// Mocks generated by Mockito 5.4.6 from annotations
// in disciplefy_bible_study/test/features/voice_buddy/voice_last_word_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:disciplefy_bible_study/core/error/failures.dart' as _i6;
import 'package:disciplefy_bible_study/core/models/app_language.dart' as _i16;
import 'package:disciplefy_bible_study/core/services/language_preference_service.dart'
    as _i15;
import 'package:disciplefy_bible_study/features/study_generation/domain/entities/study_mode.dart'
    as _i17;
import 'package:disciplefy_bible_study/features/voice_buddy/data/services/speech_service.dart'
    as _i9;
import 'package:disciplefy_bible_study/features/voice_buddy/data/services/tts_service.dart'
    as _i13;
import 'package:disciplefy_bible_study/features/voice_buddy/domain/entities/voice_conversation_entity.dart'
    as _i7;
import 'package:disciplefy_bible_study/features/voice_buddy/domain/entities/voice_preferences_entity.dart'
    as _i8;
import 'package:disciplefy_bible_study/features/voice_buddy/domain/repositories/voice_buddy_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:speech_to_text/speech_recognition_error.dart' as _i12;
import 'package:speech_to_text/speech_recognition_result.dart' as _i11;
import 'package:speech_to_text/speech_to_text.dart' as _i10;
import 'package:supabase/supabase.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionsClient_1 extends _i1.SmartFake
    implements _i3.FunctionsClient {
  _FakeFunctionsClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseStorageClient_2 extends _i1.SmartFake
    implements _i3.SupabaseStorageClient {
  _FakeSupabaseStorageClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeClient_3 extends _i1.SmartFake
    implements _i3.RealtimeClient {
  _FakeRealtimeClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestClient_4 extends _i1.SmartFake
    implements _i3.PostgrestClient {
  _FakePostgrestClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueClient_5 extends _i1.SmartFake implements _i3.GoTrueClient {
  _FakeGoTrueClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQueryBuilder_6 extends _i1.SmartFake
    implements _i3.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQuerySchema_7 extends _i1.SmartFake
    implements _i3.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestFilterBuilder_8<T1> extends _i1.SmartFake
    implements _i3.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeChannel_9 extends _i1.SmartFake
    implements _i3.RealtimeChannel {
  _FakeRealtimeChannel_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueAdminApi_10 extends _i1.SmartFake
    implements _i3.GoTrueAdminApi {
  _FakeGoTrueAdminApi_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueMFAApi_11 extends _i1.SmartFake implements _i3.GoTrueMFAApi {
  _FakeGoTrueMFAApi_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_12 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOAuthResponse_13 extends _i1.SmartFake implements _i3.OAuthResponse {
  _FakeOAuthResponse_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthSessionUrlResponse_14 extends _i1.SmartFake
    implements _i3.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResendResponse_15 extends _i1.SmartFake
    implements _i3.ResendResponse {
  _FakeResendResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserResponse_16 extends _i1.SmartFake implements _i3.UserResponse {
  _FakeUserResponse_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_17 extends _i1.SmartFake implements Object {
  _FakeObject_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VoiceBuddyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceBuddyRepository extends _i1.Mock
    implements _i4.VoiceBuddyRepository {
  @override
  _i5.Future<
      _i2.Either<_i6.Failure, _i7.VoiceConversationEntity>> startConversation({
    required String? languageCode,
    required _i7.ConversationType? conversationType,
    String? relatedStudyGuideId,
    String? relatedScripture,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startConversation,
          [],
          {
            #languageCode: languageCode,
            #conversationType: conversationType,
            #relatedStudyGuideId: relatedStudyGuideId,
            #relatedScripture: relatedScripture,
          },
        ),
        returnValue: _i5
            .Future<_i2.Either<_i6.Failure, _i7.VoiceConversationEntity>>.value(
            _FakeEither_0<_i6.Failure, _i7.VoiceConversationEntity>(
          this,
          Invocation.method(
            #startConversation,
            [],
            {
              #languageCode: languageCode,
              #conversationType: conversationType,
              #relatedStudyGuideId: relatedStudyGuideId,
              #relatedScripture: relatedScripture,
            },
          ),
        )),
        returnValueForMissingStub: _i5
            .Future<_i2.Either<_i6.Failure, _i7.VoiceConversationEntity>>.value(
            _FakeEither_0<_i6.Failure, _i7.VoiceConversationEntity>(
          this,
          Invocation.method(
            #startConversation,
            [],
            {
              #languageCode: languageCode,
              #conversationType: conversationType,
              #relatedStudyGuideId: relatedStudyGuideId,
              #relatedScripture: relatedScripture,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.VoiceConversationEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> endConversation({
    required String? conversationId,
    int? rating,
    String? feedbackText,
    bool? wasHelpful,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #endConversation,
          [],
          {
            #conversationId: conversationId,
            #rating: rating,
            #feedbackText: feedbackText,
            #wasHelpful: wasHelpful,
          },
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #endConversation,
            [],
            {
              #conversationId: conversationId,
              #rating: rating,
              #feedbackText: feedbackText,
              #wasHelpful: wasHelpful,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i6.Failure, void>>.value(
                _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #endConversation,
            [],
            {
              #conversationId: conversationId,
              #rating: rating,
              #feedbackText: feedbackText,
              #wasHelpful: wasHelpful,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.VoiceConversationEntity>>>
      getConversationHistory({
    int? limit = 20,
    int? offset = 0,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getConversationHistory,
              [],
              {
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure,
                        List<_i7.VoiceConversationEntity>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.VoiceConversationEntity>>(
              this,
              Invocation.method(
                #getConversationHistory,
                [],
                {
                  #limit: limit,
                  #offset: offset,
                },
              ),
            )),
            returnValueForMissingStub: _i5.Future<
                    _i2.Either<_i6.Failure,
                        List<_i7.VoiceConversationEntity>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.VoiceConversationEntity>>(
              this,
              Invocation.method(
                #getConversationHistory,
                [],
                {
                  #limit: limit,
                  #offset: offset,
                },
              ),
            )),
          ) as _i5.Future<
              _i2.Either<_i6.Failure, List<_i7.VoiceConversationEntity>>>);

  @override
  _i5.Future<
      _i2.Either<_i6.Failure, _i7.VoiceConversationEntity>> getConversation(
          String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversation,
          [conversationId],
        ),
        returnValue: _i5
            .Future<_i2.Either<_i6.Failure, _i7.VoiceConversationEntity>>.value(
            _FakeEither_0<_i6.Failure, _i7.VoiceConversationEntity>(
          this,
          Invocation.method(
            #getConversation,
            [conversationId],
          ),
        )),
        returnValueForMissingStub: _i5
            .Future<_i2.Either<_i6.Failure, _i7.VoiceConversationEntity>>.value(
            _FakeEither_0<_i6.Failure, _i7.VoiceConversationEntity>(
          this,
          Invocation.method(
            #getConversation,
            [conversationId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.VoiceConversationEntity>>);

  @override
  _i5.Future<
      _i2.Either<_i6.Failure, _i7.ConversationMessageEntity>> saveMessage({
    required String? conversationId,
    required int? messageOrder,
    required _i7.MessageRole? role,
    required String? contentText,
    required String? contentLanguage,
    double? audioDurationSeconds,
    double? transcriptionConfidence,
    String? llmModelUsed,
    int? llmTokensUsed,
    List<String>? scriptureReferences,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMessage,
          [],
          {
            #conversationId: conversationId,
            #messageOrder: messageOrder,
            #role: role,
            #contentText: contentText,
            #contentLanguage: contentLanguage,
            #audioDurationSeconds: audioDurationSeconds,
            #transcriptionConfidence: transcriptionConfidence,
            #llmModelUsed: llmModelUsed,
            #llmTokensUsed: llmTokensUsed,
            #scriptureReferences: scriptureReferences,
          },
        ),
        returnValue: _i5.Future<
                _i2.Either<_i6.Failure, _i7.ConversationMessageEntity>>.value(
            _FakeEither_0<_i6.Failure, _i7.ConversationMessageEntity>(
          this,
          Invocation.method(
            #saveMessage,
            [],
            {
              #conversationId: conversationId,
              #messageOrder: messageOrder,
              #role: role,
              #contentText: contentText,
              #contentLanguage: contentLanguage,
              #audioDurationSeconds: audioDurationSeconds,
              #transcriptionConfidence: transcriptionConfidence,
              #llmModelUsed: llmModelUsed,
              #llmTokensUsed: llmTokensUsed,
              #scriptureReferences: scriptureReferences,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i2.Either<_i6.Failure, _i7.ConversationMessageEntity>>.value(
            _FakeEither_0<_i6.Failure, _i7.ConversationMessageEntity>(
          this,
          Invocation.method(
            #saveMessage,
            [],
            {
              #conversationId: conversationId,
              #messageOrder: messageOrder,
              #role: role,
              #contentText: contentText,
              #contentLanguage: contentLanguage,
              #audioDurationSeconds: audioDurationSeconds,
              #transcriptionConfidence: transcriptionConfidence,
              #llmModelUsed: llmModelUsed,
              #llmTokensUsed: llmTokensUsed,
              #scriptureReferences: scriptureReferences,
            },
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.ConversationMessageEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i8.VoiceQuotaEntity>> checkQuota() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkQuota,
          [],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i8.VoiceQuotaEntity>>.value(
                _FakeEither_0<_i6.Failure, _i8.VoiceQuotaEntity>(
          this,
          Invocation.method(
            #checkQuota,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i6.Failure, _i8.VoiceQuotaEntity>>.value(
                _FakeEither_0<_i6.Failure, _i8.VoiceQuotaEntity>(
          this,
          Invocation.method(
            #checkQuota,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i8.VoiceQuotaEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> incrementUsage(
          String? languageCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementUsage,
          [languageCode],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #incrementUsage,
            [languageCode],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i6.Failure, void>>.value(
                _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #incrementUsage,
            [languageCode],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>
      getPreferences() => (super.noSuchMethod(
            Invocation.method(
              #getPreferences,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>.value(
                _FakeEither_0<_i6.Failure, _i8.VoicePreferencesEntity>(
              this,
              Invocation.method(
                #getPreferences,
                [],
              ),
            )),
            returnValueForMissingStub: _i5.Future<
                    _i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>.value(
                _FakeEither_0<_i6.Failure, _i8.VoicePreferencesEntity>(
              this,
              Invocation.method(
                #getPreferences,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>);

  @override
  _i5.Future<
      _i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>> updatePreferences(
          _i8.VoicePreferencesEntity? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePreferences,
          [preferences],
        ),
        returnValue: _i5
            .Future<_i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>.value(
            _FakeEither_0<_i6.Failure, _i8.VoicePreferencesEntity>(
          this,
          Invocation.method(
            #updatePreferences,
            [preferences],
          ),
        )),
        returnValueForMissingStub: _i5
            .Future<_i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>.value(
            _FakeEither_0<_i6.Failure, _i8.VoicePreferencesEntity>(
          this,
          Invocation.method(
            #updatePreferences,
            [preferences],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>
      resetPreferences() => (super.noSuchMethod(
            Invocation.method(
              #resetPreferences,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>.value(
                _FakeEither_0<_i6.Failure, _i8.VoicePreferencesEntity>(
              this,
              Invocation.method(
                #resetPreferences,
                [],
              ),
            )),
            returnValueForMissingStub: _i5.Future<
                    _i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>.value(
                _FakeEither_0<_i6.Failure, _i8.VoicePreferencesEntity>(
              this,
              Invocation.method(
                #resetPreferences,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i8.VoicePreferencesEntity>>);
}

/// A class which mocks [SpeechService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechService extends _i1.Mock implements _i9.SpeechService {
  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<bool> isIosSimulator() => (super.noSuchMethod(
        Invocation.method(
          #isIosSimulator,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i10.LocaleName>> getAvailableLocales() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableLocales,
          [],
        ),
        returnValue:
            _i5.Future<List<_i10.LocaleName>>.value(<_i10.LocaleName>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i10.LocaleName>>.value(<_i10.LocaleName>[]),
      ) as _i5.Future<List<_i10.LocaleName>>);

  @override
  _i5.Future<bool> isLanguageSupported(String? languageCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #isLanguageSupported,
          [languageCode],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> startListening({
    required String? languageCode,
    required void Function(_i11.SpeechRecognitionResult)? onResult,
    void Function(double)? onSoundLevelChange,
    void Function(String)? onStatusChange,
    void Function(_i12.SpeechRecognitionError)? onError,
    Duration? pauseFor = const Duration(seconds: 60),
    Duration? listenFor = const Duration(seconds: 60),
    bool? partialResults = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startListening,
          [],
          {
            #languageCode: languageCode,
            #onResult: onResult,
            #onSoundLevelChange: onSoundLevelChange,
            #onStatusChange: onStatusChange,
            #onError: onError,
            #pauseFor: pauseFor,
            #listenFor: listenFor,
            #partialResults: partialResults,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopListening() => (super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelListening() => (super.noSuchMethod(
        Invocation.method(
          #cancelListening,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void releaseCallbacks() => super.noSuchMethod(
        Invocation.method(
          #releaseCallbacks,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TTSService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTTSService extends _i1.Mock implements _i13.TTSService {
  @override
  _i13.TtsState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i13.TtsState.playing,
        returnValueForMissingStub: _i13.TtsState.playing,
      ) as _i13.TtsState);

  @override
  bool get isSpeaking => (super.noSuchMethod(
        Invocation.getter(#isSpeaking),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isUsingCloudTts => (super.noSuchMethod(
        Invocation.getter(#isUsingCloudTts),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isStreaming => (super.noSuchMethod(
        Invocation.getter(#isStreaming),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get queueLength => (super.noSuchMethod(
        Invocation.getter(#queueLength),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void setUseCloudTts(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setUseCloudTts,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<dynamic>> getAvailableLanguages() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableLanguages,
          [],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<List<dynamic>> getAvailableVoices() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableVoices,
          [],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<bool> isLanguageAvailable(String? languageCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #isLanguageAvailable,
          [languageCode],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setLanguage(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [languageCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setSpeechRate(double? rate) => (super.noSuchMethod(
        Invocation.method(
          #setSpeechRate,
          [rate],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setPitch(double? pitch) => (super.noSuchMethod(
        Invocation.method(
          #setPitch,
          [pitch],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setVoice(Map<String, String>? voice) => (super.noSuchMethod(
        Invocation.method(
          #setVoice,
          [voice],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> speak(String? text) => (super.noSuchMethod(
        Invocation.method(
          #speak,
          [text],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> speakWithSettings({
    required String? text,
    required String? languageCode,
    double? speakingRate,
    double? pitch,
    String? voiceGender,
    void Function()? onComplete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #speakWithSettings,
          [],
          {
            #text: text,
            #languageCode: languageCode,
            #speakingRate: speakingRate,
            #pitch: pitch,
            #voiceGender: voiceGender,
            #onComplete: onComplete,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pauseAudio() => (super.noSuchMethod(
        Invocation.method(
          #pauseAudio,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resumeAudio() => (super.noSuchMethod(
        Invocation.method(
          #resumeAudio,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seekTo(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [position],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Duration?> getDuration() => (super.noSuchMethod(
        Invocation.method(
          #getDuration,
          [],
        ),
        returnValue: _i5.Future<Duration?>.value(),
        returnValueForMissingStub: _i5.Future<Duration?>.value(),
      ) as _i5.Future<Duration?>);

  @override
  _i5.Future<void> startStreamingSession({
    required String? languageCode,
    double? speakingRate = 1.0,
    double? pitch = 0.0,
    String? voiceGender = 'female',
    void Function()? onComplete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startStreamingSession,
          [],
          {
            #languageCode: languageCode,
            #speakingRate: speakingRate,
            #pitch: pitch,
            #voiceGender: voiceGender,
            #onComplete: onComplete,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addSentenceToQueue(String? sentence) => (super.noSuchMethod(
        Invocation.method(
          #addSentenceToQueue,
          [sentence],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void finishStreaming() => super.noSuchMethod(
        Invocation.method(
          #finishStreaming,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> cancelStreaming() => (super.noSuchMethod(
        Invocation.method(
          #cancelStreaming,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i3.SupabaseClient {
  @override
  _i3.FunctionsClient get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFunctionsClient_1(
          this,
          Invocation.getter(#functions),
        ),
        returnValueForMissingStub: _FakeFunctionsClient_1(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i3.FunctionsClient);

  @override
  _i3.SupabaseStorageClient get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeSupabaseStorageClient_2(
          this,
          Invocation.getter(#storage),
        ),
        returnValueForMissingStub: _FakeSupabaseStorageClient_2(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i3.SupabaseStorageClient);

  @override
  _i3.RealtimeClient get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeClient_3(
          this,
          Invocation.getter(#realtime),
        ),
        returnValueForMissingStub: _FakeRealtimeClient_3(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i3.RealtimeClient);

  @override
  _i3.PostgrestClient get rest => (super.noSuchMethod(
        Invocation.getter(#rest),
        returnValue: _FakePostgrestClient_4(
          this,
          Invocation.getter(#rest),
        ),
        returnValueForMissingStub: _FakePostgrestClient_4(
          this,
          Invocation.getter(#rest),
        ),
      ) as _i3.PostgrestClient);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  _i3.GoTrueClient get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeGoTrueClient_5(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeGoTrueClient_5(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i3.GoTrueClient);

  @override
  set functions(_i3.FunctionsClient? value) => super.noSuchMethod(
        Invocation.setter(
          #functions,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set storage(_i3.SupabaseStorageClient? value) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set realtime(_i3.RealtimeClient? value) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set rest(_i3.PostgrestClient? value) => super.noSuchMethod(
        Invocation.setter(
          #rest,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          headers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.SupabaseQueryBuilder from(String? table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_6(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
        returnValueForMissingStub: _FakeSupabaseQueryBuilder_6(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
      ) as _i3.SupabaseQueryBuilder);

  @override
  _i3.SupabaseQuerySchema schema(String? schema) => (super.noSuchMethod(
        Invocation.method(
          #schema,
          [schema],
        ),
        returnValue: _FakeSupabaseQuerySchema_7(
          this,
          Invocation.method(
            #schema,
            [schema],
          ),
        ),
        returnValueForMissingStub: _FakeSupabaseQuerySchema_7(
          this,
          Invocation.method(
            #schema,
            [schema],
          ),
        ),
      ) as _i3.SupabaseQuerySchema);

  @override
  _i3.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [fn],
          {
            #params: params,
            #get: get,
          },
        ),
        returnValue: _FakePostgrestFilterBuilder_8<T>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #get: get,
            },
          ),
        ),
        returnValueForMissingStub: _FakePostgrestFilterBuilder_8<T>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #get: get,
            },
          ),
        ),
      ) as _i3.PostgrestFilterBuilder<T>);

  @override
  _i3.RealtimeChannel channel(
    String? name, {
    _i3.RealtimeChannelConfig? opts = const _i3.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #channel,
          [name],
          {#opts: opts},
        ),
        returnValue: _FakeRealtimeChannel_9(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
        returnValueForMissingStub: _FakeRealtimeChannel_9(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
      ) as _i3.RealtimeChannel);

  @override
  List<_i3.RealtimeChannel> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: <_i3.RealtimeChannel>[],
        returnValueForMissingStub: <_i3.RealtimeChannel>[],
      ) as List<_i3.RealtimeChannel>);

  @override
  _i5.Future<String> removeChannel(_i3.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channel],
        ),
        returnValue: _i5.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<String>> removeAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #removeAllChannels,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i1.Mock implements _i3.GoTrueClient {
  @override
  _i3.GoTrueAdminApi get admin => (super.noSuchMethod(
        Invocation.getter(#admin),
        returnValue: _FakeGoTrueAdminApi_10(
          this,
          Invocation.getter(#admin),
        ),
        returnValueForMissingStub: _FakeGoTrueAdminApi_10(
          this,
          Invocation.getter(#admin),
        ),
      ) as _i3.GoTrueAdminApi);

  @override
  _i3.GoTrueMFAApi get mfa => (super.noSuchMethod(
        Invocation.getter(#mfa),
        returnValue: _FakeGoTrueMFAApi_11(
          this,
          Invocation.getter(#mfa),
        ),
        returnValueForMissingStub: _FakeGoTrueMFAApi_11(
          this,
          Invocation.getter(#mfa),
        ),
      ) as _i3.GoTrueMFAApi);

  @override
  _i5.Stream<_i3.AuthState> get onAuthStateChange => (super.noSuchMethod(
        Invocation.getter(#onAuthStateChange),
        returnValue: _i5.Stream<_i3.AuthState>.empty(),
        returnValueForMissingStub: _i5.Stream<_i3.AuthState>.empty(),
      ) as _i5.Stream<_i3.AuthState>);

  @override
  _i5.Stream<_i3.AuthState> get onAuthStateChangeSync => (super.noSuchMethod(
        Invocation.getter(#onAuthStateChangeSync),
        returnValue: _i5.Stream<_i3.AuthState>.empty(),
        returnValueForMissingStub: _i5.Stream<_i3.AuthState>.empty(),
      ) as _i5.Stream<_i3.AuthState>);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  set admin(_i3.GoTrueAdminApi? value) => super.noSuchMethod(
        Invocation.setter(
          #admin,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mfa(_i3.GoTrueMFAApi? value) => super.noSuchMethod(
        Invocation.setter(
          #mfa,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
          {
            #data: data,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
            {
              #data: data,
              #captchaToken: captchaToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
            {
              #data: data,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<_i3.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i3.OtpChannel? channel = _i3.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #emailRedirectTo: emailRedirectTo,
            #data: data,
            #captchaToken: captchaToken,
            #channel: channel,
          },
        ),
        returnValue: _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            },
          ),
        )),
      ) as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<_i3.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPassword,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signInWithPassword,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signInWithPassword,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<_i3.OAuthResponse> getOAuthSignInUrl({
    required _i3.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOAuthSignInUrl,
          [],
          {
            #provider: provider,
            #redirectTo: redirectTo,
            #scopes: scopes,
            #queryParams: queryParams,
          },
        ),
        returnValue: _i5.Future<_i3.OAuthResponse>.value(_FakeOAuthResponse_13(
          this,
          Invocation.method(
            #getOAuthSignInUrl,
            [],
            {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.OAuthResponse>.value(_FakeOAuthResponse_13(
          this,
          Invocation.method(
            #getOAuthSignInUrl,
            [],
            {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
      ) as _i5.Future<_i3.OAuthResponse>);

  @override
  _i5.Future<_i3.AuthSessionUrlResponse> exchangeCodeForSession(
          String? authCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #exchangeCodeForSession,
          [authCode],
        ),
        returnValue: _i5.Future<_i3.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_14(
          this,
          Invocation.method(
            #exchangeCodeForSession,
            [authCode],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_14(
          this,
          Invocation.method(
            #exchangeCodeForSession,
            [authCode],
          ),
        )),
      ) as _i5.Future<_i3.AuthSessionUrlResponse>);

  @override
  _i5.Future<_i3.AuthResponse> signInWithIdToken({
    required _i3.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithIdToken,
          [],
          {
            #provider: provider,
            #idToken: idToken,
            #accessToken: accessToken,
            #nonce: nonce,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signInWithIdToken,
            [],
            {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #signInWithIdToken,
            [],
            {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i3.OtpChannel? channel = _i3.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithOtp,
          [],
          {
            #email: email,
            #phone: phone,
            #emailRedirectTo: emailRedirectTo,
            #shouldCreateUser: shouldCreateUser,
            #data: data,
            #captchaToken: captchaToken,
            #channel: channel,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i3.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [],
          {
            #email: email,
            #phone: phone,
            #token: token,
            #type: type,
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
            #tokenHash: tokenHash,
          },
        ),
        returnValue: _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #verifyOTP,
            [],
            {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #verifyOTP,
            [],
            {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            },
          ),
        )),
      ) as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSSOSignInUrl,
          [],
          {
            #providerId: providerId,
            #domain: domain,
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i5.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #getSSOSignInUrl,
            [],
            {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #getSSOSignInUrl,
            [],
            {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i3.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSession,
          [refreshToken],
        ),
        returnValue: _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #refreshSession,
            [refreshToken],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #refreshSession,
            [refreshToken],
          ),
        )),
      ) as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<void> reauthenticate() => (super.noSuchMethod(
        Invocation.method(
          #reauthenticate,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ResendResponse> resend({
    String? email,
    String? phone,
    required _i3.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resend,
          [],
          {
            #email: email,
            #phone: phone,
            #type: type,
            #emailRedirectTo: emailRedirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue:
            _i5.Future<_i3.ResendResponse>.value(_FakeResendResponse_15(
          this,
          Invocation.method(
            #resend,
            [],
            {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.ResendResponse>.value(_FakeResendResponse_15(
          this,
          Invocation.method(
            #resend,
            [],
            {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i5.Future<_i3.ResendResponse>);

  @override
  _i5.Future<_i3.UserResponse> getUser([String? jwt]) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [jwt],
        ),
        returnValue: _i5.Future<_i3.UserResponse>.value(_FakeUserResponse_16(
          this,
          Invocation.method(
            #getUser,
            [jwt],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.UserResponse>.value(_FakeUserResponse_16(
          this,
          Invocation.method(
            #getUser,
            [jwt],
          ),
        )),
      ) as _i5.Future<_i3.UserResponse>);

  @override
  _i5.Future<_i3.UserResponse> updateUser(
    _i3.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [attributes],
          {#emailRedirectTo: emailRedirectTo},
        ),
        returnValue: _i5.Future<_i3.UserResponse>.value(_FakeUserResponse_16(
          this,
          Invocation.method(
            #updateUser,
            [attributes],
            {#emailRedirectTo: emailRedirectTo},
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.UserResponse>.value(_FakeUserResponse_16(
          this,
          Invocation.method(
            #updateUser,
            [attributes],
            {#emailRedirectTo: emailRedirectTo},
          ),
        )),
      ) as _i5.Future<_i3.UserResponse>);

  @override
  _i5.Future<_i3.AuthResponse> setSession(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSession,
          [refreshToken],
        ),
        returnValue: _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #setSession,
            [refreshToken],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #setSession,
            [refreshToken],
          ),
        )),
      ) as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<_i3.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionFromUrl,
          [originUrl],
          {#storeSession: storeSession},
        ),
        returnValue: _i5.Future<_i3.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_14(
          this,
          Invocation.method(
            #getSessionFromUrl,
            [originUrl],
            {#storeSession: storeSession},
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_14(
          this,
          Invocation.method(
            #getSessionFromUrl,
            [originUrl],
            {#storeSession: storeSession},
          ),
        )),
      ) as _i5.Future<_i3.AuthSessionUrlResponse>);

  @override
  _i5.Future<void> signOut(
          {_i3.SignOutScope? scope = _i3.SignOutScope.local}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
          {#scope: scope},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPasswordForEmail,
          [email],
          {
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.UserIdentity>> getUserIdentities() => (super.noSuchMethod(
        Invocation.method(
          #getUserIdentities,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.UserIdentity>>.value(<_i3.UserIdentity>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.UserIdentity>>.value(<_i3.UserIdentity>[]),
      ) as _i5.Future<List<_i3.UserIdentity>>);

  @override
  _i5.Future<_i3.OAuthResponse> getLinkIdentityUrl(
    _i3.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinkIdentityUrl,
          [provider],
          {
            #redirectTo: redirectTo,
            #scopes: scopes,
            #queryParams: queryParams,
          },
        ),
        returnValue: _i5.Future<_i3.OAuthResponse>.value(_FakeOAuthResponse_13(
          this,
          Invocation.method(
            #getLinkIdentityUrl,
            [provider],
            {
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.OAuthResponse>.value(_FakeOAuthResponse_13(
          this,
          Invocation.method(
            #getLinkIdentityUrl,
            [provider],
            {
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
      ) as _i5.Future<_i3.OAuthResponse>);

  @override
  _i5.Future<void> unlinkIdentity(_i3.UserIdentity? identity) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlinkIdentity,
          [identity],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setInitialSession(String? jsonStr) => (super.noSuchMethod(
        Invocation.method(
          #setInitialSession,
          [jsonStr],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverSession,
          [jsonStr],
        ),
        returnValue: _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #recoverSession,
            [jsonStr],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.AuthResponse>.value(_FakeAuthResponse_12(
          this,
          Invocation.method(
            #recoverSession,
            [jsonStr],
          ),
        )),
      ) as _i5.Future<_i3.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
        Invocation.method(
          #startAutoRefresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
        Invocation.method(
          #stopAutoRefresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyAllSubscribers(
    _i3.AuthChangeEvent? event, {
    _i3.Session? session,
    bool? broadcast = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #notifyAllSubscribers,
          [event],
          {
            #session: session,
            #broadcast: broadcast,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  Object notifyException(
    Object? exception, [
    StackTrace? stackTrace,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyException,
          [
            exception,
            stackTrace,
          ],
        ),
        returnValue: _FakeObject_17(
          this,
          Invocation.method(
            #notifyException,
            [
              exception,
              stackTrace,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeObject_17(
          this,
          Invocation.method(
            #notifyException,
            [
              exception,
              stackTrace,
            ],
          ),
        ),
      ) as Object);
}

/// A class which mocks [LanguagePreferenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguagePreferenceService extends _i1.Mock
    implements _i15.LanguagePreferenceService {
  @override
  _i5.Stream<_i16.AppLanguage> get languageChanges => (super.noSuchMethod(
        Invocation.getter(#languageChanges),
        returnValue: _i5.Stream<_i16.AppLanguage>.empty(),
        returnValueForMissingStub: _i5.Stream<_i16.AppLanguage>.empty(),
      ) as _i5.Stream<_i16.AppLanguage>);

  @override
  _i5.Stream<_i16.AppLanguage> get studyContentLanguageChanges =>
      (super.noSuchMethod(
        Invocation.getter(#studyContentLanguageChanges),
        returnValue: _i5.Stream<_i16.AppLanguage>.empty(),
        returnValueForMissingStub: _i5.Stream<_i16.AppLanguage>.empty(),
      ) as _i5.Stream<_i16.AppLanguage>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i16.AppLanguage> getSelectedLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedLanguage,
          [],
        ),
        returnValue:
            _i5.Future<_i16.AppLanguage>.value(_i16.AppLanguage.english),
        returnValueForMissingStub:
            _i5.Future<_i16.AppLanguage>.value(_i16.AppLanguage.english),
      ) as _i5.Future<_i16.AppLanguage>);

  @override
  _i5.Future<void> saveLanguagePreference(_i16.AppLanguage? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLanguagePreference,
          [language],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> hasCompletedLanguageSelection() => (super.noSuchMethod(
        Invocation.method(
          #hasCompletedLanguageSelection,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> markLanguageSelectionCompleted() => (super.noSuchMethod(
        Invocation.method(
          #markLanguageSelectionCompleted,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> syncWithProfile() => (super.noSuchMethod(
        Invocation.method(
          #syncWithProfile,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetLanguageSelectionStatus() => (super.noSuchMethod(
        Invocation.method(
          #resetLanguageSelectionStatus,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void invalidateLanguageCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateLanguageCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> saveStudyModePreference(_i17.StudyMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStudyModePreference,
          [mode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveStudyModePreferenceRaw(String? modeValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStudyModePreferenceRaw,
          [modeValue],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearStudyModePreference() => (super.noSuchMethod(
        Invocation.method(
          #clearStudyModePreference,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getStudyModePreferenceRaw() => (super.noSuchMethod(
        Invocation.method(
          #getStudyModePreferenceRaw,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> cacheLearningPathStudyModePreference(String? modeValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheLearningPathStudyModePreference,
          [modeValue],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i17.StudyMode?> getStudyModePreference() => (super.noSuchMethod(
        Invocation.method(
          #getStudyModePreference,
          [],
        ),
        returnValue: _i5.Future<_i17.StudyMode?>.value(),
        returnValueForMissingStub: _i5.Future<_i17.StudyMode?>.value(),
      ) as _i5.Future<_i17.StudyMode?>);

  @override
  _i5.Future<_i16.AppLanguage> getStudyContentLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getStudyContentLanguage,
          [],
        ),
        returnValue:
            _i5.Future<_i16.AppLanguage>.value(_i16.AppLanguage.english),
        returnValueForMissingStub:
            _i5.Future<_i16.AppLanguage>.value(_i16.AppLanguage.english),
      ) as _i5.Future<_i16.AppLanguage>);

  @override
  _i5.Future<void> saveStudyContentLanguage(_i16.AppLanguage? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStudyContentLanguage,
          [language],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setStudyContentLanguageToDefault() => (super.noSuchMethod(
        Invocation.method(
          #setStudyContentLanguageToDefault,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isStudyContentLanguageDefault() => (super.noSuchMethod(
        Invocation.method(
          #isStudyContentLanguageDefault,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> clearStudyContentLanguage() => (super.noSuchMethod(
        Invocation.method(
          #clearStudyContentLanguage,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
