include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    # Development overrides - ignore warnings and info for pre-commit
    avoid_print: ignore
    constant_identifier_names: ignore
    unused_element: ignore
    deprecated_member_use: ignore
    prefer_expression_function_bodies: ignore
    unreachable_switch_default: ignore
    unused_local_variable: ignore
    unused_import: ignore
    unused_field: ignore
    prefer_const_constructors: ignore
    type_literal_in_constant_pattern: ignore
    use_build_context_synchronously: ignore
    prefer_initializing_formals: ignore
    overridden_fields: ignore

linter:
  rules:
    # Style
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    
    # Documentation (disabled for development - too verbose)
    # public_member_api_docs: true
    
    # Design
    avoid_function_literals_in_foreach_calls: true
    avoid_redundant_argument_values: true
    prefer_expression_function_bodies: true
    
    # Errors
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    
    # Pub (disabled for development - not critical)
    # sort_pub_dependencies: true
    
    # Additional quality rules (avoid_print disabled for development logging)
    # avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_empty_else: true
    curly_braces_in_flow_control_structures: true
