/**
 * Generates a migration that sets suggested_verse_translations.verse_text to the
 * self-hosted Bible text served by rs-backend: BSB (en), IRV Hindi (hi) and IRV
 * Malayalam (ml), read from rs-backend/data/bible/*.tsv.
 *
 * The verse references are read from the suggested-verse seed migration, so the
 * output is reproducible from the repository alone. The generated SQL is
 * idempotent: it updates by (reference, book, chapter, verse) and language, and
 * moves memory_verses rows that still hold the previous suggested wording (added
 * from the suggestion list, saved as source_type 'manual') to the new text.
 *
 * Usage (from backend/):
 *   deno run --allow-read --allow-write scripts/generate-suggested-verse-text-migration.ts \
 *     supabase/migrations/<timestamp>_suggested_verses_bsb_irv_text.sql
 */

import { bookCodeFor } from '../supabase/functions/_shared/services/bible-text-service.ts'
import { tidyVerseText } from '../supabase/functions/daily-verse/daily-verse-service.ts'

const ROOT = new URL('../../', import.meta.url).pathname
const SEED = `${ROOT}backend/supabase/migrations/20260218000001_suggested_verses_seed.sql`
const DATA = `${ROOT}rs-backend/data/bible/`
const FILES = { en: 'bsb.tsv', hi: 'irv-hi.tsv', ml: 'irv-ml.tsv' } as const
type Lang = keyof typeof FILES

interface SeedVerse {
  reference: string
  book: string
  chapter: number
  start: number
  end: number | null
}

/** book|chapter → rows of [verseFrom, verseTo, text] (handles merged spans like "24-25"). */
function loadTsv(file: string): Map<string, Array<[number, number, string]>> {
  const map = new Map<string, Array<[number, number, string]>>()
  for (const line of Deno.readTextFileSync(DATA + file).split('\n')) {
    if (!line || line.startsWith('#')) continue
    const [book, chapter, verse, text] = line.split('\t')
    const [from, to] = verse.split('-').map(Number)
    const key = `${book}|${chapter}`
    if (!map.has(key)) map.set(key, [])
    map.get(key)!.push([from, to ?? from, text.trim()])
  }
  return map
}

function readSeed(): SeedVerse[] {
  const sql = Deno.readTextFileSync(SEED)
  const re = /SELECT public\._seed_suggested_verse\(\s*'([^']+)','([^']+)',(\d+),(\d+),(NULL|\d+)/g
  const seen = new Set<string>()
  const out: SeedVerse[] = []
  for (const m of sql.matchAll(re)) {
    if (seen.has(m[1])) continue
    seen.add(m[1])
    out.push({
      reference: m[1],
      book: m[2],
      chapter: Number(m[3]),
      start: Number(m[4]),
      end: m[5] === 'NULL' ? null : Number(m[5]),
    })
  }
  return out
}

function passageText(tsv: ReturnType<typeof loadTsv>, v: SeedVerse, missing: string[], lang: Lang): string | null {
  const code = bookCodeFor(v.book)
  if (!code) throw new Error(`Unknown book ${v.book}`)
  const rows = tsv.get(`${code}|${v.chapter}`) ?? []
  const parts: string[] = []
  for (let n = v.start; n <= (v.end ?? v.start); n++) {
    const row = rows.find(([from, to]) => n >= from && n <= to)
    if (!row) {
      missing.push(`${lang} ${v.book} ${v.chapter}:${n}`)
      continue
    }
    if (!parts.includes(row[2])) parts.push(row[2])
  }
  return parts.length ? tidyVerseText(parts.join(' ')) : null
}

const q = (s: string) => `'${s.replaceAll("'", "''")}'`

const outPath = Deno.args[0]
if (!outPath) throw new Error('Pass the output migration path')

const verses = readSeed()
const missing: string[] = []
const values: string[] = []
for (const lang of Object.keys(FILES) as Lang[]) {
  const tsv = loadTsv(FILES[lang])
  for (const v of verses) {
    const text = passageText(tsv, v, missing, lang)
    if (text) values.push(`  (${q(v.reference)}, ${q(lang)}, ${q(text)})`)
  }
}

const sql = `-- =============================================================================
-- Suggested memory verses: BSB (en) / IRV Hindi (hi) / IRV Malayalam (ml) text
-- GENERATED by backend/scripts/generate-suggested-verse-text-migration.ts from
-- rs-backend/data/bible/{bsb,irv-hi,irv-ml}.tsv — do not edit by hand.
--
-- The seeded English text was NIV wording (not licensed). Replaces every
-- suggested verse text with the self-hosted public-domain / CC BY-SA text, and
-- moves memory_verses rows that were added from the suggestion list (saved as
-- source_type 'manual' with the suggested wording verbatim) to the new text.
-- Rows whose text the user typed or edited do not match and are left untouched.
-- Idempotent: re-running changes nothing.
-- =============================================================================

DROP TABLE IF EXISTS _suggested_text;
CREATE TEMP TABLE _suggested_text (reference TEXT, language_code TEXT, verse_text TEXT);

INSERT INTO _suggested_text (reference, language_code, verse_text) VALUES
${values.join(',\n')};

-- 1. memory verses copied from the old suggested wording → new wording
UPDATE public.memory_verses mv
SET verse_text = n.verse_text,
    verse_text_synced_at = NOW(),
    updated_at = NOW()
FROM public.suggested_verse_translations t
JOIN public.suggested_verses s ON s.id = t.suggested_verse_id
JOIN _suggested_text n ON n.reference = s.reference AND n.language_code = t.language_code
WHERE mv.source_type = 'manual'
  AND mv.language = t.language_code
  AND mv.verse_reference IN (t.localized_reference, s.reference)
  AND mv.verse_text = t.verse_text
  AND t.verse_text IS DISTINCT FROM n.verse_text;

-- 2. suggested verse text
UPDATE public.suggested_verse_translations t
SET verse_text = n.verse_text
FROM public.suggested_verses s, _suggested_text n
WHERE s.id = t.suggested_verse_id
  AND n.reference = s.reference
  AND n.language_code = t.language_code
  AND t.verse_text IS DISTINCT FROM n.verse_text;

DROP TABLE _suggested_text;
`

Deno.writeTextFileSync(outPath, sql)
console.log(`Wrote ${values.length} texts for ${verses.length} verses to ${outPath}`)
if (missing.length) console.log(`Missing verses (kept existing text): ${missing.join(', ')}`)
