// Mocks generated by Mockito 5.4.6 from annotations
// in disciplefy_bible_study/test/features/community/fellowship_block_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:disciplefy_bible_study/core/error/failures.dart' as _i5;
import 'package:disciplefy_bible_study/features/community/domain/entities/blocked_user_entity.dart'
    as _i10;
import 'package:disciplefy_bible_study/features/community/domain/entities/fellowship_comment_entity.dart'
    as _i9;
import 'package:disciplefy_bible_study/features/community/domain/entities/fellowship_entity.dart'
    as _i6;
import 'package:disciplefy_bible_study/features/community/domain/entities/fellowship_meeting_entity.dart'
    as _i11;
import 'package:disciplefy_bible_study/features/community/domain/entities/fellowship_member_entity.dart'
    as _i7;
import 'package:disciplefy_bible_study/features/community/domain/entities/fellowship_post_entity.dart'
    as _i8;
import 'package:disciplefy_bible_study/features/community/domain/entities/sync_calendar_result.dart'
    as _i12;
import 'package:disciplefy_bible_study/features/community/domain/repositories/community_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommunityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityRepository extends _i1.Mock
    implements _i3.CommunityRepository {
  MockCommunityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.FellowshipEntity>>>
      getFellowships(String? language) => (super.noSuchMethod(
            Invocation.method(
              #getFellowships,
              [language],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.FellowshipEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.FellowshipEntity>>(
              this,
              Invocation.method(
                #getFellowships,
                [language],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.FellowshipEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.FellowshipMemberEntity>>>
      getFellowshipMembers(String? fellowshipId) => (super.noSuchMethod(
            Invocation.method(
              #getFellowshipMembers,
              [fellowshipId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i7.FellowshipMemberEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.FellowshipMemberEntity>>(
              this,
              Invocation.method(
                #getFellowshipMembers,
                [fellowshipId],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i7.FellowshipMemberEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.FellowshipPostEntity>>>
      getFellowshipPosts({
    required String? fellowshipId,
    String? cursor,
    int? limit = 20,
    String? topicId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getFellowshipPosts,
              [],
              {
                #fellowshipId: fellowshipId,
                #cursor: cursor,
                #limit: limit,
                #topicId: topicId,
              },
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i8.FellowshipPostEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.FellowshipPostEntity>>(
              this,
              Invocation.method(
                #getFellowshipPosts,
                [],
                {
                  #fellowshipId: fellowshipId,
                  #cursor: cursor,
                  #limit: limit,
                  #topicId: topicId,
                },
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i8.FellowshipPostEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.FellowshipPostEntity>> createPost({
    required String? fellowshipId,
    required String? content,
    required String? postType,
    String? topicId,
    String? topicTitle,
    String? guideTitle,
    int? lessonIndex,
    String? studyGuideId,
    String? guideInputType,
    String? guideLanguage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [],
          {
            #fellowshipId: fellowshipId,
            #content: content,
            #postType: postType,
            #topicId: topicId,
            #topicTitle: topicTitle,
            #guideTitle: guideTitle,
            #lessonIndex: lessonIndex,
            #studyGuideId: studyGuideId,
            #guideInputType: guideInputType,
            #guideLanguage: guideLanguage,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.FellowshipPostEntity>>.value(
                _FakeEither_0<_i5.Failure, _i8.FellowshipPostEntity>(
          this,
          Invocation.method(
            #createPost,
            [],
            {
              #fellowshipId: fellowshipId,
              #content: content,
              #postType: postType,
              #topicId: topicId,
              #topicTitle: topicTitle,
              #guideTitle: guideTitle,
              #lessonIndex: lessonIndex,
              #studyGuideId: studyGuideId,
              #guideInputType: guideInputType,
              #guideLanguage: guideLanguage,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.FellowshipPostEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deletePost(String? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [postId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deletePost,
            [postId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i9.FellowshipCommentEntity>>> getComments(
          String? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [postId],
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i5.Failure, List<_i9.FellowshipCommentEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i9.FellowshipCommentEntity>>(
          this,
          Invocation.method(
            #getComments,
            [postId],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i9.FellowshipCommentEntity>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i9.FellowshipCommentEntity>> createComment({
    required String? postId,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComment,
          [],
          {
            #postId: postId,
            #content: content,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i9.FellowshipCommentEntity>>.value(
            _FakeEither_0<_i5.Failure, _i9.FellowshipCommentEntity>(
          this,
          Invocation.method(
            #createComment,
            [],
            {
              #postId: postId,
              #content: content,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i9.FellowshipCommentEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteComment(String? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteComment,
          [commentId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteComment,
            [commentId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>> toggleReaction({
    required String? postId,
    required String? reactionType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleReaction,
          [],
          {
            #postId: postId,
            #reactionType: reactionType,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, int>>(
          this,
          Invocation.method(
            #toggleReaction,
            [],
            {
              #postId: postId,
              #reactionType: reactionType,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> joinFellowship(
          String? inviteToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinFellowship,
          [inviteToken],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #joinFellowship,
            [inviteToken],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> createFellowship({
    required String? name,
    String? description,
    int? maxMembers,
    bool? isPublic = false,
    String? language = 'en',
    String? postingPermission = 'all_members',
    bool? unlimitedMembers = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFellowship,
          [],
          {
            #name: name,
            #description: description,
            #maxMembers: maxMembers,
            #isPublic: isPublic,
            #language: language,
            #postingPermission: postingPermission,
            #unlimitedMembers: unlimitedMembers,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #createFellowship,
            [],
            {
              #name: name,
              #description: description,
              #maxMembers: maxMembers,
              #isPublic: isPublic,
              #language: language,
              #postingPermission: postingPermission,
              #unlimitedMembers: unlimitedMembers,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> setFellowshipStudy({
    required String? fellowshipId,
    required String? learningPathId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFellowshipStudy,
          [],
          {
            #fellowshipId: fellowshipId,
            #learningPathId: learningPathId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #setFellowshipStudy,
            [],
            {
              #fellowshipId: fellowshipId,
              #learningPathId: learningPathId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> advanceStudy(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #advanceStudy,
          [fellowshipId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #advanceStudy,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> resetStudy(String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetStudy,
          [fellowshipId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #resetStudy,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> leaveFellowship(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveFellowship,
          [fellowshipId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #leaveFellowship,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteFellowship(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFellowship,
          [fellowshipId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteFellowship,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> muteMember({
    required String? fellowshipId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteMember,
          [],
          {
            #fellowshipId: fellowshipId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #muteMember,
            [],
            {
              #fellowshipId: fellowshipId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unmuteMember({
    required String? fellowshipId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unmuteMember,
          [],
          {
            #fellowshipId: fellowshipId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #unmuteMember,
            [],
            {
              #fellowshipId: fellowshipId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeMember({
    required String? fellowshipId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [],
          {
            #fellowshipId: fellowshipId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeMember,
            [],
            {
              #fellowshipId: fellowshipId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> createInvite(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInvite,
          [fellowshipId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #createInvite,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getFellowship(
    String? fellowshipId,
    String? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFellowship,
          [
            fellowshipId,
            language,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getFellowship,
            [
              fellowshipId,
              language,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateFellowship({
    required String? fellowshipId,
    String? name,
    String? description,
    int? maxMembers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFellowship,
          [],
          {
            #fellowshipId: fellowshipId,
            #name: name,
            #description: description,
            #maxMembers: maxMembers,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateFellowship,
            [],
            {
              #fellowshipId: fellowshipId,
              #name: name,
              #description: description,
              #maxMembers: maxMembers,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>> listInvites(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listInvites,
          [fellowshipId],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>.value(
            _FakeEither_0<_i5.Failure, List<Map<String, dynamic>>>(
          this,
          Invocation.method(
            #listInvites,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> revokeInvite({
    required String? fellowshipId,
    required String? inviteId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeInvite,
          [],
          {
            #fellowshipId: fellowshipId,
            #inviteId: inviteId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #revokeInvite,
            [],
            {
              #fellowshipId: fellowshipId,
              #inviteId: inviteId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> transferMentor({
    required String? fellowshipId,
    required String? newMentorUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferMentor,
          [],
          {
            #fellowshipId: fellowshipId,
            #newMentorUserId: newMentorUserId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #transferMentor,
            [],
            {
              #fellowshipId: fellowshipId,
              #newMentorUserId: newMentorUserId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> reportContent({
    required String? fellowshipId,
    required String? contentType,
    required String? contentId,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportContent,
          [],
          {
            #fellowshipId: fellowshipId,
            #contentType: contentType,
            #contentId: contentId,
            #reason: reason,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #reportContent,
            [],
            {
              #fellowshipId: fellowshipId,
              #contentType: contentType,
              #contentId: contentId,
              #reason: reason,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> blockUser({
    required String? blockedUserId,
    String? fellowshipId,
    String? contentType,
    String? contentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [],
          {
            #blockedUserId: blockedUserId,
            #fellowshipId: fellowshipId,
            #contentType: contentType,
            #contentId: contentId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #blockUser,
            [],
            {
              #blockedUserId: blockedUserId,
              #fellowshipId: fellowshipId,
              #contentType: contentType,
              #contentId: contentId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unblockUser(
          String? blockedUserId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [blockedUserId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #unblockUser,
            [blockedUserId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.BlockedUserEntity>>>
      getBlockedUsers() => (super.noSuchMethod(
            Invocation.method(
              #getBlockedUsers,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i10.BlockedUserEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.BlockedUserEntity>>(
              this,
              Invocation.method(
                #getBlockedUsers,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i10.BlockedUserEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>> getTopicPostCounts(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopicPostCounts,
          [fellowshipId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, int>>(
          this,
          Invocation.method(
            #getTopicPostCounts,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.DiscoverPage>> discoverFellowships({
    String? language,
    String? search,
    String? cursor,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverFellowships,
          [],
          {
            #language: language,
            #search: search,
            #cursor: cursor,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i3.DiscoverPage>>.value(
                _FakeEither_0<_i5.Failure, _i3.DiscoverPage>(
          this,
          Invocation.method(
            #discoverFellowships,
            [],
            {
              #language: language,
              #search: search,
              #cursor: cursor,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i3.DiscoverPage>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> joinPublicFellowship(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinPublicFellowship,
          [fellowshipId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #joinPublicFellowship,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i11.FellowshipMeetingEntity>>> getMeetings(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetings,
          [fellowshipId],
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i5.Failure, List<_i11.FellowshipMeetingEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i11.FellowshipMeetingEntity>>(
          this,
          Invocation.method(
            #getMeetings,
            [fellowshipId],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i11.FellowshipMeetingEntity>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i11.FellowshipMeetingEntity>> createMeeting({
    required String? fellowshipId,
    required String? title,
    String? description,
    required String? startsAt,
    required int? durationMinutes,
    required String? timeZone,
    String? recurrence,
    String? location,
    String? googleAccessToken,
    String? googleRefreshToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMeeting,
          [],
          {
            #fellowshipId: fellowshipId,
            #title: title,
            #description: description,
            #startsAt: startsAt,
            #durationMinutes: durationMinutes,
            #timeZone: timeZone,
            #recurrence: recurrence,
            #location: location,
            #googleAccessToken: googleAccessToken,
            #googleRefreshToken: googleRefreshToken,
          },
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, _i11.FellowshipMeetingEntity>>.value(
            _FakeEither_0<_i5.Failure, _i11.FellowshipMeetingEntity>(
          this,
          Invocation.method(
            #createMeeting,
            [],
            {
              #fellowshipId: fellowshipId,
              #title: title,
              #description: description,
              #startsAt: startsAt,
              #durationMinutes: durationMinutes,
              #timeZone: timeZone,
              #recurrence: recurrence,
              #location: location,
              #googleAccessToken: googleAccessToken,
              #googleRefreshToken: googleRefreshToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i11.FellowshipMeetingEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> cancelMeeting(
    String? meetingId, {
    String? googleAccessToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelMeeting,
          [meetingId],
          {#googleAccessToken: googleAccessToken},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #cancelMeeting,
            [meetingId],
            {#googleAccessToken: googleAccessToken},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i12.SyncCalendarResult>> syncFellowshipCalendar(
    String? fellowshipId, {
    String? googleAccessToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncFellowshipCalendar,
          [fellowshipId],
          {#googleAccessToken: googleAccessToken},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i12.SyncCalendarResult>>.value(
                _FakeEither_0<_i5.Failure, _i12.SyncCalendarResult>(
          this,
          Invocation.method(
            #syncFellowshipCalendar,
            [fellowshipId],
            {#googleAccessToken: googleAccessToken},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i12.SyncCalendarResult>>);
}
