// Mocks generated by Mockito 5.4.6 from annotations
// in disciplefy_bible_study/test/core/services/content_language_independence_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i11;

import 'package:dartz/dartz.dart' as _i3;
import 'package:disciplefy_bible_study/core/error/failures.dart' as _i13;
import 'package:disciplefy_bible_study/core/models/app_language.dart' as _i15;
import 'package:disciplefy_bible_study/core/services/auth_state_provider.dart'
    as _i8;
import 'package:disciplefy_bible_study/core/services/language_cache_coordinator.dart'
    as _i17;
import 'package:disciplefy_bible_study/features/auth/data/services/auth_service.dart'
    as _i4;
import 'package:disciplefy_bible_study/features/auth/domain/entities/auth_params.dart'
    as _i7;
import 'package:disciplefy_bible_study/features/auth/presentation/bloc/auth_bloc.dart'
    as _i10;
import 'package:disciplefy_bible_study/features/auth/presentation/bloc/auth_state.dart'
    as _i2;
import 'package:disciplefy_bible_study/features/study_generation/domain/entities/study_mode.dart'
    as _i16;
import 'package:disciplefy_bible_study/features/user_profile/data/services/user_profile_service.dart'
    as _i12;
import 'package:disciplefy_bible_study/features/user_profile/domain/entities/user_profile_entity.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:supabase_flutter/supabase_flutter.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i6.AuthState> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i5.Stream<_i6.AuthState>.empty(),
      ) as _i5.Stream<_i6.AuthState>);

  @override
  bool get isEmailVerified => (super.noSuchMethod(
        Invocation.getter(#isEmailVerified),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<bool> isAuthenticatedAsync() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticatedAsync,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isTokenValid() => (super.noSuchMethod(
        Invocation.method(
          #isTokenValid,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> ensureTokenValid() => (super.noSuchMethod(
        Invocation.method(
          #ensureTokenValid,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> refreshToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> processGoogleOAuthCallback(
          _i7.GoogleOAuthCallbackParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #processGoogleOAuthCallback,
          [params],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> signUpWithEmail({
    required String? email,
    required String? password,
    required String? fullName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [],
          {
            #email: email,
            #password: password,
            #fullName: fullName,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> sendPasswordResetEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resendVerificationEmail() => (super.noSuchMethod(
        Invocation.method(
          #resendVerificationEmail,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> syncEmailVerificationStatus() => (super.noSuchMethod(
        Invocation.method(
          #syncEmailVerificationStatus,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getUserType() => (super.noSuchMethod(
        Invocation.method(
          #getUserType,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> isOnboardingCompleted() => (super.noSuchMethod(
        Invocation.method(
          #isOnboardingCompleted,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> storeAuthData(_i7.AuthDataStorageParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeAuthData,
          [params],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearSecureStorage() => (super.noSuchMethod(
        Invocation.method(
          #clearSecureStorage,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthStateProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStateProvider extends _i1.Mock implements _i8.AuthStateProvider {
  MockAuthStateProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentUserName => (super.noSuchMethod(
        Invocation.getter(#currentUserName),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#currentUserName),
        ),
      ) as String);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i2.AuthState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _FakeAuthState_0(
          this,
          Invocation.getter(#currentState),
        ),
      ) as _i2.AuthState);

  @override
  bool get isSignedInUser => (super.noSuchMethod(
        Invocation.getter(#isSignedInUser),
        returnValue: false,
      ) as bool);

  @override
  String get profileBasedDisplayName => (super.noSuchMethod(
        Invocation.getter(#profileBasedDisplayName),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#profileBasedDisplayName),
        ),
      ) as String);

  @override
  String get profileBasedDisplayNameOrEmpty => (super.noSuchMethod(
        Invocation.getter(#profileBasedDisplayNameOrEmpty),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#profileBasedDisplayNameOrEmpty),
        ),
      ) as String);

  @override
  String get debugInfo => (super.noSuchMethod(
        Invocation.getter(#debugInfo),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#debugInfo),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void initialize(_i10.AuthBloc? authBloc) => super.noSuchMethod(
        Invocation.method(
          #initialize,
          [authBloc],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cacheProfile(
    String? userId,
    Map<String, dynamic>? profile,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #cacheProfile,
          [
            userId,
            profile,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool shouldFetchProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #shouldFetchProfile,
          [userId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void invalidateProfileCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateProfileCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i12.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>
      getUserProfile() => (super.noSuchMethod(
            Invocation.method(
              #getUserProfile,
              [],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
              this,
              Invocation.method(
                #getUserProfile,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>
      updateLanguagePreference(_i15.AppLanguage? language) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateLanguagePreference,
              [language],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
              this,
              Invocation.method(
                #updateLanguagePreference,
                [language],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>
      updateStudyContentLanguage(_i15.AppLanguage? language) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateStudyContentLanguage,
              [language],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
              this,
              Invocation.method(
                #updateStudyContentLanguage,
                [language],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>
      updateThemePreference(String? themePreference) => (super.noSuchMethod(
            Invocation.method(
              #updateThemePreference,
              [themePreference],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
              this,
              Invocation.method(
                #updateThemePreference,
                [themePreference],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>> updateProfile(
          Map<String, dynamic>? updates) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [updates],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
          this,
          Invocation.method(
            #updateProfile,
            [updates],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i15.AppLanguage?>>
      getLanguagePreference() => (super.noSuchMethod(
            Invocation.method(
              #getLanguagePreference,
              [],
            ),
            returnValue:
                _i5.Future<_i3.Either<_i13.Failure, _i15.AppLanguage?>>.value(
                    _FakeEither_1<_i13.Failure, _i15.AppLanguage?>(
              this,
              Invocation.method(
                #getLanguagePreference,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i13.Failure, _i15.AppLanguage?>>);

  @override
  _i5.Future<bool> profileExists() => (super.noSuchMethod(
        Invocation.method(
          #profileExists,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<
      _i3.Either<_i13.Failure, _i14.UserProfileEntity>> initializeProfile({
    required _i15.AppLanguage? language,
    String? themePreference = 'light',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeProfile,
          [],
          {
            #language: language,
            #themePreference: themePreference,
          },
        ),
        returnValue:
            _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
          this,
          Invocation.method(
            #initializeProfile,
            [],
            {
              #language: language,
              #themePreference: themePreference,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>
      getUserProfileById(String? userId) => (super.noSuchMethod(
            Invocation.method(
              #getUserProfileById,
              [userId],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
              this,
              Invocation.method(
                #getUserProfileById,
                [userId],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);

  @override
  _i5.Future<
      _i3.Either<_i13.Failure, _i14.UserProfileEntity>> upsertUserProfile({
    required String? userId,
    required String? languagePreference,
    String? themePreference,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertUserProfile,
          [],
          {
            #userId: userId,
            #languagePreference: languagePreference,
            #themePreference: themePreference,
          },
        ),
        returnValue:
            _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
          this,
          Invocation.method(
            #upsertUserProfile,
            [],
            {
              #userId: userId,
              #languagePreference: languagePreference,
              #themePreference: themePreference,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);

  @override
  _i5.Future<bool> isCurrentUserAdmin(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #isCurrentUserAdmin,
          [userId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>?> getUserProfileAsMap(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfileAsMap,
          [userId],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, dynamic>?> getCurrentUserProfileAsMap() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserProfileAsMap,
          [],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>> syncOAuthProfile(
          Map<String, dynamic>? profileData) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncOAuthProfile,
          [profileData],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
          this,
          Invocation.method(
            #syncOAuthProfile,
            [profileData],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>
      updateStudyModePreference(String? modeValue) => (super.noSuchMethod(
            Invocation.method(
              #updateStudyModePreference,
              [modeValue],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
              this,
              Invocation.method(
                #updateStudyModePreference,
                [modeValue],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i16.StudyMode?>>
      getStudyModePreference() => (super.noSuchMethod(
            Invocation.method(
              #getStudyModePreference,
              [],
            ),
            returnValue:
                _i5.Future<_i3.Either<_i13.Failure, _i16.StudyMode?>>.value(
                    _FakeEither_1<_i13.Failure, _i16.StudyMode?>(
              this,
              Invocation.method(
                #getStudyModePreference,
                [],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i13.Failure, _i16.StudyMode?>>);

  @override
  _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>
      updateLearningPathStudyModePreference(String? modeValue) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateLearningPathStudyModePreference,
              [modeValue],
            ),
            returnValue: _i5
                .Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>.value(
                _FakeEither_1<_i13.Failure, _i14.UserProfileEntity>(
              this,
              Invocation.method(
                #updateLearningPathStudyModePreference,
                [modeValue],
              ),
            )),
          ) as _i5.Future<_i3.Either<_i13.Failure, _i14.UserProfileEntity>>);
}

/// A class which mocks [LanguageCacheCoordinator].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageCacheCoordinator extends _i1.Mock
    implements _i17.LanguageCacheCoordinator {
  MockLanguageCacheCoordinator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void registerCacheInvalidationCallback(_i17.VoidCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCacheInvalidationCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterCacheInvalidationCallback(_i17.VoidCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterCacheInvalidationCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateLanguageCaches() => super.noSuchMethod(
        Invocation.method(
          #invalidateLanguageCaches,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCallbacks() => super.noSuchMethod(
        Invocation.method(
          #clearCallbacks,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
