// Mocks generated by Mockito 5.4.6 from annotations
// in disciplefy_bible_study/test/core/utils/reset_progress_error_localizer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:disciplefy_bible_study/core/i18n/translation_service.dart'
    as _i2;
import 'package:disciplefy_bible_study/core/models/app_language.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TranslationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranslationService extends _i1.Mock
    implements _i2.TranslationService {
  MockTranslationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.AppLanguage> get languageChanges => (super.noSuchMethod(
        Invocation.getter(#languageChanges),
        returnValue: _i3.Stream<_i4.AppLanguage>.empty(),
      ) as _i3.Stream<_i4.AppLanguage>);

  @override
  _i4.AppLanguage get currentLanguage => (super.noSuchMethod(
        Invocation.getter(#currentLanguage),
        returnValue: _i4.AppLanguage.english,
      ) as _i4.AppLanguage);

  @override
  String getTranslation(
    String? key, [
    Map<String, dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslation,
          [
            key,
            args,
          ],
        ),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslation,
            [
              key,
              args,
            ],
          ),
        ),
      ) as String);

  @override
  List<String> getTranslationList(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getTranslationList,
          [key],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
