// Mocks generated by Mockito 5.4.6 from annotations
// in disciplefy_bible_study/test/features/home/home_redesign_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:disciplefy_bible_study/core/error/failures.dart' as _i8;
import 'package:disciplefy_bible_study/core/i18n/translation_service.dart'
    as _i3;
import 'package:disciplefy_bible_study/core/models/app_language.dart' as _i5;
import 'package:disciplefy_bible_study/core/services/language_preference_service.dart'
    as _i17;
import 'package:disciplefy_bible_study/features/community/domain/entities/blocked_user_entity.dart'
    as _i14;
import 'package:disciplefy_bible_study/features/community/domain/entities/daily_post_status_entity.dart'
    as _i13;
import 'package:disciplefy_bible_study/features/community/domain/entities/fellowship_comment_entity.dart'
    as _i12;
import 'package:disciplefy_bible_study/features/community/domain/entities/fellowship_entity.dart'
    as _i9;
import 'package:disciplefy_bible_study/features/community/domain/entities/fellowship_meeting_entity.dart'
    as _i15;
import 'package:disciplefy_bible_study/features/community/domain/entities/fellowship_member_entity.dart'
    as _i10;
import 'package:disciplefy_bible_study/features/community/domain/entities/fellowship_post_entity.dart'
    as _i11;
import 'package:disciplefy_bible_study/features/community/domain/entities/sync_calendar_result.dart'
    as _i16;
import 'package:disciplefy_bible_study/features/community/domain/repositories/community_repository.dart'
    as _i7;
import 'package:disciplefy_bible_study/features/study_generation/domain/entities/study_mode.dart'
    as _i18;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TranslationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranslationService extends _i1.Mock
    implements _i3.TranslationService {
  MockTranslationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.AppLanguage> get languageChanges => (super.noSuchMethod(
        Invocation.getter(#languageChanges),
        returnValue: _i4.Stream<_i5.AppLanguage>.empty(),
      ) as _i4.Stream<_i5.AppLanguage>);

  @override
  _i5.AppLanguage get currentLanguage => (super.noSuchMethod(
        Invocation.getter(#currentLanguage),
        returnValue: _i5.AppLanguage.english,
      ) as _i5.AppLanguage);

  @override
  String getTranslation(
    String? key, [
    Map<String, dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranslation,
          [
            key,
            args,
          ],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTranslation,
            [
              key,
              args,
            ],
          ),
        ),
      ) as String);

  @override
  List<String> getTranslationList(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getTranslationList,
          [key],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CommunityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityRepository extends _i1.Mock
    implements _i7.CommunityRepository {
  MockCommunityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i8.Failure, List<_i9.FellowshipEntity>>>
      getFellowships(String? language) => (super.noSuchMethod(
            Invocation.method(
              #getFellowships,
              [language],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i8.Failure, List<_i9.FellowshipEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i9.FellowshipEntity>>(
              this,
              Invocation.method(
                #getFellowships,
                [language],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i8.Failure, List<_i9.FellowshipEntity>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, List<_i10.FellowshipMemberEntity>>>
      getFellowshipMembers(String? fellowshipId) => (super.noSuchMethod(
            Invocation.method(
              #getFellowshipMembers,
              [fellowshipId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i8.Failure,
                        List<_i10.FellowshipMemberEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i10.FellowshipMemberEntity>>(
              this,
              Invocation.method(
                #getFellowshipMembers,
                [fellowshipId],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i8.Failure, List<_i10.FellowshipMemberEntity>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, List<_i11.FellowshipPostEntity>>>
      getFellowshipPosts({
    required String? fellowshipId,
    String? cursor,
    int? limit = 20,
    String? topicId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getFellowshipPosts,
              [],
              {
                #fellowshipId: fellowshipId,
                #cursor: cursor,
                #limit: limit,
                #topicId: topicId,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i8.Failure,
                        List<_i11.FellowshipPostEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i11.FellowshipPostEntity>>(
              this,
              Invocation.method(
                #getFellowshipPosts,
                [],
                {
                  #fellowshipId: fellowshipId,
                  #cursor: cursor,
                  #limit: limit,
                  #topicId: topicId,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i8.Failure, List<_i11.FellowshipPostEntity>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, _i11.FellowshipPostEntity>> createPost({
    required String? fellowshipId,
    required String? content,
    required String? postType,
    String? topicId,
    String? topicTitle,
    String? guideTitle,
    int? lessonIndex,
    String? studyGuideId,
    String? guideInputType,
    String? guideLanguage,
    String? guideStudyMode,
    String? guideSummary,
    bool? disciplerReplyOptOut = false,
    List<String>? mentionedUserIds = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [],
          {
            #fellowshipId: fellowshipId,
            #content: content,
            #postType: postType,
            #topicId: topicId,
            #topicTitle: topicTitle,
            #guideTitle: guideTitle,
            #lessonIndex: lessonIndex,
            #studyGuideId: studyGuideId,
            #guideInputType: guideInputType,
            #guideLanguage: guideLanguage,
            #guideStudyMode: guideStudyMode,
            #guideSummary: guideSummary,
            #disciplerReplyOptOut: disciplerReplyOptOut,
            #mentionedUserIds: mentionedUserIds,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i8.Failure, _i11.FellowshipPostEntity>>.value(
            _FakeEither_0<_i8.Failure, _i11.FellowshipPostEntity>(
          this,
          Invocation.method(
            #createPost,
            [],
            {
              #fellowshipId: fellowshipId,
              #content: content,
              #postType: postType,
              #topicId: topicId,
              #topicTitle: topicTitle,
              #guideTitle: guideTitle,
              #lessonIndex: lessonIndex,
              #studyGuideId: studyGuideId,
              #guideInputType: guideInputType,
              #guideLanguage: guideLanguage,
              #guideStudyMode: guideStudyMode,
              #guideSummary: guideSummary,
              #disciplerReplyOptOut: disciplerReplyOptOut,
              #mentionedUserIds: mentionedUserIds,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, _i11.FellowshipPostEntity>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> deletePost(String? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [postId],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #deletePost,
            [postId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<
      _i2.Either<_i8.Failure, List<_i12.FellowshipCommentEntity>>> getComments(
          String? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [postId],
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i8.Failure, List<_i12.FellowshipCommentEntity>>>.value(
            _FakeEither_0<_i8.Failure, List<_i12.FellowshipCommentEntity>>(
          this,
          Invocation.method(
            #getComments,
            [postId],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i8.Failure, List<_i12.FellowshipCommentEntity>>>);

  @override
  _i4.Future<
      _i2.Either<_i8.Failure, _i12.FellowshipCommentEntity>> createComment({
    required String? postId,
    required String? content,
    List<String>? mentionedUserIds = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComment,
          [],
          {
            #postId: postId,
            #content: content,
            #mentionedUserIds: mentionedUserIds,
          },
        ),
        returnValue: _i4.Future<
                _i2.Either<_i8.Failure, _i12.FellowshipCommentEntity>>.value(
            _FakeEither_0<_i8.Failure, _i12.FellowshipCommentEntity>(
          this,
          Invocation.method(
            #createComment,
            [],
            {
              #postId: postId,
              #content: content,
              #mentionedUserIds: mentionedUserIds,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, _i12.FellowshipCommentEntity>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> deleteComment(String? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteComment,
          [commentId],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #deleteComment,
            [commentId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> editPost(
    String? postId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editPost,
          [
            postId,
            content,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #editPost,
            [
              postId,
              content,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> editComment(
    String? commentId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editComment,
          [
            commentId,
            content,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #editComment,
            [
              commentId,
              content,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, Map<String, int>>> toggleReaction({
    required String? postId,
    required String? reactionType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleReaction,
          [],
          {
            #postId: postId,
            #reactionType: reactionType,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i8.Failure, Map<String, int>>>.value(
                _FakeEither_0<_i8.Failure, Map<String, int>>(
          this,
          Invocation.method(
            #toggleReaction,
            [],
            {
              #postId: postId,
              #reactionType: reactionType,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, Map<String, int>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, String>> joinFellowship(
          String? inviteToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinFellowship,
          [inviteToken],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, String>>.value(
            _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #joinFellowship,
            [inviteToken],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> createFellowship({
    required String? name,
    String? description,
    int? maxMembers,
    bool? isPublic = false,
    String? language = 'en',
    String? postingPermission = 'all_members',
    bool? unlimitedMembers = false,
    bool? isOfficial = false,
    bool? disciplerAllowed = false,
    bool? dailyPostAllowed = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFellowship,
          [],
          {
            #name: name,
            #description: description,
            #maxMembers: maxMembers,
            #isPublic: isPublic,
            #language: language,
            #postingPermission: postingPermission,
            #unlimitedMembers: unlimitedMembers,
            #isOfficial: isOfficial,
            #disciplerAllowed: disciplerAllowed,
            #dailyPostAllowed: dailyPostAllowed,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #createFellowship,
            [],
            {
              #name: name,
              #description: description,
              #maxMembers: maxMembers,
              #isPublic: isPublic,
              #language: language,
              #postingPermission: postingPermission,
              #unlimitedMembers: unlimitedMembers,
              #isOfficial: isOfficial,
              #disciplerAllowed: disciplerAllowed,
              #dailyPostAllowed: dailyPostAllowed,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, String>> setFellowshipStudy({
    required String? fellowshipId,
    required String? learningPathId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFellowshipStudy,
          [],
          {
            #fellowshipId: fellowshipId,
            #learningPathId: learningPathId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, String>>.value(
            _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #setFellowshipStudy,
            [],
            {
              #fellowshipId: fellowshipId,
              #learningPathId: learningPathId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, Map<String, dynamic>>> advanceStudy(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #advanceStudy,
          [fellowshipId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i8.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i8.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #advanceStudy,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> resetStudy(String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetStudy,
          [fellowshipId],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #resetStudy,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, _i13.DailyPostStatusEntity>>
      getDailyPostStatus(String? fellowshipId) => (super.noSuchMethod(
            Invocation.method(
              #getDailyPostStatus,
              [fellowshipId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i8.Failure, _i13.DailyPostStatusEntity>>.value(
                _FakeEither_0<_i8.Failure, _i13.DailyPostStatusEntity>(
              this,
              Invocation.method(
                #getDailyPostStatus,
                [fellowshipId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i8.Failure, _i13.DailyPostStatusEntity>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> updateDailyPost(
    String? fellowshipId, {
    bool? skipNext,
    String? pausedUntil,
    bool? clearPause = false,
    String? time,
    String? nextLearningPathTopicId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDailyPost,
          [fellowshipId],
          {
            #skipNext: skipNext,
            #pausedUntil: pausedUntil,
            #clearPause: clearPause,
            #time: time,
            #nextLearningPathTopicId: nextLearningPathTopicId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #updateDailyPost,
            [fellowshipId],
            {
              #skipNext: skipNext,
              #pausedUntil: pausedUntil,
              #clearPause: clearPause,
              #time: time,
              #nextLearningPathTopicId: nextLearningPathTopicId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> requestDailyPostAction(
    String? fellowshipId,
    String? kind, {
    String? dailyPostId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestDailyPostAction,
          [
            fellowshipId,
            kind,
          ],
          {#dailyPostId: dailyPostId},
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #requestDailyPostAction,
            [
              fellowshipId,
              kind,
            ],
            {#dailyPostId: dailyPostId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> leaveFellowship(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveFellowship,
          [fellowshipId],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #leaveFellowship,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> deleteFellowship(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFellowship,
          [fellowshipId],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #deleteFellowship,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> muteMember({
    required String? fellowshipId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteMember,
          [],
          {
            #fellowshipId: fellowshipId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #muteMember,
            [],
            {
              #fellowshipId: fellowshipId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> unmuteMember({
    required String? fellowshipId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unmuteMember,
          [],
          {
            #fellowshipId: fellowshipId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #unmuteMember,
            [],
            {
              #fellowshipId: fellowshipId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> removeMember({
    required String? fellowshipId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [],
          {
            #fellowshipId: fellowshipId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #removeMember,
            [],
            {
              #fellowshipId: fellowshipId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, Map<String, dynamic>>> createInvite(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInvite,
          [fellowshipId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i8.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i8.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #createInvite,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, Map<String, dynamic>>> getFellowship(
    String? fellowshipId,
    String? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFellowship,
          [
            fellowshipId,
            language,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i8.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i8.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #getFellowship,
            [
              fellowshipId,
              language,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> updateFellowship({
    required String? fellowshipId,
    String? name,
    String? description,
    int? maxMembers,
    String? postingPermission,
    bool? isOfficial,
    bool? disciplerAllowed,
    bool? dailyPostAllowed,
    String? disciplerReplyMode,
    String? disciplerReplyScope,
    int? disciplerReplyDelayMin,
    bool? disciplerReactEnabled,
    bool? dailyPostOn,
    int? dailyPostFrequencyDays,
    bool? dailyPostAutoAdvance,
    bool? dailyPostAutoAdvancePath,
    bool? disciplerActivityPush,
    bool? notificationsMuted,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFellowship,
          [],
          {
            #fellowshipId: fellowshipId,
            #name: name,
            #description: description,
            #maxMembers: maxMembers,
            #postingPermission: postingPermission,
            #isOfficial: isOfficial,
            #disciplerAllowed: disciplerAllowed,
            #dailyPostAllowed: dailyPostAllowed,
            #disciplerReplyMode: disciplerReplyMode,
            #disciplerReplyScope: disciplerReplyScope,
            #disciplerReplyDelayMin: disciplerReplyDelayMin,
            #disciplerReactEnabled: disciplerReactEnabled,
            #dailyPostOn: dailyPostOn,
            #dailyPostFrequencyDays: dailyPostFrequencyDays,
            #dailyPostAutoAdvance: dailyPostAutoAdvance,
            #dailyPostAutoAdvancePath: dailyPostAutoAdvancePath,
            #disciplerActivityPush: disciplerActivityPush,
            #notificationsMuted: notificationsMuted,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #updateFellowship,
            [],
            {
              #fellowshipId: fellowshipId,
              #name: name,
              #description: description,
              #maxMembers: maxMembers,
              #postingPermission: postingPermission,
              #isOfficial: isOfficial,
              #disciplerAllowed: disciplerAllowed,
              #dailyPostAllowed: dailyPostAllowed,
              #disciplerReplyMode: disciplerReplyMode,
              #disciplerReplyScope: disciplerReplyScope,
              #disciplerReplyDelayMin: disciplerReplyDelayMin,
              #disciplerReactEnabled: disciplerReactEnabled,
              #dailyPostOn: dailyPostOn,
              #dailyPostFrequencyDays: dailyPostFrequencyDays,
              #dailyPostAutoAdvance: dailyPostAutoAdvance,
              #dailyPostAutoAdvancePath: dailyPostAutoAdvancePath,
              #disciplerActivityPush: disciplerActivityPush,
              #notificationsMuted: notificationsMuted,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> promoteMember({
    required String? fellowshipId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #promoteMember,
          [],
          {
            #fellowshipId: fellowshipId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #promoteMember,
            [],
            {
              #fellowshipId: fellowshipId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> demoteMember({
    required String? fellowshipId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #demoteMember,
          [],
          {
            #fellowshipId: fellowshipId,
            #userId: userId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #demoteMember,
            [],
            {
              #fellowshipId: fellowshipId,
              #userId: userId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, ({String? email, String? whatsapp})>>
      updateMentorContact({
    required String? fellowshipId,
    String? whatsapp,
    String? email,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateMentorContact,
              [],
              {
                #fellowshipId: fellowshipId,
                #whatsapp: whatsapp,
                #email: email,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i8.Failure,
                        ({String? email, String? whatsapp})>>.value(
                _FakeEither_0<_i8.Failure, ({String? email, String? whatsapp})>(
              this,
              Invocation.method(
                #updateMentorContact,
                [],
                {
                  #fellowshipId: fellowshipId,
                  #whatsapp: whatsapp,
                  #email: email,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i8.Failure, ({String? email, String? whatsapp})>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> approveDisciplerComment(
          String? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveDisciplerComment,
          [commentId],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #approveDisciplerComment,
            [commentId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> discardDisciplerComment(
          String? commentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #discardDisciplerComment,
          [commentId],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #discardDisciplerComment,
            [commentId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, _i7.DisciplerActivityPage>>
      getDisciplerActivity({
    required String? fellowshipId,
    String? kind,
    String? cursor,
    int? limit = 30,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getDisciplerActivity,
              [],
              {
                #fellowshipId: fellowshipId,
                #kind: kind,
                #cursor: cursor,
                #limit: limit,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i8.Failure, _i7.DisciplerActivityPage>>.value(
                _FakeEither_0<_i8.Failure, _i7.DisciplerActivityPage>(
              this,
              Invocation.method(
                #getDisciplerActivity,
                [],
                {
                  #fellowshipId: fellowshipId,
                  #kind: kind,
                  #cursor: cursor,
                  #limit: limit,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i8.Failure, _i7.DisciplerActivityPage>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, List<Map<String, dynamic>>>> listInvites(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listInvites,
          [fellowshipId],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i8.Failure, List<Map<String, dynamic>>>>.value(
            _FakeEither_0<_i8.Failure, List<Map<String, dynamic>>>(
          this,
          Invocation.method(
            #listInvites,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> revokeInvite({
    required String? fellowshipId,
    required String? inviteId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeInvite,
          [],
          {
            #fellowshipId: fellowshipId,
            #inviteId: inviteId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #revokeInvite,
            [],
            {
              #fellowshipId: fellowshipId,
              #inviteId: inviteId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> transferMentor({
    required String? fellowshipId,
    required String? newMentorUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferMentor,
          [],
          {
            #fellowshipId: fellowshipId,
            #newMentorUserId: newMentorUserId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #transferMentor,
            [],
            {
              #fellowshipId: fellowshipId,
              #newMentorUserId: newMentorUserId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> reportContent({
    required String? fellowshipId,
    required String? contentType,
    required String? contentId,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportContent,
          [],
          {
            #fellowshipId: fellowshipId,
            #contentType: contentType,
            #contentId: contentId,
            #reason: reason,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #reportContent,
            [],
            {
              #fellowshipId: fellowshipId,
              #contentType: contentType,
              #contentId: contentId,
              #reason: reason,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> blockUser({
    required String? blockedUserId,
    String? fellowshipId,
    String? contentType,
    String? contentId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #blockUser,
          [],
          {
            #blockedUserId: blockedUserId,
            #fellowshipId: fellowshipId,
            #contentType: contentType,
            #contentId: contentId,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #blockUser,
            [],
            {
              #blockedUserId: blockedUserId,
              #fellowshipId: fellowshipId,
              #contentType: contentType,
              #contentId: contentId,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> unblockUser(
          String? blockedUserId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unblockUser,
          [blockedUserId],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #unblockUser,
            [blockedUserId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, List<_i14.BlockedUserEntity>>>
      getBlockedUsers() => (super.noSuchMethod(
            Invocation.method(
              #getBlockedUsers,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i8.Failure, List<_i14.BlockedUserEntity>>>.value(
                _FakeEither_0<_i8.Failure, List<_i14.BlockedUserEntity>>(
              this,
              Invocation.method(
                #getBlockedUsers,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i8.Failure, List<_i14.BlockedUserEntity>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, Map<String, int>>> getTopicPostCounts(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopicPostCounts,
          [fellowshipId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i8.Failure, Map<String, int>>>.value(
                _FakeEither_0<_i8.Failure, Map<String, int>>(
          this,
          Invocation.method(
            #getTopicPostCounts,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, Map<String, int>>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, _i7.DiscoverPage>> discoverFellowships({
    String? language,
    String? search,
    String? cursor,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverFellowships,
          [],
          {
            #language: language,
            #search: search,
            #cursor: cursor,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i8.Failure, _i7.DiscoverPage>>.value(
                _FakeEither_0<_i8.Failure, _i7.DiscoverPage>(
          this,
          Invocation.method(
            #discoverFellowships,
            [],
            {
              #language: language,
              #search: search,
              #cursor: cursor,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, _i7.DiscoverPage>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, String>> joinPublicFellowship(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinPublicFellowship,
          [fellowshipId],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, String>>.value(
            _FakeEither_0<_i8.Failure, String>(
          this,
          Invocation.method(
            #joinPublicFellowship,
            [fellowshipId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i4.Future<
      _i2.Either<_i8.Failure, List<_i15.FellowshipMeetingEntity>>> getMeetings(
          String? fellowshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMeetings,
          [fellowshipId],
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i8.Failure, List<_i15.FellowshipMeetingEntity>>>.value(
            _FakeEither_0<_i8.Failure, List<_i15.FellowshipMeetingEntity>>(
          this,
          Invocation.method(
            #getMeetings,
            [fellowshipId],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i8.Failure, List<_i15.FellowshipMeetingEntity>>>);

  @override
  _i4.Future<
      _i2.Either<_i8.Failure, _i15.FellowshipMeetingEntity>> createMeeting({
    required String? fellowshipId,
    required String? title,
    String? description,
    required String? startsAt,
    required int? durationMinutes,
    required String? timeZone,
    String? recurrence,
    String? location,
    String? googleAccessToken,
    String? googleRefreshToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMeeting,
          [],
          {
            #fellowshipId: fellowshipId,
            #title: title,
            #description: description,
            #startsAt: startsAt,
            #durationMinutes: durationMinutes,
            #timeZone: timeZone,
            #recurrence: recurrence,
            #location: location,
            #googleAccessToken: googleAccessToken,
            #googleRefreshToken: googleRefreshToken,
          },
        ),
        returnValue: _i4.Future<
                _i2.Either<_i8.Failure, _i15.FellowshipMeetingEntity>>.value(
            _FakeEither_0<_i8.Failure, _i15.FellowshipMeetingEntity>(
          this,
          Invocation.method(
            #createMeeting,
            [],
            {
              #fellowshipId: fellowshipId,
              #title: title,
              #description: description,
              #startsAt: startsAt,
              #durationMinutes: durationMinutes,
              #timeZone: timeZone,
              #recurrence: recurrence,
              #location: location,
              #googleAccessToken: googleAccessToken,
              #googleRefreshToken: googleRefreshToken,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, _i15.FellowshipMeetingEntity>>);

  @override
  _i4.Future<_i2.Either<_i8.Failure, void>> cancelMeeting(
    String? meetingId, {
    String? googleAccessToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelMeeting,
          [meetingId],
          {#googleAccessToken: googleAccessToken},
        ),
        returnValue: _i4.Future<_i2.Either<_i8.Failure, void>>.value(
            _FakeEither_0<_i8.Failure, void>(
          this,
          Invocation.method(
            #cancelMeeting,
            [meetingId],
            {#googleAccessToken: googleAccessToken},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, void>>);

  @override
  _i4.Future<
      _i2.Either<_i8.Failure, _i16.SyncCalendarResult>> syncFellowshipCalendar(
    String? fellowshipId, {
    String? googleAccessToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncFellowshipCalendar,
          [fellowshipId],
          {#googleAccessToken: googleAccessToken},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i8.Failure, _i16.SyncCalendarResult>>.value(
                _FakeEither_0<_i8.Failure, _i16.SyncCalendarResult>(
          this,
          Invocation.method(
            #syncFellowshipCalendar,
            [fellowshipId],
            {#googleAccessToken: googleAccessToken},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.Failure, _i16.SyncCalendarResult>>);
}

/// A class which mocks [LanguagePreferenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguagePreferenceService extends _i1.Mock
    implements _i17.LanguagePreferenceService {
  MockLanguagePreferenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.AppLanguage> get languageChanges => (super.noSuchMethod(
        Invocation.getter(#languageChanges),
        returnValue: _i4.Stream<_i5.AppLanguage>.empty(),
      ) as _i4.Stream<_i5.AppLanguage>);

  @override
  _i4.Stream<_i5.AppLanguage> get studyContentLanguageChanges =>
      (super.noSuchMethod(
        Invocation.getter(#studyContentLanguageChanges),
        returnValue: _i4.Stream<_i5.AppLanguage>.empty(),
      ) as _i4.Stream<_i5.AppLanguage>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<_i5.AppLanguage> getSelectedLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getSelectedLanguage,
          [],
        ),
        returnValue: _i4.Future<_i5.AppLanguage>.value(_i5.AppLanguage.english),
      ) as _i4.Future<_i5.AppLanguage>);

  @override
  _i4.Future<void> saveLanguagePreference(_i5.AppLanguage? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLanguagePreference,
          [language],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> hasCompletedLanguageSelection() => (super.noSuchMethod(
        Invocation.method(
          #hasCompletedLanguageSelection,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> markLanguageSelectionCompleted() => (super.noSuchMethod(
        Invocation.method(
          #markLanguageSelectionCompleted,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> syncWithProfile() => (super.noSuchMethod(
        Invocation.method(
          #syncWithProfile,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetLanguageSelectionStatus() => (super.noSuchMethod(
        Invocation.method(
          #resetLanguageSelectionStatus,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void invalidateLanguageCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateLanguageCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> saveStudyModePreference(_i18.StudyMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStudyModePreference,
          [mode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveStudyModePreferenceRaw(String? modeValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStudyModePreferenceRaw,
          [modeValue],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearStudyModePreference() => (super.noSuchMethod(
        Invocation.method(
          #clearStudyModePreference,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getStudyModePreferenceRaw() => (super.noSuchMethod(
        Invocation.method(
          #getStudyModePreferenceRaw,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> cacheLearningPathStudyModePreference(String? modeValue) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheLearningPathStudyModePreference,
          [modeValue],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i18.StudyMode?> getStudyModePreference() => (super.noSuchMethod(
        Invocation.method(
          #getStudyModePreference,
          [],
        ),
        returnValue: _i4.Future<_i18.StudyMode?>.value(),
      ) as _i4.Future<_i18.StudyMode?>);

  @override
  _i4.Future<_i5.AppLanguage> getStudyContentLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getStudyContentLanguage,
          [],
        ),
        returnValue: _i4.Future<_i5.AppLanguage>.value(_i5.AppLanguage.english),
      ) as _i4.Future<_i5.AppLanguage>);

  @override
  _i4.Future<void> saveStudyContentLanguage(_i5.AppLanguage? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStudyContentLanguage,
          [language],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setStudyContentLanguageToDefault(
          {_i5.AppLanguage? appLanguage}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStudyContentLanguageToDefault,
          [],
          {#appLanguage: appLanguage},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isStudyContentLanguageDefault() => (super.noSuchMethod(
        Invocation.method(
          #isStudyContentLanguageDefault,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> clearStudyContentLanguage() => (super.noSuchMethod(
        Invocation.method(
          #clearStudyContentLanguage,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
