// Mocks generated by Mockito 5.4.6 from annotations
// in disciplefy_bible_study/test/features/memory_verses/domain/usecases/reset_memory_progress_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:disciplefy_bible_study/core/error/failures.dart' as _i5;
import 'package:disciplefy_bible_study/core/models/reset_progress_result.dart'
    as _i8;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/daily_goal_entity.dart'
    as _i15;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/fetched_verse_entity.dart'
    as _i10;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/mastery_progress_entity.dart'
    as _i14;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/memory_challenge_entity.dart'
    as _i16;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/memory_champion_entry.dart'
    as _i17;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/memory_streak_entity.dart'
    as _i13;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/memory_verse_entity.dart'
    as _i6;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/practice_mode_entity.dart'
    as _i11;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/review_session_entity.dart'
    as _i9;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/review_statistics_entity.dart'
    as _i7;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/suggested_verse_entity.dart'
    as _i18;
import 'package:disciplefy_bible_study/features/memory_verses/domain/repositories/memory_verse_repository.dart'
    as _i3;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/submit_practice_session.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MemoryVerseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryVerseRepository extends _i1.Mock
    implements _i3.MemoryVerseRepository {
  MockMemoryVerseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> addVerseFromDaily({
    required String? dailyVerseId,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVerseFromDaily,
          [],
          {
            #dailyVerseId: dailyVerseId,
            #language: language,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #addVerseFromDaily,
            [],
            {
              #dailyVerseId: dailyVerseId,
              #language: language,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> addVerseManually({
    required String? verseReference,
    required String? verseText,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVerseManually,
          [],
          {
            #verseReference: verseReference,
            #verseText: verseText,
            #language: language,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #addVerseManually,
            [],
            {
              #verseReference: verseReference,
              #verseText: verseText,
              #language: language,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);

  @override
  _i4.Future<
          _i2.Either<_i5.Failure,
              (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>>
      getDueVerses({
    int? limit = 20,
    int? offset = 0,
    String? language,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getDueVerses,
              [],
              {
                #limit: limit,
                #offset: offset,
                #language: language,
              },
            ),
            returnValue: _i4.Future<
                _i2.Either<
                    _i5.Failure,
                    (
                      List<_i6.MemoryVerseEntity>,
                      _i7.ReviewStatisticsEntity
                    )>>.value(_FakeEither_0<_i5.Failure,
                (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>(
              this,
              Invocation.method(
                #getDueVerses,
                [],
                {
                  #limit: limit,
                  #offset: offset,
                  #language: language,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>>);

  @override
  _i4.Future<(List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)?>
      getCachedDueVerses({String? language}) => (super.noSuchMethod(
            Invocation.method(
              #getCachedDueVerses,
              [],
              {#language: language},
            ),
            returnValue: _i4.Future<
                (
                  List<_i6.MemoryVerseEntity>,
                  _i7.ReviewStatisticsEntity
                )?>.value(),
          ) as _i4.Future<
              (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)?>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> submitReview({
    required String? memoryVerseId,
    required int? qualityRating,
    int? timeSpentSeconds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitReview,
          [],
          {
            #memoryVerseId: memoryVerseId,
            #qualityRating: qualityRating,
            #timeSpentSeconds: timeSpentSeconds,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #submitReview,
            [],
            {
              #memoryVerseId: memoryVerseId,
              #qualityRating: qualityRating,
              #timeSpentSeconds: timeSpentSeconds,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>>
      getStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getStatistics,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>>.value(
                _FakeEither_0<_i5.Failure, _i7.ReviewStatisticsEntity>(
              this,
              Invocation.method(
                #getStatistics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> getVerseById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerseById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #getVerseById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemoryVerseEntity>>>
      getAllVerses() => (super.noSuchMethod(
            Invocation.method(
              #getAllVerses,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.MemoryVerseEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.MemoryVerseEntity>>(
              this,
              Invocation.method(
                #getAllVerses,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.MemoryVerseEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> deleteVerse(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVerse,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteVerse,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.ResetProgressResult>>
      resetMemoryProgress() => (super.noSuchMethod(
            Invocation.method(
              #resetMemoryProgress,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i8.ResetProgressResult>>.value(
                _FakeEither_0<_i5.Failure, _i8.ResetProgressResult>(
              this,
              Invocation.method(
                #resetMemoryProgress,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i8.ResetProgressResult>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i9.ReviewSessionEntity>>> getReviewHistory({
    required String? memoryVerseId,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviewHistory,
          [],
          {
            #memoryVerseId: memoryVerseId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, List<_i9.ReviewSessionEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i9.ReviewSessionEntity>>(
          this,
          Invocation.method(
            #getReviewHistory,
            [],
            {
              #memoryVerseId: memoryVerseId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.ReviewSessionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> syncWithRemote() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWithRemote,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #syncWithRemote,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> clearLocalCache() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearLocalCache,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #clearLocalCache,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>> fetchVerseText({
    required String? book,
    required int? chapter,
    required int? verseStart,
    int? verseEnd,
    required String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVerseText,
          [],
          {
            #book: book,
            #chapter: chapter,
            #verseStart: verseStart,
            #verseEnd: verseEnd,
            #language: language,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i10.FetchedVerseEntity>(
          this,
          Invocation.method(
            #fetchVerseText,
            [],
            {
              #book: book,
              #chapter: chapter,
              #verseStart: verseStart,
              #verseEnd: verseEnd,
              #language: language,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i11.PracticeModeEntity>> selectPracticeMode({
    required String? verseId,
    required _i11.PracticeModeType? practiceMode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectPracticeMode,
          [],
          {
            #verseId: verseId,
            #practiceMode: practiceMode,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i11.PracticeModeEntity>>.value(
                _FakeEither_0<_i5.Failure, _i11.PracticeModeEntity>(
          this,
          Invocation.method(
            #selectPracticeMode,
            [],
            {
              #verseId: verseId,
              #practiceMode: practiceMode,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i11.PracticeModeEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i12.SubmitPracticeSessionResponse>>
      submitPracticeSession(_i12.SubmitPracticeSessionParams? params) =>
          (super.noSuchMethod(
            Invocation.method(
              #submitPracticeSession,
              [params],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i12.SubmitPracticeSessionResponse>>.value(
                _FakeEither_0<_i5.Failure, _i12.SubmitPracticeSessionResponse>(
              this,
              Invocation.method(
                #submitPracticeSession,
                [params],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i12.SubmitPracticeSessionResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i11.PracticeModeEntity>>>
      getPracticeModeStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getPracticeModeStatistics,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i11.PracticeModeEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i11.PracticeModeEntity>>(
              this,
              Invocation.method(
                #getPracticeModeStatistics,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i11.PracticeModeEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>
      getMemoryStreak() => (super.noSuchMethod(
            Invocation.method(
              #getMemoryStreak,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>.value(
                _FakeEither_0<_i5.Failure, _i13.MemoryStreakEntity>(
              this,
              Invocation.method(
                #getMemoryStreak,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>> useStreakFreeze(
          {required DateTime? freezeDate}) =>
      (super.noSuchMethod(
        Invocation.method(
          #useStreakFreeze,
          [],
          {#freezeDate: freezeDate},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>.value(
                _FakeEither_0<_i5.Failure, _i13.MemoryStreakEntity>(
          this,
          Invocation.method(
            #useStreakFreeze,
            [],
            {#freezeDate: freezeDate},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, (bool, int?)>> checkStreakMilestone() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkStreakMilestone,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, (bool, int?)>>.value(
            _FakeEither_0<_i5.Failure, (bool, int?)>(
          this,
          Invocation.method(
            #checkStreakMilestone,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, (bool, int?)>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>
      getMasteryProgress({required String? verseId}) => (super.noSuchMethod(
            Invocation.method(
              #getMasteryProgress,
              [],
              {#verseId: verseId},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>.value(
                _FakeEither_0<_i5.Failure, _i14.MasteryProgressEntity>(
              this,
              Invocation.method(
                #getMasteryProgress,
                [],
                {#verseId: verseId},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>
      updateMasteryLevel({
    required String? verseId,
    required _i14.MasteryLevel? newMasteryLevel,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateMasteryLevel,
              [],
              {
                #verseId: verseId,
                #newMasteryLevel: newMasteryLevel,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>.value(
                _FakeEither_0<_i5.Failure, _i14.MasteryProgressEntity>(
              this,
              Invocation.method(
                #updateMasteryLevel,
                [],
                {
                  #verseId: verseId,
                  #newMasteryLevel: newMasteryLevel,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>> getDailyGoal() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyGoal,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
          this,
          Invocation.method(
            #getDailyGoal,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>
      updateDailyGoalProgress({required bool? isNewVerse}) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateDailyGoalProgress,
              [],
              {#isNewVerse: isNewVerse},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                    _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
              this,
              Invocation.method(
                #updateDailyGoalProgress,
                [],
                {#isNewVerse: isNewVerse},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>
      setDailyGoalTargets({
    required int? targetReviews,
    required int? targetNewVerses,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #setDailyGoalTargets,
              [],
              {
                #targetReviews: targetReviews,
                #targetNewVerses: targetNewVerses,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                    _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
              this,
              Invocation.method(
                #setDailyGoalTargets,
                [],
                {
                  #targetReviews: targetReviews,
                  #targetNewVerses: targetNewVerses,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i16.MemoryChallengeEntity>>>
      getActiveChallenges() => (super.noSuchMethod(
            Invocation.method(
              #getActiveChallenges,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i16.MemoryChallengeEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i16.MemoryChallengeEntity>>(
              this,
              Invocation.method(
                #getActiveChallenges,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i16.MemoryChallengeEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, (_i16.MemoryChallengeEntity, int)>>
      claimChallengeReward({required String? challengeId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #claimChallengeReward,
              [],
              {#challengeId: challengeId},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        (_i16.MemoryChallengeEntity, int)>>.value(
                _FakeEither_0<_i5.Failure, (_i16.MemoryChallengeEntity, int)>(
              this,
              Invocation.method(
                #claimChallengeReward,
                [],
                {#challengeId: challengeId},
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, (_i16.MemoryChallengeEntity, int)>>);

  @override
  _i4.Future<
          _i2.Either<_i5.Failure,
              (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>>
      getMemoryChampionsLeaderboard({
    required String? period,
    int? limit = 100,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getMemoryChampionsLeaderboard,
              [],
              {
                #period: period,
                #limit: limit,
              },
            ),
            returnValue: _i4.Future<
                _i2.Either<
                    _i5.Failure,
                    (
                      List<_i17.MemoryChampionEntry>,
                      _i17.UserMemoryStats
                    )>>.value(_FakeEither_0<_i5.Failure,
                (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>(
              this,
              Invocation.method(
                #getMemoryChampionsLeaderboard,
                [],
                {
                  #period: period,
                  #limit: limit,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getMemoryStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getMemoryStatistics,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getMemoryStatistics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i18.SuggestedVersesResponse>>
      getSuggestedVerses({
    _i18.SuggestedVerseCategory? category,
    String? language = 'en',
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getSuggestedVerses,
              [],
              {
                #category: category,
                #language: language,
              },
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, _i18.SuggestedVersesResponse>>.value(
                _FakeEither_0<_i5.Failure, _i18.SuggestedVersesResponse>(
              this,
              Invocation.method(
                #getSuggestedVerses,
                [],
                {
                  #category: category,
                  #language: language,
                },
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i18.SuggestedVersesResponse>>);
}
