-- Migration: Add interpretation_insights and context_question columns to study_guides table
-- Date: 2024-12-24
-- Purpose: Enable content-aware reflection questions in Reflect Mode

BEGIN;

-- Add new columns for dynamic reflection insights
ALTER TABLE public.study_guides
ADD COLUMN IF NOT EXISTS interpretation_insights TEXT[],
ADD COLUMN IF NOT EXISTS context_question TEXT;

-- Create partial indexes for performance (only index rows where field is populated)
CREATE INDEX IF NOT EXISTS idx_study_guides_has_insights
ON public.study_guides((interpretation_insights IS NOT NULL))
WHERE interpretation_insights IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_study_guides_has_context_question
ON public.study_guides((context_question IS NOT NULL))
WHERE context_question IS NOT NULL;

-- Add helpful column comments for documentation
COMMENT ON COLUMN public.study_guides.interpretation_insights IS
'Array of 3-4 theological insights extracted from interpretation for multi-select reflection (10-15 words each). Generated by LLM during study guide creation.';

COMMENT ON COLUMN public.study_guides.context_question IS
'Yes/no question generated from historical/cultural context to connect biblical situation to modern life. Used in Reflect Mode context card.';

COMMIT;
