-- =============================================================================
-- Suggested memory verses: BSB (en) / IRV Hindi (hi) / IRV Malayalam (ml) text
-- GENERATED by backend/scripts/generate-suggested-verse-text-migration.ts from
-- rs-backend/data/bible/{bsb,irv-hi,irv-ml}.tsv — do not edit by hand.
--
-- The seeded English text was NIV wording (not licensed). Replaces every
-- suggested verse text with the self-hosted public-domain / CC BY-SA text, and
-- moves memory_verses rows that were added from the suggestion list (saved as
-- source_type 'manual' with the suggested wording verbatim) to the new text.
-- Rows whose text the user typed or edited do not match and are left untouched.
-- Idempotent: re-running changes nothing.
-- =============================================================================

DROP TABLE IF EXISTS _suggested_text;
CREATE TEMP TABLE _suggested_text (reference TEXT, language_code TEXT, verse_text TEXT);

INSERT INTO _suggested_text (reference, language_code, verse_text) VALUES
  ('John 3:16', 'en', 'For God so loved the world that He gave His one and only Son, that everyone who believes in Him shall not perish but have eternal life.'),
  ('Romans 10:9', 'en', 'that if you confess with your mouth, “ Jesus is Lord,” and believe in your heart that God raised Him from the dead, you will be saved.'),
  ('Ephesians 2:8', 'en', 'For it is by grace you have been saved through faith, and this not from yourselves; it is the gift of God,'),
  ('Acts 4:12', 'en', 'Salvation exists in no one else, for there is no other name under heaven given to men by which we must be saved.'),
  ('Romans 6:23', 'en', 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.'),
  ('Matthew 11:28', 'en', 'Come to Me, all you who are weary and burdened, and I will give you rest.'),
  ('Psalm 23:4', 'en', 'Even though I walk through the valley of the shadow of death, I will fear no evil, for You are with me; Your rod and Your staff, they comfort me.'),
  ('Isaiah 41:10', 'en', 'Do not fear, for I am with you; do not be afraid, for I am your God. I will strengthen you; I will surely help you; I will uphold you with My right hand of righteousness.'),
  ('John 14:27', 'en', 'Peace I leave with you; My peace I give to you. I do not give to you as the world gives. Do not let your hearts be troubled; do not be afraid.'),
  ('2 Corinthians 1:3', 'en', 'Blessed be the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort,'),
  ('Philippians 4:13', 'en', 'I can do all things through Christ who gives me strength.'),
  ('Isaiah 40:31', 'en', 'But those who wait upon the LORD will renew their strength; they will mount up with wings like eagles; they will run and not grow weary, they will walk and not faint.'),
  ('Psalm 46:1', 'en', 'God is our refuge and strength, an ever-present help in times of trouble.'),
  ('2 Corinthians 12:9', 'en', 'But He said to me, “ My grace is sufficient for you, for My power is perfected in weakness.” Therefore I will boast all the more gladly in my weaknesses, so that the power of Christ may rest on me.'),
  ('Nehemiah 8:10', 'en', 'Then Nehemiah told them, “ Go and eat what is rich, drink what is sweet, and send out portions to those who have nothing prepared, since today is holy to our Lord. Do not grieve, for the joy of the LORD is your strength.”'),
  ('Proverbs 3:5', 'en', 'Trust in the LORD with all your heart, and lean not on your own understanding;'),
  ('James 1:5', 'en', 'Now if any of you lacks wisdom, he should ask God, who gives generously to all without finding fault, and it will be given to him.'),
  ('Proverbs 9:10', 'en', 'The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding.'),
  ('Psalm 119:105', 'en', 'Your word is a lamp to my feet and a light to my path.'),
  ('Colossians 2:3', 'en', 'in whom are hidden all the treasures of wisdom and knowledge.'),
  ('Jeremiah 29:11', 'en', 'For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, to give you a future and a hope.'),
  ('Romans 8:28', 'en', 'And we know that God works all things together for the good of those who love Him, who are called according to His purpose.'),
  ('Psalm 37:4', 'en', 'Delight yourself in the LORD, and He will give you the desires of your heart.'),
  ('Joshua 1:9', 'en', 'Have I not commanded you to be strong and courageous? Do not be afraid; do not be discouraged, for the LORD your God is with you wherever you go.'),
  ('Hebrews 13:5', 'en', 'Keep your lives free from the love of money and be content with what you have, for God has said: “ Never will I leave you, never will I forsake you.”'),
  ('Proverbs 3:6', 'en', 'in all your ways acknowledge Him, and He will make your paths straight.'),
  ('John 16:13', 'en', 'However, when the Spirit of truth comes, He will guide you into all truth. For He will not speak on His own, but He will speak what He hears, and He will declare to you what is to come.'),
  ('Psalm 32:8', 'en', 'I will instruct you and teach you the way you should go; I will give you counsel and watch over you.'),
  ('Isaiah 30:21', 'en', 'And whether you turn to the right or to the left, your ears will hear this command behind you: “ This is the way. Walk in it.”'),
  ('Psalm 25:4', 'en', 'Show me Your ways, O LORD; teach me Your paths.'),
  ('Hebrews 11:1', 'en', 'Now faith is the assurance of what we hope for and the certainty of what we do not see.'),
  ('Matthew 17:20', 'en', '“ Because you have so little faith,” He answered. “ For truly I tell you, if you have faith the size of a mustard seed, you can say to this mountain, ‘ Move from here to there,’ and it will move. Nothing will be impossible for you.”'),
  ('Romans 10:17', 'en', 'Consequently, faith comes by hearing, and hearing by the word of Christ.'),
  ('2 Corinthians 5:7', 'en', 'For we walk by faith, not by sight.'),
  ('1 John 5:14', 'en', 'And this is the confidence that we have before Him: If we ask anything according to His will, He hears us.'),
  ('1 Corinthians 13:4', 'en', 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.'),
  ('Romans 5:8', 'en', 'But God proves His love for us in this: While we were still sinners, Christ died for us.'),
  ('1 John 4:8', 'en', 'Whoever does not love does not know God, because God is love.'),
  ('1 John 4:19', 'en', 'We love because He first loved us.'),
  ('John 15:13', 'en', 'Greater love has no one than this, that he lay down his life for his friends.'),
  ('John 3:16', 'hi', 'क्योंकि परमेश्वर ने जगत से ऐसा प्रेम रखा कि उसने अपना एकलौता पुत्र दे दिया, ताकि जो कोई उस पर विश्वास करे, वह नाश न हो, परन्तु अनन्त जीवन पाए।'),
  ('Romans 10:9', 'hi', 'कि यदि तू अपने मुँह से यीशु को प्रभु जानकर अंगीकार करे और अपने मन से विश्वास करे, कि परमेश्वर ने उसे मरे हुओं में से जिलाया, तो तू निश्चय उद्धार पाएगा।'),
  ('Ephesians 2:8', 'hi', 'क्योंकि विश्वास के द्वारा अनुग्रह ही से तुम्हारा उद्धार हुआ है, और यह तुम्हारी ओर से नहीं, वरन् परमेश्वर का दान है;'),
  ('Acts 4:12', 'hi', 'और किसी दूसरे के द्वारा उद्धार नहीं; क्योंकि स्वर्ग के नीचे मनुष्यों में और कोई दूसरा नाम नहीं दिया गया, जिसके द्वारा हम उद्धार पा सके।'),
  ('Romans 6:23', 'hi', 'क्योंकि पाप की मजदूरी तो मृत्यु है, परन्तु परमेश्वर का वरदान हमारे प्रभु मसीह यीशु में अनन्त जीवन है।'),
  ('Matthew 11:28', 'hi', 'हे सब परिश्रम करनेवालों और बोझ से दबे लोगों, मेरे पास आओ; मैं तुम्हें विश्राम दूँगा।'),
  ('Psalm 23:4', 'hi', 'चाहे मैं घोर अंधकार से भरी हुई तराई में होकर चलूँ, तो भी हानि से न डरूँगा, क्योंकि तू मेरे साथ रहता है; तेरे सोंटे और तेरी लाठी से मुझे शान्ति मिलती है।'),
  ('Isaiah 41:10', 'hi', 'मत डर, क्योंकि मैं तेरे संग हूँ, इधर-उधर मत ताक, क्योंकि मैं तेरा परमेश्वर हूँ; मैं तुझे दृढ़ करूँगा और तेरी सहायता करूँगा, अपने धर्ममय दाहिने हाथ से मैं तुझे सम्भाले रहूँगा।'),
  ('John 14:27', 'hi', 'मैं तुम्हें शान्ति दिए जाता हूँ , अपनी शान्ति तुम्हें देता हूँ; जैसे संसार देता है, मैं तुम्हें नहीं देता: तुम्हारा मन न घबराए और न डरे।'),
  ('2 Corinthians 1:3', 'hi', 'हमारे प्रभु यीशु मसीह के परमेश्वर, और पिता का धन्यवाद हो, जो दया का पिता, और सब प्रकार की शान्ति का परमेश्वर है।'),
  ('Philippians 4:13', 'hi', 'जो मुझे सामर्थ्य देता है उसमें मैं सब कुछ कर सकता हूँ।'),
  ('Isaiah 40:31', 'hi', 'परन्तु जो यहोवा की बाट जोहते हैं, वे नया बल प्राप्त करते जाएँगे, वे उकाबों के समान उड़ेंगे, वे दौड़ेंगे और श्रमित न होंगे, चलेंगे और थकित न होंगे।'),
  ('Psalm 46:1', 'hi', 'परमेश्वर हमारा शरणस्थान और बल है, संकट में अति सहज से मिलनेवाला सहायक।'),
  ('2 Corinthians 12:9', 'hi', 'और उसने मुझसे कहा, “मेरा अनुग्रह तेरे लिये बहुत है; क्योंकि मेरी सामर्थ्य निर्बलता में सिद्ध होती है ।” इसलिए मैं बड़े आनन्द से अपनी निर्बलताओं पर घमण्ड करूँगा, कि मसीह की सामर्थ्य मुझ पर छाया करती रहे।'),
  ('Nehemiah 8:10', 'hi', 'फिर उसने उनसे कहा, “जाकर चिकना-चिकना भोजन करो और मीठा-मीठा रस पियो, और जिनके लिये कुछ तैयार नहीं हुआ उनके पास भोजन सामग्री भेजो; क्योंकि आज का दिन हमारे प्रभु के लिये पवित्र है; और उदास मत रहो, क्योंकि यहोवा का आनन्द तुम्हारा दृढ़ गढ़ है।”'),
  ('Proverbs 3:5', 'hi', 'तू अपनी समझ का सहारा न लेना, वरन् सम्पूर्ण मन से यहोवा पर भरोसा रखना।'),
  ('James 1:5', 'hi', 'पर यदि तुम में से किसी को बुद्धि की घटी हो, तो परमेश्वर से माँगो, जो बिना उलाहना दिए सब को उदारता से देता है; और उसको दी जाएगी।'),
  ('Proverbs 9:10', 'hi', 'यहोवा का भय मानना बुद्धि का आरम्भ है, और परमपवित्र परमेश्वर को जानना ही समझ है।'),
  ('Psalm 119:105', 'hi', 'तेरा वचन मेरे पाँव के लिये दीपक, और मेरे मार्ग के लिये उजियाला है।'),
  ('Colossians 2:3', 'hi', 'जिसमें बुद्धि और ज्ञान के सारे भण्डार छिपे हुए हैं।'),
  ('Jeremiah 29:11', 'hi', 'क्योंकि यहोवा की यह वाणी है, कि जो कल्पनाएँ मैं तुम्हारे विषय करता हूँ उन्हें मैं जानता हूँ, वे हानि की नहीं, वरन् कुशल ही की हैं, और अन्त में तुम्हारी आशा पूरी करूँगा।'),
  ('Romans 8:28', 'hi', 'और हम जानते हैं, कि जो लोग परमेश्वर से प्रेम रखते हैं, उनके लिये सब बातें मिलकर भलाई ही को उत्पन्न करती हैं; अर्थात् उन्हीं के लिये जो उसकी इच्छा के अनुसार बुलाए हुए हैं।'),
  ('Psalm 37:4', 'hi', 'यहोवा को अपने सुख का मूल जान, और वह तेरे मनोरथों को पूरा करेगा।'),
  ('Joshua 1:9', 'hi', 'क्या मैंने तुझे आज्ञा नहीं दी? हियाव बाँधकर दृढ़ हो जा; भय न खा, और तेरा मन कच्चा न हो; क्योंकि जहाँ-जहाँ तू जाएगा वहाँ-वहाँ तेरा परमेश्वर यहोवा तेरे संग रहेगा।'),
  ('Hebrews 13:5', 'hi', 'तुम्हारा स्वभाव लोभरहित हो, और जो तुम्हारे पास है, उसी पर संतोष किया करो; क्योंकि उसने आप ही कहा है, “मैं तुझे कभी न छोड़ूँगा, और न कभी तुझे त्यागूँगा।”'),
  ('Proverbs 3:6', 'hi', 'उसी को स्मरण करके सब काम करना, तब वह तेरे लिये सीधा मार्ग निकालेगा।'),
  ('John 16:13', 'hi', 'परन्तु जब वह अर्थात् सत्य का आत्मा आएगा, तो तुम्हें सब सत्य का मार्ग बताएगा, क्योंकि वह अपनी ओर से न कहेगा, परन्तु जो कुछ सुनेगा, वही कहेगा, और आनेवाली बातें तुम्हें बताएगा।'),
  ('Psalm 32:8', 'hi', 'मैं तुझे बुद्धि दूँगा, और जिस मार्ग में तुझे चलना होगा उसमें तेरी अगुआई करूँगा; मैं तुझ पर कृपादृष्टि रखूँगा और सम्मति दिया करूँगा।'),
  ('Isaiah 30:21', 'hi', 'और जब कभी तुम दाहिनी या बायीं ओर मुड़ने लगो, तब तुम्हारे पीछे से यह वचन तुम्हारे कानों में पड़ेगा, “मार्ग यही है, इसी पर चलो।”'),
  ('Psalm 25:4', 'hi', 'हे यहोवा, अपने मार्ग मुझ को दिखा; अपना पथ मुझे बता दे।'),
  ('Hebrews 11:1', 'hi', 'अब विश्वास आशा की हुई वस्तुओं का निश्चय, और अनदेखी वस्तुओं का प्रमाण है।'),
  ('Matthew 17:20', 'hi', 'उसने उनसे कहा, “अपने विश्वास की कमी के कारण: क्योंकि मैं तुम से सच कहता हूँ, यदि तुम्हारा विश्वास राई के दाने के बराबर भी हो, तो इस पहाड़ से कह सकोगे, ‘यहाँ से सरककर वहाँ चला जा’, तो वह चला जाएगा; और कोई बात तुम्हारे लिये अनहोनी न होगी।'),
  ('Romans 10:17', 'hi', 'इसलिए विश्वास सुनने से, और सुनना मसीह के वचन से होता है।'),
  ('2 Corinthians 5:7', 'hi', 'क्योंकि हम रूप को देखकर नहीं, पर विश्वास से चलते हैं।'),
  ('1 John 5:14', 'hi', 'और हमें उसके सामने जो साहस होता है, वह यह है; कि यदि हम उसकी इच्छा के अनुसार कुछ माँगते हैं, तो हमारी सुनता है।'),
  ('1 Corinthians 13:4', 'hi', 'प्रेम धीरजवन्त है, और कृपालु है; प्रेम डाह नहीं करता; प्रेम अपनी बड़ाई नहीं करता, और फूलता नहीं।'),
  ('Romans 5:8', 'hi', 'परन्तु परमेश्वर हम पर अपने प्रेम की भलाई इस रीति से प्रगट करता है, कि जब हम पापी ही थे तभी मसीह हमारे लिये मरा।'),
  ('1 John 4:8', 'hi', 'जो प्रेम नहीं रखता वह परमेश्वर को नहीं जानता है, क्योंकि परमेश्वर प्रेम है।'),
  ('1 John 4:19', 'hi', 'हम इसलिए प्रेम करते हैं, क्योंकि पहले उसने हम से प्रेम किया।'),
  ('John 15:13', 'hi', 'इससे बड़ा प्रेम किसी का नहीं, कि कोई अपने मित्रों के लिये अपना प्राण दे।'),
  ('John 3:16', 'ml', 'തന്‍റെ ഏകജാതനായ പുത്രനിൽ വിശ്വസിക്കുന്ന ഏവനും നശിച്ചുപോകാതെ നിത്യജീവൻ പ്രാപിക്കേണ്ടതിന് ദൈവം അവനെ നല്കുവാൻ തക്കവണ്ണം ലോകത്തെ സ്നേഹിച്ചു.'),
  ('Romans 10:9', 'ml', 'യേശുവിനെ കർത്താവ് എന്നു വായ്കൊണ്ട് ഏറ്റുപറയുകയും ദൈവം അവനെ മരിച്ചവരിൽ നിന്നു ഉയിർത്തെഴുന്നേല്പിച്ചു എന്നു ഹൃദയംകൊണ്ട് വിശ്വസിക്കയും ചെയ്താൽ നീ രക്ഷിക്കപ്പെടും.'),
  ('Ephesians 2:8', 'ml', 'കൃപയാലല്ലോ നിങ്ങൾ വിശ്വാസംമൂലം രക്ഷിയ്ക്കപ്പെട്ടിരിക്കുന്നത്; അതിനും നിങ്ങൾ കാരണക്കാരല്ല; അത് ദൈവത്തിന്‍റെ ദാനമത്രേയാകുന്നു.'),
  ('Acts 4:12', 'ml', 'മറ്റൊരുവനിലും രക്ഷ ഇല്ല; നാം രക്ഷിക്കപ്പെടുവാൻ ആകാശത്തിൻ കീഴിൽ മനുഷ്യരുടെ ഇടയിൽ നല്കപ്പെട്ട വേറൊരു നാമവും ഇല്ല.'),
  ('Romans 6:23', 'ml', 'പാപത്തിന്‍റെ ശമ്പളം മരണമത്രേ; ദൈവത്തിന്‍റെ കൃപാവരമോ നമ്മുടെ കർത്താവായ ക്രിസ്തുയേശുവിൽ നിത്യജീവൻ തന്നെ.'),
  ('Matthew 11:28', 'ml', 'അദ്ധ്വാനിക്കുന്നവരും ഭാരം ചുമക്കുന്നവരും ആയുള്ളോരേ, എല്ലാവരും എന്‍റെ അടുക്കൽ വരുവിൻ; ഞാൻ നിങ്ങൾക്ക് വിശ്രമം നൽകാം.'),
  ('Psalm 23:4', 'ml', 'മരണനിഴലിൻ താഴ്വരയിൽ കൂടിനടന്നാലും ഞാൻ ഒരു അനർത്ഥവും ഭയപ്പെടുകയില്ല; അങ്ങ് എന്നോടുകൂടി ഇരിക്കുന്നുവല്ലോ; അങ്ങേയുടെ വടിയും കോലും എന്നെ ആശ്വസിപ്പിക്കുന്നു.'),
  ('Isaiah 41:10', 'ml', 'നീ ഭയപ്പെടേണ്ടാ; ഞാൻ നിന്നോടുകൂടെ ഉണ്ട്; ഭ്രമിച്ചുനോക്കേണ്ടാ, ഞാൻ നിന്‍റെ ദൈവം ആകുന്നു; ഞാൻ നിന്നെ ശക്തീകരിക്കും; ഞാൻ നിന്നെ സഹായിക്കും; എന്‍റെ നീതിയുള്ള വലംകൈകൊണ്ടു ഞാൻ നിന്നെ താങ്ങും.'),
  ('John 14:27', 'ml', 'സമാധാനം ഞാൻ നിങ്ങൾക്ക് തന്നിട്ടുപോകുന്നു; എന്‍റെ സമാധാനം ഞാൻ നിങ്ങൾക്ക് തരുന്നു; ലോകം തരുന്നതുപോലെ അല്ല ഞാൻ ഇത് നിങ്ങൾക്ക് തരുന്നത്. നിങ്ങളുടെ ഹൃദയം കലങ്ങരുത്, ഭ്രമിക്കുകയും അരുത്.'),
  ('2 Corinthians 1:3', 'ml', 'കരുണ നിറഞ്ഞ പിതാവും സർവ്വ ആശ്വാസത്തിൻ്റെ ദൈവവുമായ നമ്മുടെ കർത്താവായ യേശുക്രിസ്തുവിന്‍റെ പിതാവായ ദൈവം വാഴ്ത്തപ്പെടുമാറാകട്ടെ.'),
  ('Philippians 4:13', 'ml', 'എന്നെ ശക്തനാക്കുന്നവൻ മുഖാന്തരം എനിക്ക് എല്ലാം ചെയ്യുവാൻ കഴിയും.'),
  ('Isaiah 40:31', 'ml', 'എങ്കിലും യഹോവയെ കാത്തിരിക്കുന്നവർ ശക്തിയെ പുതുക്കും; അവർ കഴുകന്മാരെപ്പോലെ ചിറകടിച്ചു കയറും; അവർ തളർന്നുപോകാതെ ഓടുകയും ക്ഷീണിച്ചുപോകാതെ നടക്കുകയും ചെയ്യും.'),
  ('Psalm 46:1', 'ml', 'ദൈവം നമ്മുടെ സങ്കേതവും ബലവും ആകുന്നു; കഷ്ടസമയത്ത് അവിടുന്ന് ഏറ്റവും അടുത്ത സഹായമായിരിക്കുന്നു.'),
  ('2 Corinthians 12:9', 'ml', 'അവൻ എന്നോട്: എന്‍റെ കൃപ നിനക്കു മതി; എന്‍റെ ശക്തി ബലഹീനതയിൽ തികഞ്ഞുവരുന്നുവല്ലോ എന്നു പറഞ്ഞു. ആകയാൽ ക്രിസ്തുവിന്‍റെ ശക്തി എന്‍റെ മേൽ ആവസിക്കേണ്ടതിന് ഞാൻ അതിസന്തോഷത്തോടെ എന്‍റെ ബലഹീനതകളിൽ പ്രശംസിക്കും.'),
  ('Nehemiah 8:10', 'ml', 'അനന്തരം അവർ അവരോട്: “നിങ്ങൾ ചെന്നു നല്ല ഭക്ഷണവും മധുരപാനീയവും കഴിച്ച് തങ്ങൾക്കായി കരുതിയിട്ടില്ലാത്തവർക്കായി ഓഹരി കൊടുത്തയപ്പിൻ; ഈ ദിവസം നമ്മുടെ കർത്താവിന് വിശുദ്ധമാകുന്നു; നിങ്ങൾ ദുഃഖിക്കരുത്; യഹോവയിങ്കലെ സന്തോഷം നിങ്ങളുടെ ബലം ആകുന്നുവല്ലോ” എന്നു പറഞ്ഞു.'),
  ('Proverbs 3:5', 'ml', 'പൂർണ്ണഹൃദയത്തോടെ യഹോവയിൽ ആശ്രയിക്കുക; സ്വന്ത വിവേകത്തിൽ ആശ്രയിക്കരുത്.'),
  ('James 1:5', 'ml', 'നിങ്ങളിൽ ഒരാൾക്ക് ജ്ഞാനം കുറവാകുന്നു എങ്കിൽ, ശകാരിക്കാതെയും സന്തോഷത്തോടെ എല്ലാവർക്കും ഔദാര്യമായി കൊടുക്കുന്നവനുമായ ദൈവത്തോട് യാചിക്കട്ടെ; അപ്പോൾ അവനു ലഭിക്കും.'),
  ('Proverbs 9:10', 'ml', 'യഹോവാഭക്തി ജ്ഞാനത്തിന്‍റെ ആരംഭവും പരിശുദ്ധ ദൈവത്തെക്കുറിച്ചുള്ള പരിജ്ഞാനം വിവേകവും ആകുന്നു.'),
  ('Psalm 119:105', 'ml', 'അങ്ങേയുടെ വചനം എന്‍റെ കാലിന് ദീപവും എന്‍റെ പാതയ്ക്കു പ്രകാശവും ആകുന്നു.'),
  ('Colossians 2:3', 'ml', 'ക്രിസ്തുവില്‍ ജ്ഞാനത്തിൻ്റെയും അറിവിൻ്റേയും നിക്ഷേപങ്ങൾ ഒക്കെയും മറഞ്ഞിരിക്കുന്നു.'),
  ('Jeremiah 29:11', 'ml', 'നിങ്ങൾ പ്രത്യാശിക്കുന്ന ശുഭഭാവി വരുവാൻ തക്കവണ്ണം എനിക്ക് നിങ്ങളെക്കുറിച്ചുള്ള നിരൂപണങ്ങൾ എന്തെല്ലാമെന്ന് ഞാൻ അറിയുന്നു; അവ തിന്മയ്ക്കല്ല, നന്മയ്ക്കുള്ളവയത്രേ എന്നു യഹോവയുടെ അരുളപ്പാടു.'),
  ('Romans 8:28', 'ml', 'എന്നാൽ ദൈവത്തെ സ്നേഹിക്കുന്നവർക്ക്, നിർണ്ണയപ്രകാരം വിളിക്കപ്പെട്ടവർക്കു തന്നെ, സകലവും നന്മയ്ക്കായി കൂടി വ്യാപരിക്കുന്നു എന്നു നാം അറിയുന്നു.'),
  ('Psalm 37:4', 'ml', 'യഹോവയിൽ തന്നെ രസിച്ചുകൊള്ളുക; കർത്താവ് നിന്‍റെ ഹൃദയത്തിലെ ആഗ്രഹങ്ങൾ നിനക്കു തരും.'),
  ('Joshua 1:9', 'ml', 'നിന്‍റെ ദൈവമായ യഹോവ നീ പോകുന്ന ഇടത്തൊക്കെയും നിന്നോടുകൂടെ ഉള്ളതുകൊണ്ട് ഉറപ്പും ധൈര്യവുമുള്ളവനായിരിക്ക; ഭയപ്പെടരുത്, ഭ്രമിക്കയും അരുത് ഞാൻ തന്നെ നിന്നോട് കല്പിച്ചുവല്ലോ.'),
  ('Hebrews 13:5', 'ml', 'നിങ്ങളുടെ ജീവിതവഴികളിൽ ദ്രവ്യാഗ്രഹമില്ലാതിരിക്കട്ടെ; ഉള്ളതുകൊണ്ട് സംതൃപ്തിപ്പെടുവിൻ: “ഞാൻ നിന്നെ ഒരുനാളും കൈവിടുകയില്ല, ഉപേക്ഷിക്കുകയുമില്ല” എന്നു ദൈവം തന്നെ അരുളിച്ചെയ്തിരിക്കുന്നുവല്ലോ.'),
  ('Proverbs 3:6', 'ml', 'നിന്‍റെ എല്ലാ വഴികളിലും അവിടുത്തെ അംഗീകരിച്ചുകൊള്ളുക; അവിടുന്ന് നിന്‍റെ പാതകളെ നേരെയാക്കും;'),
  ('John 16:13', 'ml', 'സത്യത്തിന്‍റെ ആത്മാവ് വരുമ്പോഴോ അവൻ നിങ്ങളെ സകല സത്യത്തിലും വഴിനടത്തും; അവൻ സ്വയമായി സംസാരിക്കാതെ താൻ കേൾക്കുന്നത് സംസാരിക്കുകയും വരുവാനുള്ളതു നിങ്ങൾക്ക് അറിയിച്ചുതരികയും ചെയ്യും.'),
  ('Psalm 32:8', 'ml', 'ഞാൻ നിന്നെ ഉപദേശിച്ച്, നടക്കേണ്ട വഴി നിനക്കു കാണിച്ചുതരും; ഞാൻ നിന്‍റെമേൽ ദൃഷ്ടിവെച്ച് നിനക്കു ആലോചന പറഞ്ഞുതരും.'),
  ('Isaiah 30:21', 'ml', 'നിങ്ങൾ വലത്തോട്ടോ ഇടത്തോട്ടോ തിരിയുമ്പോൾ: “വഴി ഇതാകുന്നു, ഇതിൽ നടന്നുകൊള്ളുവിൻ” എന്നൊരു വാക്ക് പിറകിൽനിന്നു കേൾക്കും.'),
  ('Psalm 25:4', 'ml', 'യഹോവേ, അങ്ങേയുടെ വഴികൾ എന്നെ അറിയിക്കേണമേ; അങ്ങേയുടെ പാതകൾ എനിക്ക് ഉപദേശിച്ചു തരേണമേ!'),
  ('Hebrews 11:1', 'ml', 'എന്നാൽ വിശ്വാസം എന്നതോ, ധൈര്യത്തോടെ ചിലത് പ്രതീക്ഷിക്കുന്ന ഒരുവന്‍റെ ഉറപ്പാണ്. അത് കാണാൻ കഴിയാത്ത കാര്യങ്ങളുടെ നിശ്ചയവും ആകുന്നു.'),
  ('Matthew 17:20', 'ml', 'അവൻ അവരോട്: നിങ്ങളുടെ അല്പവിശ്വാസം നിമിത്തമത്രേ;'),
  ('Romans 10:17', 'ml', 'ആകയാൽ വിശ്വാസം കേൾവിയാലും കേൾവി ക്രിസ്തുവിന്‍റെ വചനത്താലും വരുന്നു.'),
  ('2 Corinthians 5:7', 'ml', 'എന്തെന്നാൽ, കാഴ്ചയാൽ അല്ല, വിശ്വാസത്താലത്രേ ഞങ്ങൾ നടക്കുന്നത്.'),
  ('1 John 5:14', 'ml', 'അവന്‍റെ ഇഷ്ടപ്രകാരം നാം എന്തെങ്കിലും ചോദിച്ചാൽ അവൻ നമ്മെ കേൾക്കുന്നു എന്നുള്ളത് നമുക്ക് അവനിലുള്ള ധൈര്യമാകുന്നു.'),
  ('1 Corinthians 13:4', 'ml', 'സ്നേഹം ദീർഘമായി ക്ഷമിക്കുന്നു; ദയ കാണിക്കുന്നു; സ്നേഹം അസൂയപ്പെടുന്നില്ല,'),
  ('Romans 5:8', 'ml', 'ക്രിസ്തുവോ, നാം പാപികൾ ആയിരിക്കുമ്പോൾതന്നെ നമുക്കുവേണ്ടി മരിച്ചു. അങ്ങനെ ദൈവം നമ്മോടുള്ള അവന്‍റെ സ്നേഹത്തെ പ്രദർശിപ്പിച്ചിരിക്കുന്നു.'),
  ('1 John 4:8', 'ml', 'ദൈവം സ്നേഹം തന്നെയായതിനാൽ, സ്നേഹിക്കാത്തവൻ ദൈവത്തെ അറിഞ്ഞിട്ടില്ല.'),
  ('1 John 4:19', 'ml', 'ദൈവം ആദ്യം നമ്മെ സ്നേഹിച്ചതുകൊണ്ട് നാം സ്നേഹിക്കുന്നു.'),
  ('John 15:13', 'ml', 'തന്‍റെ സ്നേഹിതന്മാർക്കുവേണ്ടി ജീവനെ കൊടുക്കുന്നതിലും അധികമുള്ള സ്നേഹം ആർക്കും ഇല്ല.');

-- 1. memory verses copied from the old suggested wording → new wording
UPDATE public.memory_verses mv
SET verse_text = n.verse_text,
    verse_text_synced_at = NOW(),
    updated_at = NOW()
FROM public.suggested_verse_translations t
JOIN public.suggested_verses s ON s.id = t.suggested_verse_id
JOIN _suggested_text n ON n.reference = s.reference AND n.language_code = t.language_code
WHERE mv.source_type = 'manual'
  AND mv.language = t.language_code
  AND mv.verse_reference IN (t.localized_reference, s.reference)
  AND mv.verse_text = t.verse_text
  AND t.verse_text IS DISTINCT FROM n.verse_text;

-- 2. suggested verse text
UPDATE public.suggested_verse_translations t
SET verse_text = n.verse_text
FROM public.suggested_verses s, _suggested_text n
WHERE s.id = t.suggested_verse_id
  AND n.reference = s.reference
  AND n.language_code = t.language_code
  AND t.verse_text IS DISTINCT FROM n.verse_text;

DROP TABLE _suggested_text;
