// Mocks generated by Mockito 5.4.6 from annotations
// in disciplefy_bible_study/test/features/memory_verses/presentation/bloc/memory_verse_reset_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:disciplefy_bible_study/core/error/failures.dart' as _i5;
import 'package:disciplefy_bible_study/core/models/reset_progress_result.dart'
    as _i8;
import 'package:disciplefy_bible_study/features/memory_verses/data/services/memory_verse_notification_service.dart'
    as _i41;
import 'package:disciplefy_bible_study/features/memory_verses/data/services/suggested_verses_cache_service.dart'
    as _i42;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/daily_goal_entity.dart'
    as _i15;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/fetched_verse_entity.dart'
    as _i10;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/mastery_progress_entity.dart'
    as _i14;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/memory_challenge_entity.dart'
    as _i16;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/memory_champion_entry.dart'
    as _i17;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/memory_streak_entity.dart'
    as _i13;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/memory_verse_entity.dart'
    as _i6;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/practice_mode_entity.dart'
    as _i11;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/review_session_entity.dart'
    as _i9;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/review_statistics_entity.dart'
    as _i7;
import 'package:disciplefy_bible_study/features/memory_verses/domain/entities/suggested_verse_entity.dart'
    as _i18;
import 'package:disciplefy_bible_study/features/memory_verses/domain/repositories/memory_verse_repository.dart'
    as _i3;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/add_verse_from_daily.dart'
    as _i21;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/add_verse_manually.dart'
    as _i22;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/claim_challenge_reward.dart'
    as _i37;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/delete_verse.dart'
    as _i26;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/fetch_verse_text.dart'
    as _i25;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_active_challenges.dart'
    as _i36;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_cached_due_verses.dart'
    as _i20;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_daily_goal.dart'
    as _i33;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_due_verses.dart'
    as _i19;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_mastery_progress.dart'
    as _i31;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_memory_champions_leaderboard.dart'
    as _i38;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_memory_statistics.dart'
    as _i39;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_memory_streak.dart'
    as _i29;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_practice_mode_statistics.dart'
    as _i28;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_statistics.dart'
    as _i24;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/get_suggested_verses.dart'
    as _i40;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/select_practice_mode.dart'
    as _i27;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/set_daily_goal_targets.dart'
    as _i35;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/submit_practice_session.dart'
    as _i12;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/submit_review.dart'
    as _i23;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/update_daily_goal_progress.dart'
    as _i34;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/update_mastery_level.dart'
    as _i32;
import 'package:disciplefy_bible_study/features/memory_verses/domain/usecases/use_streak_freeze.dart'
    as _i30;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoryVerseRepository_1 extends _i1.SmartFake
    implements _i3.MemoryVerseRepository {
  _FakeMemoryVerseRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MemoryVerseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryVerseRepository extends _i1.Mock
    implements _i3.MemoryVerseRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> addVerseFromDaily({
    required String? dailyVerseId,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVerseFromDaily,
          [],
          {
            #dailyVerseId: dailyVerseId,
            #language: language,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #addVerseFromDaily,
            [],
            {
              #dailyVerseId: dailyVerseId,
              #language: language,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #addVerseFromDaily,
            [],
            {
              #dailyVerseId: dailyVerseId,
              #language: language,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> addVerseManually({
    required String? verseReference,
    required String? verseText,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVerseManually,
          [],
          {
            #verseReference: verseReference,
            #verseText: verseText,
            #language: language,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #addVerseManually,
            [],
            {
              #verseReference: verseReference,
              #verseText: verseText,
              #language: language,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #addVerseManually,
            [],
            {
              #verseReference: verseReference,
              #verseText: verseText,
              #language: language,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);

  @override
  _i4.Future<
          _i2.Either<_i5.Failure,
              (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>>
      getDueVerses({
    int? limit = 20,
    int? offset = 0,
    String? language,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getDueVerses,
              [],
              {
                #limit: limit,
                #offset: offset,
                #language: language,
              },
            ),
            returnValue: _i4.Future<
                _i2.Either<
                    _i5.Failure,
                    (
                      List<_i6.MemoryVerseEntity>,
                      _i7.ReviewStatisticsEntity
                    )>>.value(_FakeEither_0<_i5.Failure,
                (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>(
              this,
              Invocation.method(
                #getDueVerses,
                [],
                {
                  #limit: limit,
                  #offset: offset,
                  #language: language,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                _i2.Either<
                    _i5.Failure,
                    (
                      List<_i6.MemoryVerseEntity>,
                      _i7.ReviewStatisticsEntity
                    )>>.value(_FakeEither_0<_i5.Failure,
                (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>(
              this,
              Invocation.method(
                #getDueVerses,
                [],
                {
                  #limit: limit,
                  #offset: offset,
                  #language: language,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>>);

  @override
  _i4.Future<(List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)?>
      getCachedDueVerses({String? language}) => (super.noSuchMethod(
            Invocation.method(
              #getCachedDueVerses,
              [],
              {#language: language},
            ),
            returnValue: _i4.Future<
                (
                  List<_i6.MemoryVerseEntity>,
                  _i7.ReviewStatisticsEntity
                )?>.value(),
            returnValueForMissingStub: _i4.Future<
                (
                  List<_i6.MemoryVerseEntity>,
                  _i7.ReviewStatisticsEntity
                )?>.value(),
          ) as _i4.Future<
              (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)?>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> submitReview({
    required String? memoryVerseId,
    required int? qualityRating,
    int? timeSpentSeconds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitReview,
          [],
          {
            #memoryVerseId: memoryVerseId,
            #qualityRating: qualityRating,
            #timeSpentSeconds: timeSpentSeconds,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #submitReview,
            [],
            {
              #memoryVerseId: memoryVerseId,
              #qualityRating: qualityRating,
              #timeSpentSeconds: timeSpentSeconds,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #submitReview,
            [],
            {
              #memoryVerseId: memoryVerseId,
              #qualityRating: qualityRating,
              #timeSpentSeconds: timeSpentSeconds,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>>
      getStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getStatistics,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>>.value(
                _FakeEither_0<_i5.Failure, _i7.ReviewStatisticsEntity>(
              this,
              Invocation.method(
                #getStatistics,
                [],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>>.value(
                _FakeEither_0<_i5.Failure, _i7.ReviewStatisticsEntity>(
              this,
              Invocation.method(
                #getStatistics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> getVerseById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerseById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #getVerseById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #getVerseById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          List<_i6.MemoryVerseEntity>>> getAllVerses() => (super.noSuchMethod(
        Invocation.method(
          #getAllVerses,
          [],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.MemoryVerseEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.MemoryVerseEntity>>(
          this,
          Invocation.method(
            #getAllVerses,
            [],
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.MemoryVerseEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.MemoryVerseEntity>>(
          this,
          Invocation.method(
            #getAllVerses,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemoryVerseEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> deleteVerse(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVerse,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteVerse,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteVerse,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          _i8.ResetProgressResult>> resetMemoryProgress() =>
      (super.noSuchMethod(
        Invocation.method(
          #resetMemoryProgress,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.ResetProgressResult>>.value(
                _FakeEither_0<_i5.Failure, _i8.ResetProgressResult>(
          this,
          Invocation.method(
            #resetMemoryProgress,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i8.ResetProgressResult>>.value(
                _FakeEither_0<_i5.Failure, _i8.ResetProgressResult>(
          this,
          Invocation.method(
            #resetMemoryProgress,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.ResetProgressResult>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i9.ReviewSessionEntity>>> getReviewHistory({
    required String? memoryVerseId,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReviewHistory,
          [],
          {
            #memoryVerseId: memoryVerseId,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, List<_i9.ReviewSessionEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i9.ReviewSessionEntity>>(
          this,
          Invocation.method(
            #getReviewHistory,
            [],
            {
              #memoryVerseId: memoryVerseId,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2.Either<_i5.Failure, List<_i9.ReviewSessionEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i9.ReviewSessionEntity>>(
          this,
          Invocation.method(
            #getReviewHistory,
            [],
            {
              #memoryVerseId: memoryVerseId,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.ReviewSessionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> syncWithRemote() =>
      (super.noSuchMethod(
        Invocation.method(
          #syncWithRemote,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #syncWithRemote,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #syncWithRemote,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> clearLocalCache() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearLocalCache,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #clearLocalCache,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #clearLocalCache,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>> fetchVerseText({
    required String? book,
    required int? chapter,
    required int? verseStart,
    int? verseEnd,
    required String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchVerseText,
          [],
          {
            #book: book,
            #chapter: chapter,
            #verseStart: verseStart,
            #verseEnd: verseEnd,
            #language: language,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i10.FetchedVerseEntity>(
          this,
          Invocation.method(
            #fetchVerseText,
            [],
            {
              #book: book,
              #chapter: chapter,
              #verseStart: verseStart,
              #verseEnd: verseEnd,
              #language: language,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i10.FetchedVerseEntity>(
          this,
          Invocation.method(
            #fetchVerseText,
            [],
            {
              #book: book,
              #chapter: chapter,
              #verseStart: verseStart,
              #verseEnd: verseEnd,
              #language: language,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i11.PracticeModeEntity>> selectPracticeMode({
    required String? verseId,
    required _i11.PracticeModeType? practiceMode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectPracticeMode,
          [],
          {
            #verseId: verseId,
            #practiceMode: practiceMode,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i11.PracticeModeEntity>>.value(
                _FakeEither_0<_i5.Failure, _i11.PracticeModeEntity>(
          this,
          Invocation.method(
            #selectPracticeMode,
            [],
            {
              #verseId: verseId,
              #practiceMode: practiceMode,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i11.PracticeModeEntity>>.value(
                _FakeEither_0<_i5.Failure, _i11.PracticeModeEntity>(
          this,
          Invocation.method(
            #selectPracticeMode,
            [],
            {
              #verseId: verseId,
              #practiceMode: practiceMode,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i11.PracticeModeEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i12.SubmitPracticeSessionResponse>>
      submitPracticeSession(_i12.SubmitPracticeSessionParams? params) =>
          (super.noSuchMethod(
            Invocation.method(
              #submitPracticeSession,
              [params],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i12.SubmitPracticeSessionResponse>>.value(
                _FakeEither_0<_i5.Failure, _i12.SubmitPracticeSessionResponse>(
              this,
              Invocation.method(
                #submitPracticeSession,
                [params],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i12.SubmitPracticeSessionResponse>>.value(
                _FakeEither_0<_i5.Failure, _i12.SubmitPracticeSessionResponse>(
              this,
              Invocation.method(
                #submitPracticeSession,
                [params],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i12.SubmitPracticeSessionResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i11.PracticeModeEntity>>>
      getPracticeModeStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getPracticeModeStatistics,
              [],
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i11.PracticeModeEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i11.PracticeModeEntity>>(
              this,
              Invocation.method(
                #getPracticeModeStatistics,
                [],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i11.PracticeModeEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i11.PracticeModeEntity>>(
              this,
              Invocation.method(
                #getPracticeModeStatistics,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i11.PracticeModeEntity>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          _i13.MemoryStreakEntity>> getMemoryStreak() => (super.noSuchMethod(
        Invocation.method(
          #getMemoryStreak,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>.value(
                _FakeEither_0<_i5.Failure, _i13.MemoryStreakEntity>(
          this,
          Invocation.method(
            #getMemoryStreak,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>.value(
                _FakeEither_0<_i5.Failure, _i13.MemoryStreakEntity>(
          this,
          Invocation.method(
            #getMemoryStreak,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>> useStreakFreeze(
          {required DateTime? freezeDate}) =>
      (super.noSuchMethod(
        Invocation.method(
          #useStreakFreeze,
          [],
          {#freezeDate: freezeDate},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>.value(
                _FakeEither_0<_i5.Failure, _i13.MemoryStreakEntity>(
          this,
          Invocation.method(
            #useStreakFreeze,
            [],
            {#freezeDate: freezeDate},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>.value(
                _FakeEither_0<_i5.Failure, _i13.MemoryStreakEntity>(
          this,
          Invocation.method(
            #useStreakFreeze,
            [],
            {#freezeDate: freezeDate},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, (bool, int?)>> checkStreakMilestone() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkStreakMilestone,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, (bool, int?)>>.value(
            _FakeEither_0<_i5.Failure, (bool, int?)>(
          this,
          Invocation.method(
            #checkStreakMilestone,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, (bool, int?)>>.value(
                _FakeEither_0<_i5.Failure, (bool, int?)>(
          this,
          Invocation.method(
            #checkStreakMilestone,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, (bool, int?)>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i14.MasteryProgressEntity>> getMasteryProgress(
          {required String? verseId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMasteryProgress,
          [],
          {#verseId: verseId},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>.value(
            _FakeEither_0<_i5.Failure, _i14.MasteryProgressEntity>(
          this,
          Invocation.method(
            #getMasteryProgress,
            [],
            {#verseId: verseId},
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>.value(
            _FakeEither_0<_i5.Failure, _i14.MasteryProgressEntity>(
          this,
          Invocation.method(
            #getMasteryProgress,
            [],
            {#verseId: verseId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i14.MasteryProgressEntity>> updateMasteryLevel({
    required String? verseId,
    required _i14.MasteryLevel? newMasteryLevel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMasteryLevel,
          [],
          {
            #verseId: verseId,
            #newMasteryLevel: newMasteryLevel,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>.value(
            _FakeEither_0<_i5.Failure, _i14.MasteryProgressEntity>(
          this,
          Invocation.method(
            #updateMasteryLevel,
            [],
            {
              #verseId: verseId,
              #newMasteryLevel: newMasteryLevel,
            },
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>.value(
            _FakeEither_0<_i5.Failure, _i14.MasteryProgressEntity>(
          this,
          Invocation.method(
            #updateMasteryLevel,
            [],
            {
              #verseId: verseId,
              #newMasteryLevel: newMasteryLevel,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>> getDailyGoal() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyGoal,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
          this,
          Invocation.method(
            #getDailyGoal,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
          this,
          Invocation.method(
            #getDailyGoal,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>
      updateDailyGoalProgress({required bool? isNewVerse}) =>
          (super.noSuchMethod(
            Invocation.method(
              #updateDailyGoalProgress,
              [],
              {#isNewVerse: isNewVerse},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                    _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
              this,
              Invocation.method(
                #updateDailyGoalProgress,
                [],
                {#isNewVerse: isNewVerse},
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                    _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
              this,
              Invocation.method(
                #updateDailyGoalProgress,
                [],
                {#isNewVerse: isNewVerse},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>
      setDailyGoalTargets({
    required int? targetReviews,
    required int? targetNewVerses,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #setDailyGoalTargets,
              [],
              {
                #targetReviews: targetReviews,
                #targetNewVerses: targetNewVerses,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                    _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
              this,
              Invocation.method(
                #setDailyGoalTargets,
                [],
                {
                  #targetReviews: targetReviews,
                  #targetNewVerses: targetNewVerses,
                },
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                    _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
              this,
              Invocation.method(
                #setDailyGoalTargets,
                [],
                {
                  #targetReviews: targetReviews,
                  #targetNewVerses: targetNewVerses,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i16.MemoryChallengeEntity>>>
      getActiveChallenges() => (super.noSuchMethod(
            Invocation.method(
              #getActiveChallenges,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i16.MemoryChallengeEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i16.MemoryChallengeEntity>>(
              this,
              Invocation.method(
                #getActiveChallenges,
                [],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i16.MemoryChallengeEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i16.MemoryChallengeEntity>>(
              this,
              Invocation.method(
                #getActiveChallenges,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i16.MemoryChallengeEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, (_i16.MemoryChallengeEntity, int)>>
      claimChallengeReward({required String? challengeId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #claimChallengeReward,
              [],
              {#challengeId: challengeId},
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        (_i16.MemoryChallengeEntity, int)>>.value(
                _FakeEither_0<_i5.Failure, (_i16.MemoryChallengeEntity, int)>(
              this,
              Invocation.method(
                #claimChallengeReward,
                [],
                {#challengeId: challengeId},
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure,
                        (_i16.MemoryChallengeEntity, int)>>.value(
                _FakeEither_0<_i5.Failure, (_i16.MemoryChallengeEntity, int)>(
              this,
              Invocation.method(
                #claimChallengeReward,
                [],
                {#challengeId: challengeId},
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, (_i16.MemoryChallengeEntity, int)>>);

  @override
  _i4.Future<
          _i2.Either<_i5.Failure,
              (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>>
      getMemoryChampionsLeaderboard({
    required String? period,
    int? limit = 100,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getMemoryChampionsLeaderboard,
              [],
              {
                #period: period,
                #limit: limit,
              },
            ),
            returnValue: _i4.Future<
                _i2.Either<
                    _i5.Failure,
                    (
                      List<_i17.MemoryChampionEntry>,
                      _i17.UserMemoryStats
                    )>>.value(_FakeEither_0<_i5.Failure,
                (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>(
              this,
              Invocation.method(
                #getMemoryChampionsLeaderboard,
                [],
                {
                  #period: period,
                  #limit: limit,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                _i2.Either<
                    _i5.Failure,
                    (
                      List<_i17.MemoryChampionEntry>,
                      _i17.UserMemoryStats
                    )>>.value(_FakeEither_0<_i5.Failure,
                (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>(
              this,
              Invocation.method(
                #getMemoryChampionsLeaderboard,
                [],
                {
                  #period: period,
                  #limit: limit,
                },
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
      getMemoryStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getMemoryStatistics,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getMemoryStatistics,
                [],
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #getMemoryStatistics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<
      _i2
      .Either<_i5.Failure, _i18.SuggestedVersesResponse>> getSuggestedVerses({
    _i18.SuggestedVerseCategory? category,
    String? language = 'en',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSuggestedVerses,
          [],
          {
            #category: category,
            #language: language,
          },
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, _i18.SuggestedVersesResponse>>.value(
            _FakeEither_0<_i5.Failure, _i18.SuggestedVersesResponse>(
          this,
          Invocation.method(
            #getSuggestedVerses,
            [],
            {
              #category: category,
              #language: language,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2.Either<_i5.Failure, _i18.SuggestedVersesResponse>>.value(
            _FakeEither_0<_i5.Failure, _i18.SuggestedVersesResponse>(
          this,
          Invocation.method(
            #getSuggestedVerses,
            [],
            {
              #category: category,
              #language: language,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i18.SuggestedVersesResponse>>);
}

/// A class which mocks [GetDueVerses].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDueVerses extends _i1.Mock implements _i19.GetDueVerses {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>> call({
    int? limit = 20,
    int? offset = 0,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #limit: limit,
            #offset: offset,
            #language: language,
          },
        ),
        returnValue: _i4.Future<
            _i2.Either<
                _i5.Failure,
                (
                  List<_i6.MemoryVerseEntity>,
                  _i7.ReviewStatisticsEntity
                )>>.value(_FakeEither_0<_i5.Failure,
            (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #limit: limit,
              #offset: offset,
              #language: language,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<
            _i2.Either<
                _i5.Failure,
                (
                  List<_i6.MemoryVerseEntity>,
                  _i7.ReviewStatisticsEntity
                )>>.value(_FakeEither_0<_i5.Failure,
            (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #limit: limit,
              #offset: offset,
              #language: language,
            },
          ),
        )),
      ) as _i4.Future<
          _i2.Either<_i5.Failure,
              (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)>>);
}

/// A class which mocks [GetCachedDueVerses].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCachedDueVerses extends _i1.Mock
    implements _i20.GetCachedDueVerses {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<(List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)?> call(
          {String? language}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#language: language},
        ),
        returnValue: _i4.Future<
            (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)?>.value(),
        returnValueForMissingStub: _i4.Future<
            (List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)?>.value(),
      ) as _i4
          .Future<(List<_i6.MemoryVerseEntity>, _i7.ReviewStatisticsEntity)?>);
}

/// A class which mocks [AddVerseFromDaily].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddVerseFromDaily extends _i1.Mock implements _i21.AddVerseFromDaily {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> call(
    String? dailyVerseId, {
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [dailyVerseId],
          {#language: language},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #call,
            [dailyVerseId],
            {#language: language},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #call,
            [dailyVerseId],
            {#language: language},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);
}

/// A class which mocks [AddVerseManually].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddVerseManually extends _i1.Mock implements _i22.AddVerseManually {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> call({
    required String? verseReference,
    required String? verseText,
    String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #verseReference: verseReference,
            #verseText: verseText,
            #language: language,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #verseReference: verseReference,
              #verseText: verseText,
              #language: language,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #verseReference: verseReference,
              #verseText: verseText,
              #language: language,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);
}

/// A class which mocks [SubmitReview].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmitReview extends _i1.Mock implements _i23.SubmitReview {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>> call({
    required String? memoryVerseId,
    required int? qualityRating,
    int? timeSpentSeconds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #memoryVerseId: memoryVerseId,
            #qualityRating: qualityRating,
            #timeSpentSeconds: timeSpentSeconds,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #memoryVerseId: memoryVerseId,
              #qualityRating: qualityRating,
              #timeSpentSeconds: timeSpentSeconds,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemoryVerseEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #memoryVerseId: memoryVerseId,
              #qualityRating: qualityRating,
              #timeSpentSeconds: timeSpentSeconds,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemoryVerseEntity>>);
}

/// A class which mocks [GetStatistics].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStatistics extends _i1.Mock implements _i24.GetStatistics {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>>.value(
            _FakeEither_0<_i5.Failure, _i7.ReviewStatisticsEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>>.value(
            _FakeEither_0<_i5.Failure, _i7.ReviewStatisticsEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.ReviewStatisticsEntity>>);
}

/// A class which mocks [FetchVerseText].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchVerseText extends _i1.Mock implements _i25.FetchVerseText {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>> call({
    required String? book,
    required int? chapter,
    required int? verseStart,
    int? verseEnd,
    required String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #book: book,
            #chapter: chapter,
            #verseStart: verseStart,
            #verseEnd: verseEnd,
            #language: language,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i10.FetchedVerseEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #book: book,
              #chapter: chapter,
              #verseStart: verseStart,
              #verseEnd: verseEnd,
              #language: language,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>>.value(
                _FakeEither_0<_i5.Failure, _i10.FetchedVerseEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #book: book,
              #chapter: chapter,
              #verseStart: verseStart,
              #verseEnd: verseEnd,
              #language: language,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i10.FetchedVerseEntity>>);
}

/// A class which mocks [DeleteVerse].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteVerse extends _i1.Mock implements _i26.DeleteVerse {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> call(String? verseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [verseId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #call,
            [verseId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #call,
            [verseId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}

/// A class which mocks [SelectPracticeMode].
///
/// See the documentation for Mockito's code generation for more information.
class MockSelectPracticeMode extends _i1.Mock
    implements _i27.SelectPracticeMode {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.PracticeModeEntity>> call({
    required String? verseId,
    required _i11.PracticeModeType? practiceMode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #verseId: verseId,
            #practiceMode: practiceMode,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i11.PracticeModeEntity>>.value(
                _FakeEither_0<_i5.Failure, _i11.PracticeModeEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #verseId: verseId,
              #practiceMode: practiceMode,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i11.PracticeModeEntity>>.value(
                _FakeEither_0<_i5.Failure, _i11.PracticeModeEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #verseId: verseId,
              #practiceMode: practiceMode,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i11.PracticeModeEntity>>);
}

/// A class which mocks [SubmitPracticeSession].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmitPracticeSession extends _i1.Mock
    implements _i12.SubmitPracticeSession {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i12.SubmitPracticeSessionResponse>> call(
          _i12.SubmitPracticeSessionParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i5.Failure, _i12.SubmitPracticeSessionResponse>>.value(
            _FakeEither_0<_i5.Failure, _i12.SubmitPracticeSessionResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2
                .Either<_i5.Failure, _i12.SubmitPracticeSessionResponse>>.value(
            _FakeEither_0<_i5.Failure, _i12.SubmitPracticeSessionResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, _i12.SubmitPracticeSessionResponse>>);
}

/// A class which mocks [GetPracticeModeStatistics].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPracticeModeStatistics extends _i1.Mock
    implements _i28.GetPracticeModeStatistics {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i11.PracticeModeEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, List<_i11.PracticeModeEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i11.PracticeModeEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2.Either<_i5.Failure, List<_i11.PracticeModeEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i11.PracticeModeEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i11.PracticeModeEntity>>>);
}

/// A class which mocks [GetMemoryStreak].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMemoryStreak extends _i1.Mock implements _i29.GetMemoryStreak {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>.value(
                _FakeEither_0<_i5.Failure, _i13.MemoryStreakEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>.value(
                _FakeEither_0<_i5.Failure, _i13.MemoryStreakEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>);
}

/// A class which mocks [UseStreakFreeze].
///
/// See the documentation for Mockito's code generation for more information.
class MockUseStreakFreeze extends _i1.Mock implements _i30.UseStreakFreeze {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>> call(
          {required DateTime? freezeDate}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#freezeDate: freezeDate},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>.value(
                _FakeEither_0<_i5.Failure, _i13.MemoryStreakEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {#freezeDate: freezeDate},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>.value(
                _FakeEither_0<_i5.Failure, _i13.MemoryStreakEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {#freezeDate: freezeDate},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i13.MemoryStreakEntity>>);
}

/// A class which mocks [GetMasteryProgress].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMasteryProgress extends _i1.Mock
    implements _i31.GetMasteryProgress {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>> call(
          {required String? verseId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#verseId: verseId},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>.value(
            _FakeEither_0<_i5.Failure, _i14.MasteryProgressEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {#verseId: verseId},
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>.value(
            _FakeEither_0<_i5.Failure, _i14.MasteryProgressEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {#verseId: verseId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>);
}

/// A class which mocks [UpdateMasteryLevel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateMasteryLevel extends _i1.Mock
    implements _i32.UpdateMasteryLevel {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>> call({
    required String? verseId,
    required _i14.MasteryLevel? newMasteryLevel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #verseId: verseId,
            #newMasteryLevel: newMasteryLevel,
          },
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>.value(
            _FakeEither_0<_i5.Failure, _i14.MasteryProgressEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #verseId: verseId,
              #newMasteryLevel: newMasteryLevel,
            },
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>.value(
            _FakeEither_0<_i5.Failure, _i14.MasteryProgressEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #verseId: verseId,
              #newMasteryLevel: newMasteryLevel,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i14.MasteryProgressEntity>>);
}

/// A class which mocks [GetDailyGoal].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDailyGoal extends _i1.Mock implements _i33.GetDailyGoal {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>);
}

/// A class which mocks [UpdateDailyGoalProgress].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateDailyGoalProgress extends _i1.Mock
    implements _i34.UpdateDailyGoalProgress {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>> call(
          {required bool? isNewVerse}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#isNewVerse: isNewVerse},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {#isNewVerse: isNewVerse},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {#isNewVerse: isNewVerse},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>);
}

/// A class which mocks [SetDailyGoalTargets].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetDailyGoalTargets extends _i1.Mock
    implements _i35.SetDailyGoalTargets {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>> call({
    required int? targetReviews,
    required int? targetNewVerses,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #targetReviews: targetReviews,
            #targetNewVerses: targetNewVerses,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #targetReviews: targetReviews,
              #targetNewVerses: targetNewVerses,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>.value(
                _FakeEither_0<_i5.Failure, _i15.DailyGoalEntity>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #targetReviews: targetReviews,
              #targetNewVerses: targetNewVerses,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i15.DailyGoalEntity>>);
}

/// A class which mocks [GetActiveChallenges].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetActiveChallenges extends _i1.Mock
    implements _i36.GetActiveChallenges {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<
      _i2
      .Either<_i5.Failure, List<_i16.MemoryChallengeEntity>>> call() => (super
              .noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i5.Failure, List<_i16.MemoryChallengeEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i16.MemoryChallengeEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2
                .Either<_i5.Failure, List<_i16.MemoryChallengeEntity>>>.value(
            _FakeEither_0<_i5.Failure, List<_i16.MemoryChallengeEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i16.MemoryChallengeEntity>>>);
}

/// A class which mocks [ClaimChallengeReward].
///
/// See the documentation for Mockito's code generation for more information.
class MockClaimChallengeReward extends _i1.Mock
    implements _i37.ClaimChallengeReward {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, (_i16.MemoryChallengeEntity, int)>> call(
          {required String? challengeId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#challengeId: challengeId},
        ),
        returnValue: _i4.Future<
                _i2
                .Either<_i5.Failure, (_i16.MemoryChallengeEntity, int)>>.value(
            _FakeEither_0<_i5.Failure, (_i16.MemoryChallengeEntity, int)>(
          this,
          Invocation.method(
            #call,
            [],
            {#challengeId: challengeId},
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2
                .Either<_i5.Failure, (_i16.MemoryChallengeEntity, int)>>.value(
            _FakeEither_0<_i5.Failure, (_i16.MemoryChallengeEntity, int)>(
          this,
          Invocation.method(
            #call,
            [],
            {#challengeId: challengeId},
          ),
        )),
      ) as _i4
          .Future<_i2.Either<_i5.Failure, (_i16.MemoryChallengeEntity, int)>>);
}

/// A class which mocks [GetMemoryChampionsLeaderboard].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMemoryChampionsLeaderboard extends _i1.Mock
    implements _i38.GetMemoryChampionsLeaderboard {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<
          _i2.Either<_i5.Failure,
              (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>>
      call(_i38.LeaderboardParams? params) => (super.noSuchMethod(
            Invocation.method(
              #call,
              [params],
            ),
            returnValue: _i4.Future<
                _i2.Either<
                    _i5.Failure,
                    (
                      List<_i17.MemoryChampionEntry>,
                      _i17.UserMemoryStats
                    )>>.value(_FakeEither_0<_i5.Failure,
                (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>(
              this,
              Invocation.method(
                #call,
                [params],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                _i2.Either<
                    _i5.Failure,
                    (
                      List<_i17.MemoryChampionEntry>,
                      _i17.UserMemoryStats
                    )>>.value(_FakeEither_0<_i5.Failure,
                (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>(
              this,
              Invocation.method(
                #call,
                [params],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure,
                  (List<_i17.MemoryChampionEntry>, _i17.UserMemoryStats)>>);
}

/// A class which mocks [GetMemoryStatistics].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMemoryStatistics extends _i1.Mock
    implements _i39.GetMemoryStatistics {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [GetSuggestedVerses].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSuggestedVerses extends _i1.Mock
    implements _i40.GetSuggestedVerses {
  @override
  _i3.MemoryVerseRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeMemoryVerseRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.MemoryVerseRepository);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i18.SuggestedVersesResponse>> call(
          {_i40.GetSuggestedVersesParams? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, _i18.SuggestedVersesResponse>>.value(
            _FakeEither_0<_i5.Failure, _i18.SuggestedVersesResponse>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2.Either<_i5.Failure, _i18.SuggestedVersesResponse>>.value(
            _FakeEither_0<_i5.Failure, _i18.SuggestedVersesResponse>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i18.SuggestedVersesResponse>>);
}

/// A class which mocks [MemoryVerseNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemoryVerseNotificationService extends _i1.Mock
    implements _i41.MemoryVerseNotificationService {
  @override
  _i4.Future<void> scheduleDailyPracticeReminder(
          {required int? dueVersesCount}) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleDailyPracticeReminder,
          [],
          {#dueVersesCount: dueVersesCount},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleStreakAtRiskNotification({
    required int? currentStreak,
    required bool? practicedToday,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleStreakAtRiskNotification,
          [],
          {
            #currentStreak: currentStreak,
            #practicedToday: practicedToday,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showDailyGoalAchievedNotification(
          {required int? xpEarned}) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDailyGoalAchievedNotification,
          [],
          {#xpEarned: xpEarned},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showMasteryLevelUpNotification({
    required String? verseReference,
    required String? masteryLevel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showMasteryLevelUpNotification,
          [],
          {
            #verseReference: verseReference,
            #masteryLevel: masteryLevel,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleMilestoneApproachingNotification({
    required int? milestoneDays,
    required DateTime? milestoneDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleMilestoneApproachingNotification,
          [],
          {
            #milestoneDays: milestoneDays,
            #milestoneDate: milestoneDate,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showChallengeCompletionNotification({
    required String? challengeName,
    required int? xpEarned,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showChallengeCompletionNotification,
          [],
          {
            #challengeName: challengeName,
            #xpEarned: xpEarned,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleNewChallengeNotification() => (super.noSuchMethod(
        Invocation.method(
          #scheduleNewChallengeNotification,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelStreakAtRiskNotification() => (super.noSuchMethod(
        Invocation.method(
          #cancelStreakAtRiskNotification,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [SuggestedVersesCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuggestedVersesCacheService extends _i1.Mock
    implements _i42.SuggestedVersesCacheService {
  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheVerses({
    required List<_i18.SuggestedVerseEntity>? verses,
    required List<_i18.SuggestedVerseCategory>? categories,
    required String? language,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheVerses,
          [],
          {
            #verses: verses,
            #categories: categories,
            #language: language,
            #category: category,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i42.CachedSuggestedVersesData?> getCachedVerses({
    required String? language,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedVerses,
          [],
          {
            #language: language,
            #category: category,
          },
        ),
        returnValue: _i4.Future<_i42.CachedSuggestedVersesData?>.value(),
        returnValueForMissingStub:
            _i4.Future<_i42.CachedSuggestedVersesData?>.value(),
      ) as _i4.Future<_i42.CachedSuggestedVersesData?>);

  @override
  _i4.Future<bool> isCacheValid({
    required String? language,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCacheValid,
          [],
          {
            #language: language,
            #category: category,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCacheForKey({
    required String? language,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCacheForKey,
          [],
          {
            #language: language,
            #category: category,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
        returnValueForMissingStub:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
