use crate::services::study_api::StudyGuideResult;

pub struct BlogContent {
    pub title: String,
    pub excerpt: String,
    pub content: String,
    pub tags: Vec<String>,
}

struct SectionLabels {
    historical_context: &'static str,
    scripture_passage: &'static str,
    interpretation: &'static str,
    reflection_questions: &'static str,
    prayer_points: &'static str,
    related_verses: &'static str,
    cta: &'static str,
}

fn labels_for(locale: &str) -> SectionLabels {
    match locale {
        "hi" => SectionLabels {
            historical_context:   "ऐतिहासिक संदर्भ",
            scripture_passage:    "पवित्रशास्त्र का अंश",
            interpretation:       "व्याख्या और अंतर्दृष्टि",
            reflection_questions: "चिंतन के प्रश्न",
            prayer_points:        "प्रार्थना के बिंदु",
            related_verses:       "संबंधित वचन",
            cta: "*यह अध्ययन मार्गदर्शिका Disciplefy द्वारा तैयार की गई है। पूर्ण इंटरैक्टिव अनुभव के लिए [ऐप डाउनलोड करें](https://app.disciplefy.in) — अभ्यास मोड, ऑडियो और बहुत कुछ।*",
        },
        "ml" => SectionLabels {
            historical_context:   "ചരിത്രപരമായ പശ്ചാത്തലം",
            scripture_passage:    "തിരുവചന ഭാഗം",
            interpretation:       "വ്യാഖ്യാനവും ഉൾക്കാഴ്ചകളും",
            reflection_questions: "ധ്യാന ചോദ്യങ്ങൾ",
            prayer_points:        "പ്രാർത്ഥനാ വിഷയങ്ങൾ",
            related_verses:       "ബന്ധപ്പെട്ട വചനങ്ങൾ",
            cta: "*ഈ പഠന ഗൈഡ് Disciplefy നിർമ്മിച്ചതാണ്. [ആപ്പ് ഡൗൺലോഡ് ചെയ്യൂ](https://app.disciplefy.in) — പ്രാക്ടീസ് മോഡ്, ഓഡിയോ, കൂടുതൽ സവിശേഷതകൾ.*",
        },
        _ => SectionLabels {
            historical_context:   "Historical Context",
            scripture_passage:    "Scripture Passage",
            interpretation:       "Interpretation & Insights",
            reflection_questions: "Reflection Questions",
            prayer_points:        "Prayer Points",
            related_verses:       "Related Verses",
            cta: "*This study guide was generated by Disciplefy. [Download the app](https://app.disciplefy.in) for the full interactive experience with practice modes, audio, and more.*",
        },
    }
}

/// Transform study guide sections into a blog-formatted markdown post.
pub fn format_blog_post(
    topic_title: &str,
    guide: &StudyGuideResult,
    category: &str,
    disciple_level: &str,
    locale: &str,
) -> BlogContent {
    let l = labels_for(locale);
    let mut md = String::new();

    // Summary
    if let Some(summary) = guide.sections.get("summary") {
        md.push_str(summary);
        md.push_str("\n\n");
    }

    // Historical Context
    if let Some(context) = guide.sections.get("context") {
        md.push_str(&format!("## {}\n\n", l.historical_context));
        md.push_str(context);
        md.push_str("\n\n");
    }

    // Scripture Passage
    if let Some(passage) = guide.sections.get("passage") {
        md.push_str(&format!("## {}\n\n", l.scripture_passage));
        md.push_str(passage);
        md.push_str("\n\n");
    }

    // Interpretation
    if let Some(interp) = guide.sections.get("interpretation") {
        md.push_str(&format!("## {}\n\n", l.interpretation));
        md.push_str(interp);
        md.push_str("\n\n");
    }

    // Interpretation Insights (bullet list — no heading, follows interpretation)
    if let Some(insights) = guide.sections.get("interpretationInsights") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(insights) {
            if items.len() == 1 {
                md.push_str(&items[0]);
                md.push_str("\n\n");
            } else if items.len() > 1 {
                for item in &items {
                    md.push_str(&format!("- {}\n", item));
                }
                md.push('\n');
            }
        }
    }

    // Reflection Questions (numbered list)
    if let Some(questions) = guide.sections.get("reflectionQuestions") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(questions) {
            if !items.is_empty() {
                md.push_str(&format!("## {}\n\n", l.reflection_questions));
                if items.len() == 1 {
                    md.push_str(&items[0]);
                    md.push_str("\n\n");
                } else {
                    for (i, q) in items.iter().enumerate() {
                        md.push_str(&format!("{}. {}\n", i + 1, q));
                    }
                    md.push('\n');
                }
            }
        }
    }

    // Prayer Points (bullet list)
    if let Some(prayers) = guide.sections.get("prayerPoints") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(prayers) {
            if !items.is_empty() {
                md.push_str(&format!("## {}\n\n", l.prayer_points));
                if items.len() == 1 {
                    md.push_str(&items[0]);
                    md.push_str("\n\n");
                } else {
                    for item in &items {
                        md.push_str(&format!("- {}\n", item));
                    }
                    md.push('\n');
                }
            }
        }
    }

    // Related Verses
    if let Some(verses) = guide.sections.get("relatedVerses") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(verses) {
            if !items.is_empty() {
                md.push_str(&format!("## {}\n\n", l.related_verses));
                if items.len() == 1 {
                    md.push_str(&items[0]);
                    md.push_str("\n\n");
                } else {
                    for item in &items {
                        md.push_str(&format!("- {}\n", item));
                    }
                    md.push('\n');
                }
            }
        } else if let Ok(items) = serde_json::from_str::<Vec<serde_json::Value>>(verses) {
            if !items.is_empty() {
                md.push_str(&format!("## {}\n\n", l.related_verses));
                if items.len() == 1 {
                    if let (Some(reference), Some(text)) = (
                        items[0].get("reference").and_then(|v| v.as_str()),
                        items[0].get("text").and_then(|v| v.as_str()),
                    ) {
                        md.push_str(&format!("**{}** — {}\n\n", reference, text));
                    }
                } else {
                    for item in &items {
                        if let (Some(reference), Some(text)) = (
                            item.get("reference").and_then(|v| v.as_str()),
                            item.get("text").and_then(|v| v.as_str()),
                        ) {
                            md.push_str(&format!("- **{}** — {}\n", reference, text));
                        }
                    }
                    md.push('\n');
                }
            }
        }
    }

    // CTA footer
    md.push_str("---\n\n");
    md.push_str(l.cta);
    md.push('\n');

    // Excerpt: first ~160 chars of summary, trimmed to last sentence boundary
    let excerpt = guide
        .sections
        .get("summary")
        .map(|s| {
            let trimmed = if s.chars().count() > 160 {
                let byte_end = s.char_indices().nth(160).map(|(i, _)| i).unwrap_or(s.len());
                let cut = &s[..byte_end];
                if let Some(pos) = cut.rfind(". ") {
                    &cut[..=pos]
                } else if let Some(pos) = cut.rfind('.') {
                    &cut[..=pos]
                } else {
                    cut
                }
            } else {
                s.as_str()
            };
            trimmed.trim().to_string()
        })
        .unwrap_or_default();

    // Tags from category + disciple_level
    let mut tags = vec!["bible-study".to_string()];
    if !category.is_empty() {
        tags.push(slug::slugify(category));
    }
    if !disciple_level.is_empty() {
        tags.push(slug::slugify(disciple_level));
    }

    BlogContent {
        title: topic_title.to_string(),
        excerpt,
        content: md,
        tags,
    }
}
