use crate::services::study_api::StudyGuideResult;

pub struct BlogContent {
    pub title: String,
    pub excerpt: String,
    pub content: String,
    pub tags: Vec<String>,
}

/// Transform study guide sections into a blog-formatted markdown post.
pub fn format_blog_post(
    topic_title: &str,
    guide: &StudyGuideResult,
    category: &str,
    disciple_level: &str,
) -> BlogContent {
    let mut md = String::new();

    // Summary
    if let Some(summary) = guide.sections.get("summary") {
        md.push_str(summary);
        md.push_str("\n\n");
    }

    // Historical Context
    if let Some(context) = guide.sections.get("context") {
        md.push_str("## Historical Context\n\n");
        md.push_str(context);
        md.push_str("\n\n");
    }

    // Scripture Passage
    if let Some(passage) = guide.sections.get("passage") {
        md.push_str("## Scripture Passage\n\n");
        md.push_str(passage);
        md.push_str("\n\n");
    }

    // Interpretation
    if let Some(interp) = guide.sections.get("interpretation") {
        md.push_str("## Interpretation & Insights\n\n");
        md.push_str(interp);
        md.push_str("\n\n");
    }

    // Interpretation Insights (bullet list)
    if let Some(insights) = guide.sections.get("interpretationInsights") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(insights) {
            if !items.is_empty() {
                for item in &items {
                    md.push_str(&format!("- {}\n", item));
                }
                md.push('\n');
            }
        }
    }

    // Reflection Questions (numbered list)
    if let Some(questions) = guide.sections.get("reflectionQuestions") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(questions) {
            if !items.is_empty() {
                md.push_str("## Reflection Questions\n\n");
                for (i, q) in items.iter().enumerate() {
                    md.push_str(&format!("{}. {}\n", i + 1, q));
                }
                md.push('\n');
            }
        }
    }

    // Prayer Points (bullet list)
    if let Some(prayers) = guide.sections.get("prayerPoints") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(prayers) {
            if !items.is_empty() {
                md.push_str("## Prayer Points\n\n");
                for item in &items {
                    md.push_str(&format!("- {}\n", item));
                }
                md.push('\n');
            }
        }
    }

    // Related Verses
    if let Some(verses) = guide.sections.get("relatedVerses") {
        // relatedVerses can be array of strings or array of {reference, text}
        if let Ok(items) = serde_json::from_str::<Vec<String>>(verses) {
            if !items.is_empty() {
                md.push_str("## Related Verses\n\n");
                for item in &items {
                    md.push_str(&format!("- {}\n", item));
                }
                md.push('\n');
            }
        } else if let Ok(items) = serde_json::from_str::<Vec<serde_json::Value>>(verses) {
            if !items.is_empty() {
                md.push_str("## Related Verses\n\n");
                for item in &items {
                    if let (Some(reference), Some(text)) =
                        (item.get("reference").and_then(|v| v.as_str()),
                         item.get("text").and_then(|v| v.as_str()))
                    {
                        md.push_str(&format!("- **{}** — {}\n", reference, text));
                    }
                }
                md.push('\n');
            }
        }
    }

    // CTA footer
    md.push_str("---\n\n");
    md.push_str("*This study guide was generated by Disciplefy. [Download the app](https://app.disciplefy.in) for the full interactive experience with practice modes, audio, and more.*\n");

    // Excerpt: first ~160 chars of summary, trimmed to last sentence boundary
    let excerpt = guide
        .sections
        .get("summary")
        .map(|s| {
            let trimmed = if s.chars().count() > 160 {
                // Find the byte index of the 160th char boundary
                let byte_end = s.char_indices().nth(160).map(|(i, _)| i).unwrap_or(s.len());
                let cut = &s[..byte_end];
                // Find last sentence boundary
                if let Some(pos) = cut.rfind(". ") {
                    &cut[..=pos]
                } else if let Some(pos) = cut.rfind('.') {
                    &cut[..=pos]
                } else {
                    cut
                }
            } else {
                s.as_str()
            };
            trimmed.trim().to_string()
        })
        .unwrap_or_default();

    // Tags from category + disciple_level
    let mut tags = vec!["bible-study".to_string()];
    if !category.is_empty() {
        tags.push(slug::slugify(category));
    }
    if !disciple_level.is_empty() {
        tags.push(slug::slugify(disciple_level));
    }

    BlogContent {
        title: topic_title.to_string(),
        excerpt,
        content: md,
        tags,
    }
}
