use crate::services::study_api::StudyGuideResult;

pub struct BlogContent {
    pub title: String,
    pub excerpt: String,
    pub content: String,
    pub tags: Vec<String>,
}

struct SectionLabels {
    historical_context: &'static str,
    scripture_passage: &'static str,
    interpretation: &'static str,
    reflection_questions: &'static str,
    prayer_points: &'static str,
    related_verses: &'static str,
    cta: &'static str,
}

fn labels_for(locale: &str) -> SectionLabels {
    match locale {
        "hi" => SectionLabels {
            historical_context:   "ऐतिहासिक संदर्भ",
            scripture_passage:    "पवित्रशास्त्र का अंश",
            interpretation:       "व्याख्या और अंतर्दृष्टि",
            reflection_questions: "चिंतन के प्रश्न",
            prayer_points:        "प्रार्थना के बिंदु",
            related_verses:       "संबंधित वचन",
            cta: "*यह अध्ययन मार्गदर्शिका Disciplefy द्वारा तैयार की गई है। पूर्ण इंटरैक्टिव अनुभव के लिए [ऐप डाउनलोड करें](https://links.disciplefy.in) — अभ्यास मोड, ऑडियो और बहुत कुछ।*",
        },
        "ml" => SectionLabels {
            historical_context:   "ചരിത്രപരമായ പശ്ചാത്തലം",
            scripture_passage:    "തിരുവചന ഭാഗം",
            interpretation:       "വ്യാഖ്യാനവും ഉൾക്കാഴ്ചകളും",
            reflection_questions: "ധ്യാന ചോദ്യങ്ങൾ",
            prayer_points:        "പ്രാർത്ഥനാ വിഷയങ്ങൾ",
            related_verses:       "ബന്ധപ്പെട്ട വചനങ്ങൾ",
            cta: "*ഈ പഠന ഗൈഡ് Disciplefy നിർമ്മിച്ചതാണ്. [ആപ്പ് ഡൗൺലോഡ് ചെയ്യൂ](https://links.disciplefy.in) — പ്രാക്ടീസ് മോഡ്, ഓഡിയോ, കൂടുതൽ സവിശേഷതകൾ.*",
        },
        _ => SectionLabels {
            historical_context:   "Historical Context",
            scripture_passage:    "Scripture Passage",
            interpretation:       "Interpretation & Insights",
            reflection_questions: "Reflection Questions",
            prayer_points:        "Prayer Points",
            related_verses:       "Related Verses",
            cta: "*This study guide was generated by Disciplefy. [Download the app](https://links.disciplefy.in) for the full interactive experience with practice modes, audio, and more.*",
        },
    }
}

/// Transform study guide sections into a blog-formatted markdown post.
pub fn format_blog_post(
    topic_title: &str,
    guide: &StudyGuideResult,
    category: &str,
    disciple_level: &str,
    locale: &str,
) -> BlogContent {
    let l = labels_for(locale);
    let mut md = String::new();

    // Summary
    if let Some(summary) = guide.sections.get("summary") {
        md.push_str(summary);
        md.push_str("\n\n");
    }

    // Historical Context
    if let Some(context) = guide.sections.get("context") {
        md.push_str(&format!("## {}\n\n", l.historical_context));
        md.push_str(context);
        md.push_str("\n\n");
    }

    // Scripture Passage
    if let Some(passage) = guide.sections.get("passage") {
        md.push_str(&format!("## {}\n\n", l.scripture_passage));
        md.push_str(passage);
        md.push_str("\n\n");
    }

    // Interpretation
    if let Some(interp) = guide.sections.get("interpretation") {
        md.push_str(&format!("## {}\n\n", l.interpretation));
        md.push_str(interp);
        md.push_str("\n\n");
    }

    // Interpretation Insights (bullet list — no heading, follows interpretation)
    if let Some(insights) = guide.sections.get("interpretationInsights") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(insights) {
            if items.len() == 1 {
                md.push_str(&items[0]);
                md.push_str("\n\n");
            } else if items.len() > 1 {
                for item in &items {
                    md.push_str(&format!("- {}\n", item));
                }
                md.push('\n');
            }
        }
    }

    // Reflection Questions (numbered list)
    if let Some(questions) = guide.sections.get("reflectionQuestions") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(questions) {
            if !items.is_empty() {
                md.push_str(&format!("## {}\n\n", l.reflection_questions));
                if items.len() == 1 {
                    md.push_str(&items[0]);
                    md.push_str("\n\n");
                } else {
                    for (i, q) in items.iter().enumerate() {
                        md.push_str(&format!("{}. {}\n", i + 1, q));
                    }
                    md.push('\n');
                }
            }
        }
    }

    // Prayer Points (bullet list)
    if let Some(prayers) = guide.sections.get("prayerPoints") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(prayers) {
            if !items.is_empty() {
                md.push_str(&format!("## {}\n\n", l.prayer_points));
                if items.len() == 1 {
                    md.push_str(&items[0]);
                    md.push_str("\n\n");
                } else {
                    for item in &items {
                        md.push_str(&format!("- {}\n", item));
                    }
                    md.push('\n');
                }
            }
        }
    }

    // Related Verses
    if let Some(verses) = guide.sections.get("relatedVerses") {
        if let Ok(items) = serde_json::from_str::<Vec<String>>(verses) {
            if !items.is_empty() {
                md.push_str(&format!("## {}\n\n", l.related_verses));
                if items.len() == 1 {
                    md.push_str(&items[0]);
                    md.push_str("\n\n");
                } else {
                    for item in &items {
                        md.push_str(&format!("- {}\n", item));
                    }
                    md.push('\n');
                }
            }
        } else if let Ok(items) = serde_json::from_str::<Vec<serde_json::Value>>(verses) {
            if !items.is_empty() {
                md.push_str(&format!("## {}\n\n", l.related_verses));
                if items.len() == 1 {
                    if let (Some(reference), Some(text)) = (
                        items[0].get("reference").and_then(|v| v.as_str()),
                        items[0].get("text").and_then(|v| v.as_str()),
                    ) {
                        md.push_str(&format!("**{}** — {}\n\n", reference, text));
                    }
                } else {
                    for item in &items {
                        if let (Some(reference), Some(text)) = (
                            item.get("reference").and_then(|v| v.as_str()),
                            item.get("text").and_then(|v| v.as_str()),
                        ) {
                            md.push_str(&format!("- **{}** — {}\n", reference, text));
                        }
                    }
                    md.push('\n');
                }
            }
        }
    }

    // CTA footer
    md.push_str("---\n\n");
    md.push_str(l.cta);
    md.push('\n');

    // Excerpt: first ~160 chars of summary, trimmed to last sentence boundary
    let excerpt = guide
        .sections
        .get("summary")
        .map(|s| {
            let trimmed = if s.chars().count() > 160 {
                let byte_end = s.char_indices().nth(160).map(|(i, _)| i).unwrap_or(s.len());
                let cut = &s[..byte_end];
                if let Some(pos) = cut.rfind(". ") {
                    &cut[..=pos]
                } else if let Some(pos) = cut.rfind('.') {
                    &cut[..=pos]
                } else {
                    cut
                }
            } else {
                s.as_str()
            };
            trimmed.trim().to_string()
        })
        .unwrap_or_default();

    // Tags from category + disciple_level
    let mut tags = vec!["bible-study".to_string()];
    if !category.is_empty() {
        tags.push(slug::slugify(category));
    }
    if !disciple_level.is_empty() {
        tags.push(slug::slugify(disciple_level));
    }

    BlogContent {
        title: topic_title.to_string(),
        excerpt,
        content: md,
        tags,
    }
}

#[allow(dead_code)]
pub struct DailyPostContent {
    pub content: String,
    pub question: Option<String>,
    pub verse: Option<String>,
}

fn first_sentences(text: &str, n: usize) -> String {
    let mut out = String::new();
    let mut count = 0;
    for piece in text.split_inclusive(['.', '।', '?', '!']) {
        out.push_str(piece);
        count += 1;
        if count == n {
            break;
        }
    }
    out.trim().to_string()
}

fn open_study_label(locale: &str) -> &'static str {
    match locale {
        "hi" => "पूरा अध्ययन खोलें →",
        "ml" => "മുഴുവൻ പഠനം തുറക്കുക →",
        _ => "Open the full study →",
    }
}

/// Plain-text daily post body for fellowship feeds (no markdown headings).
pub fn format_daily_post(
    topic_title: &str,
    guide: &StudyGuideResult,
    locale: &str,
) -> DailyPostContent {
    let summary = guide
        .sections
        .get("summary")
        .map(|s| first_sentences(s, 2))
        .unwrap_or_default();

    let question = guide
        .sections
        .get("reflectionQuestions")
        .and_then(|raw| serde_json::from_str::<Vec<String>>(raw).ok())
        .and_then(|v| v.into_iter().next())
        .map(|q| q.trim().to_string())
        .filter(|q| !q.is_empty());

    let verse = guide
        .sections
        .get("relatedVerses")
        .and_then(|raw| {
            if let Ok(v) = serde_json::from_str::<Vec<String>>(raw) {
                return v.into_iter().next();
            }
            serde_json::from_str::<Vec<serde_json::Value>>(raw)
                .ok()
                .and_then(|v| v.into_iter().next())
                .and_then(|o| {
                    o.get("reference")
                        .and_then(|r| r.as_str())
                        .map(String::from)
                })
        })
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());

    let mut content = format!("📖 {}\n\n{}", topic_title.trim(), summary);
    if let Some(v) = &verse {
        content.push_str(&format!("\n\n✝️ {}", v));
    }
    if let Some(q) = &question {
        content.push_str(&format!("\n\n💬 {}", q));
    }
    content.push_str(&format!("\n\n{}", open_study_label(locale)));

    let content: String = content.chars().take(1900).collect();
    DailyPostContent {
        content,
        question,
        verse,
    }
}

#[cfg(test)]
mod daily_tests {
    use super::*;
    use std::collections::HashMap;

    fn guide() -> StudyGuideResult {
        let mut s = HashMap::new();
        s.insert("summary".into(), "Paul reminds the Corinthians that trust outlasts sight. Faith is sight fixed on the eternal. A third sentence.".into());
        s.insert(
            "reflectionQuestions".into(),
            "[\"When has faith carried you past what you could see?\",\"Second?\"]".into(),
        );
        s.insert(
            "relatedVerses".into(),
            "[{\"reference\":\"2 Corinthians 5:7\",\"text\":\"For we walk by faith\"}]".into(),
        );
        StudyGuideResult {
            sections: s,
            study_guide_id: None,
            from_cache: false,
        }
    }

    #[test]
    fn builds_english_daily_post() {
        let d = format_daily_post("Walking by Faith", &guide(), "en");
        assert!(d.content.starts_with("📖 Walking by Faith\n\n"));
        assert!(d.content.contains(
            "Paul reminds the Corinthians that trust outlasts sight. Faith is sight fixed on the eternal."
        ));
        assert!(!d.content.contains("A third sentence"));
        assert_eq!(d.verse.as_deref(), Some("2 Corinthians 5:7"));
        assert_eq!(
            d.question.as_deref(),
            Some("When has faith carried you past what you could see?")
        );
        assert!(d.content.ends_with("Open the full study →"));
    }

    #[test]
    fn falls_back_when_sections_missing() {
        let g = StudyGuideResult {
            sections: HashMap::from([("summary".to_string(), "Only one.".to_string())]),
            study_guide_id: None,
            from_cache: false,
        };
        let d = format_daily_post("T", &g, "ml");
        assert_eq!(d.verse, None);
        assert_eq!(d.question, None);
        assert!(d.content.contains("Only one."));
        assert!(d.content.ends_with("മുഴുവൻ പഠനം തുറക്കുക →"));
    }

    #[test]
    fn related_verses_as_plain_strings() {
        let g = StudyGuideResult {
            sections: HashMap::from([
                ("summary".to_string(), "S.".to_string()),
                ("relatedVerses".to_string(), "[\"John 3:16\"]".to_string()),
            ]),
            study_guide_id: None,
            from_cache: false,
        };
        assert_eq!(
            format_daily_post("T", &g, "hi").verse.as_deref(),
            Some("John 3:16")
        );
    }
}
