// Mocks generated by Mockito 5.4.5 from annotations
// in disciplefy_bible_study/test/features/study_topics/learning_path_download_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:disciplefy_bible_study/core/error/failures.dart' as _i5;
import 'package:disciplefy_bible_study/features/study_generation/data/datasources/study_local_data_source.dart'
    as _i7;
import 'package:disciplefy_bible_study/features/study_generation/domain/entities/study_guide.dart'
    as _i6;
import 'package:disciplefy_bible_study/features/study_generation/domain/usecases/generate_study_guide.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GenerateStudyGuide].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateStudyGuide extends _i1.Mock
    implements _i3.GenerateStudyGuide {
  MockGenerateStudyGuide() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.StudyGuide>> call(
          _i3.StudyGenerationParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.StudyGuide>>.value(
            _FakeEither_0<_i5.Failure, _i6.StudyGuide>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.StudyGuide>>);
}

/// A class which mocks [StudyLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudyLocalDataSource extends _i1.Mock
    implements _i7.StudyLocalDataSource {
  MockStudyLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i6.StudyGuide>> getCachedStudyGuides() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedStudyGuides,
          [],
        ),
        returnValue: _i4.Future<List<_i6.StudyGuide>>.value(<_i6.StudyGuide>[]),
      ) as _i4.Future<List<_i6.StudyGuide>>);

  @override
  _i4.Future<bool> cacheStudyGuide(_i6.StudyGuide? studyGuide) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheStudyGuide,
          [studyGuide],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteStudyGuide(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteStudyGuide,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
