// ============================================================================
// Send Recommended Topic Notification Edge Function
// ============================================================================
// Sends recommended Bible study topic push notifications to all eligible users
// Triggered by GitHub Actions workflow at 8 AM across different timezones

import { createSimpleFunction } from '../_shared/core/function-factory.ts'
import { ServiceContainer } from '../_shared/core/services.ts'
import { FCMService, logNotification } from '../_shared/fcm-service.ts'
import {
  selectNotificationForUser,
  recordContinueLearningReminder,
} from '../_shared/unified-notification-selector.ts'
import {
  createNotificationHelper,
  NotificationUser,
} from '../_shared/services/notification-helper-service.ts'
import { AppError } from '../_shared/utils/error-handler.ts'
import { isWithinDeliveryWindow, DEDUP_LOOKBACK_HOURS } from '../_shared/utils/notification-window.ts'
import { fetchAllRows } from '../_shared/utils/supabase-paginate.ts'

// ============================================================================
// Types
// ============================================================================

interface RecommendedTopicUser extends NotificationUser {
  readonly timezone_offset_minutes: number
}

// ============================================================================
// Note: Notification titles and bodies are now generated by unified-notification-selector
// to support both "Continue Learning" and "For You" notification types
// ============================================================================

// ============================================================================
// Helper Functions
// ============================================================================

/** Intended local delivery time: 8 AM. */
const TARGET_LOCAL_MINUTES = 8 * 60

async function getAllUserTokens(
  supabase: ServiceContainer['supabaseServiceClient']
): Promise<Array<{ user_id: string; fcm_token: string }>> {
  return await fetchAllRows<{ user_id: string; fcm_token: string }>(
    (from, to) =>
      supabase
        .from('user_notification_tokens')
        .select('user_id, fcm_token')
        .order('user_id', { ascending: true })
        .range(from, to)
  ).catch((error: Error) => {
    throw new AppError('DATABASE_ERROR', `Failed to fetch tokens: ${error.message}`, 500)
  })
}

async function fetchEnabledPreferences(
  supabase: ServiceContainer['supabaseServiceClient']
): Promise<Array<{ user_id: string; timezone_offset_minutes: number }>> {
  return await fetchAllRows<{ user_id: string; timezone_offset_minutes: number }>(
    (from, to) =>
      supabase
        .from('user_notification_preferences')
        .select('user_id, timezone_offset_minutes, recommended_topic_enabled')
        .eq('recommended_topic_enabled', true)
        .order('user_id', { ascending: true })
        .range(from, to)
  ).catch((error: Error) => {
    throw new AppError('DATABASE_ERROR', `Failed to fetch preferences: ${error.message}`, 500)
  })
}

function enrichUsersWithTimezone(
  tokens: Array<{ user_id: string; fcm_token: string }>,
  preferences: Array<{ user_id: string; timezone_offset_minutes: number }>,
  now: Date
): RecommendedTopicUser[] {
  const prefsMap = new Map(preferences.map(p => [p.user_id, p]))
  return tokens
    .filter(t => prefsMap.has(t.user_id))
    .map(t => ({
      user_id: t.user_id,
      fcm_token: t.fcm_token,
      timezone_offset_minutes: prefsMap.get(t.user_id)!.timezone_offset_minutes
    }))
    .filter(u => isWithinDeliveryWindow(u.timezone_offset_minutes, TARGET_LOCAL_MINUTES, undefined, now))
}

/**
 * Fetches users whose local time has reached the 8 AM target and who have
 * recommended topic notifications enabled.
 *
 * Evaluated as a forward-looking catch-up window rather than a single exact UTC
 * hour, so a dropped or delayed cron is picked up by a later run instead of
 * skipping that timezone for the day. Per-day dedup prevents repeat sends.
 *
 * @param supabase - Supabase service client for database operations
 * @param now - Instant to evaluate the delivery window against
 * @returns Array of users with FCM tokens and timezone offsets
 */
async function fetchEligibleUsersWithTimezone(
  supabase: ServiceContainer['supabaseServiceClient'],
  now: Date
): Promise<RecommendedTopicUser[]> {
  const tokens = await getAllUserTokens(supabase)
  const preferences = await fetchEnabledPreferences(supabase)
  return enrichUsersWithTimezone(tokens, preferences, now)
}

async function computeUsersToNotify(
  notificationHelper: ReturnType<typeof createNotificationHelper>,
  authenticatedUsers: RecommendedTopicUser[]
): Promise<RecommendedTopicUser[]> {
  const userIds = authenticatedUsers.map(u => u.user_id)
  const [alreadySentRecommended, alreadySentContinue] = await Promise.all([
    notificationHelper.getAlreadySentUserIds(userIds, 'recommended_topic', DEDUP_LOOKBACK_HOURS),
    notificationHelper.getAlreadySentUserIds(userIds, 'continue_learning', DEDUP_LOOKBACK_HOURS),
  ])
  const alreadySentUserIds = new Set([...alreadySentRecommended, ...alreadySentContinue])
  const deduped = authenticatedUsers.filter(u => !alreadySentUserIds.has(u.user_id))

  // Space out categories — a user notified by another category within the last
  // hour is deferred to a later run, still inside this window.
  return await notificationHelper.excludeRecentlyNotified(deduped)
}

function buildNotificationData(
  notification: { type: string; topicId: string; topicTitle: string; topicDescription: string; guideId?: string; timeSpent?: number; pathId?: string },
  language: string
): Record<string, string> {
  const data: Record<string, string> = {
    type: notification.type,
    topic_id: notification.topicId,
    topic_title: notification.topicTitle,
    topic_description: notification.topicDescription,
    language,
  }

  if (notification.type === 'continue_learning' && notification.guideId) {
    data.guide_id = notification.guideId
    data.time_spent = notification.timeSpent?.toString() || '0'
    // Lets the app open the topic's learning path on tap; it cannot open the
    // guide itself, as the study guide route has no fetch-by-id path.
    if (notification.pathId) {
      data.path_id = notification.pathId
    }
  }

  return data
}

async function sendSingleNotification(
  user: RecommendedTopicUser,
  language: string,
  fcmService: FCMService,
  supabaseUrl: string,
  serviceRoleKey: string
): Promise<{ success: boolean; topicSelectionFailed?: boolean; topicId?: string; notificationType?: string }> {
  try {
    const notificationResult = await selectNotificationForUser(supabaseUrl, serviceRoleKey, user.user_id, language)

    if (!notificationResult.success || !notificationResult.notification) {
      console.error(`[RecommendedTopic] Notification selection failed for user ${user.user_id}:`, notificationResult.error)
      return { success: false, topicSelectionFailed: true }
    }

    const notification = notificationResult.notification
    const notificationData = buildNotificationData(notification, language)

    const result = await fcmService.sendNotification({
      token: user.fcm_token,
      notification: { title: notification.title, body: notification.body },
      data: notificationData,
      android: { priority: 'high' },
      apns: {
        headers: { 'apns-priority': '10' },
        payload: { aps: { sound: 'default', badge: 1 } },
      },
    })

    // Record the reminder so this guide's repeat cap advances and the next run
    // rotates to a different one. Only on success — a failed send shouldn't
    // burn one of the guide's limited reminders.
    if (result.success && notification.type === 'continue_learning' && notification.guideId) {
      await recordContinueLearningReminder(supabaseUrl, serviceRoleKey, notification.guideId)
    }

    await logNotification(supabaseUrl, serviceRoleKey, {
      userId: user.user_id,
      notificationType: notification.type === 'continue_learning' ? 'continue_learning' : 'recommended_topic',
      title: notification.title,
      body: notification.body,
      topicId: notification.topicId || undefined,
      language,
      deliveryStatus: result.success ? 'sent' : 'failed',
      fcmMessageId: result.messageId,
      errorMessage: result.error,
    })

    return { success: result.success, topicId: notification.topicId, notificationType: notification.type }
  } catch (error) {
    console.error(`[RecommendedTopic] Error for user ${user.user_id}:`, error)
    return { success: false }
  }
}

interface NotificationStats {
  successCount: number
  failureCount: number
  topicSelectionFailures: number
  uniqueTopicIds: Set<string>
  continueLearningCount: number
  forYouCount: number
}

async function sendNotificationBatch(
  users: RecommendedTopicUser[],
  languageMap: Map<string, string>,
  fcmService: FCMService,
  supabaseUrl: string,
  serviceRoleKey: string
): Promise<NotificationStats> {
  const stats: NotificationStats = {
    successCount: 0,
    failureCount: 0,
    topicSelectionFailures: 0,
    uniqueTopicIds: new Set<string>(),
    continueLearningCount: 0,
    forYouCount: 0,
  }

  const BATCH_SIZE = 10

  for (let i = 0; i < users.length; i += BATCH_SIZE) {
    const batch = users.slice(i, i + BATCH_SIZE)
    const results = await Promise.allSettled(
      batch.map(user => sendSingleNotification(user, languageMap.get(user.user_id) || 'en', fcmService, supabaseUrl, serviceRoleKey))
    )

    results.forEach(result => {
      if (result.status === 'fulfilled') {
        const value = result.value
        if (value.topicSelectionFailed) {
          stats.topicSelectionFailures++
          stats.failureCount++
        } else if (value.success) {
          stats.successCount++
          if (value.topicId) stats.uniqueTopicIds.add(value.topicId)
          if (value.notificationType === 'continue_learning') stats.continueLearningCount++
          else if (value.notificationType === 'for_you') stats.forYouCount++
        } else {
          stats.failureCount++
        }
      } else {
        stats.failureCount++
      }
    })

    console.log(`[RecommendedTopic] Batch ${Math.floor(i / BATCH_SIZE) + 1} complete: ${stats.successCount} sent, ${stats.failureCount} failed`)
  }

  return stats
}

async function prepareUserNotifications(
  supabase: ServiceContainer['supabaseServiceClient'],
  notificationHelper: ReturnType<typeof createNotificationHelper>,
  now: Date
): Promise<{ usersToNotify: RecommendedTopicUser[]; languageMap: Map<string, string> } | Response> {
  const allUsers = await fetchEligibleUsersWithTimezone(supabase, now)
  if (allUsers.length === 0) return notificationHelper.createSuccessResponse('No eligible users', { sentCount: 0 })
  console.log(`[RecommendedTopic] Found ${allUsers.length} users with tokens`)

  const authenticatedUsers = await notificationHelper.filterAnonymousUsers(supabase, allUsers)
  if (authenticatedUsers.length === 0) return notificationHelper.createSuccessResponse('No authenticated users eligible', { sentCount: 0 })

  const usersToNotify = await computeUsersToNotify(notificationHelper, authenticatedUsers)
  console.log(`[RecommendedTopic] ${usersToNotify.length} users need notification`)
  if (usersToNotify.length === 0) return notificationHelper.createSuccessResponse('All users already received notification today', { sentCount: 0 })

  const languageMap = await notificationHelper.getUserLanguagePreferences(supabase, usersToNotify.map(u => u.user_id))
  return { usersToNotify, languageMap }
}

function isResponse(value: unknown): value is Response {
  return value instanceof Response
}

// ============================================================================
// Main Handler
// ============================================================================

/**
 * Handles sending recommended topic push notifications to eligible users at 8 AM in their timezone.
 * Uses unified notification selector to send either "Continue Learning" or "For You" notifications.
 *
 * @param req - HTTP request with cron secret for authentication
 * @param services - Service container with Supabase client and dependencies
 * @returns Response with notification statistics (success/failure counts, notification types)
 */
async function handleRecommendedTopicNotification(req: Request, services: ServiceContainer): Promise<Response> {
  const notificationHelper = createNotificationHelper()
  notificationHelper.verifyCronSecret(req)
  console.log('[RecommendedTopic] Starting notification process...')

  const now = new Date()
  console.log(`[RecommendedTopic] UTC time: ${now.toISOString()}, target: 08:00 local (+ catch-up window)`)

  const result = await prepareUserNotifications(services.supabaseServiceClient, notificationHelper, now)
  if (isResponse(result)) return result

  const { usersToNotify, languageMap } = result
  const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
  const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  const stats = await sendNotificationBatch(usersToNotify, languageMap, new FCMService(), SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

  console.log(`[RecommendedTopic] Complete: ${stats.successCount} sent (${stats.continueLearningCount} Continue, ${stats.forYouCount} ForYou)`)

  return notificationHelper.createSuccessResponse('Unified notifications sent (Continue Learning + For You)', {
    totalEligible: usersToNotify.length,
    successCount: stats.successCount,
    failureCount: stats.failureCount,
    topicSelectionFailures: stats.topicSelectionFailures,
    uniqueTopicsSent: stats.uniqueTopicIds.size,
    continueLearningCount: stats.continueLearningCount,
    forYouCount: stats.forYouCount,
  })
}

// ============================================================================
// Start Server
// ============================================================================

createSimpleFunction(handleRecommendedTopicNotification, {
  allowedMethods: ['POST'],
  enableAnalytics: false,
})
