name: Flutter CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test Flutter App
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      working-directory: ./frontend
      run: flutter pub get
      
    - name: Verify Flutter formatting
      working-directory: ./frontend
      run: dart format --output=none --set-exit-if-changed .
      
    - name: Analyze Flutter code
      working-directory: ./frontend
      run: flutter analyze
      
    - name: Run Flutter tests
      working-directory: ./frontend
      run: flutter test
      
  supabase:
    name: Deploy Supabase Functions
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Supabase CLI
      run: npm install -g supabase@1.123.4
      
    - name: Deploy Edge Functions
      working-directory: ./backend
      run: |
        supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      working-directory: ./frontend
      run: flutter pub get
      
    - name: Build Android APK
      working-directory: ./frontend
      run: flutter build apk --release
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: frontend/build/app/outputs/flutter-apk/app-release.apk
        
  build-web:
    name: Build Web App
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      working-directory: ./frontend
      run: flutter pub get
      
    - name: Build Web App
      working-directory: ./frontend
      run: flutter build web --release
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        
    - name: Upload Web build artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: frontend/build/web/
        
  deploy-web:
    name: Deploy Web to Supabase Storage
    runs-on: ubuntu-latest
    needs: build-web
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download Web build
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: ./web-build
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Supabase CLI
      run: npm install -g supabase@1.123.4
      
    - name: Deploy to Supabase Storage
      run: |
        # TODO: Implement web deployment to Supabase Storage
        echo "Web deployment placeholder - implement based on hosting strategy"
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}